Repository osmlab/atlas, pull requests merged in 2018-05, with the labels that each got.

#122 Add FerryTag
  src/main/java/org/openstreetmap/atlas/tags/FerryTag.java
Labels: Enhancement

#118 Fixing raw Atlas sectioning and slicing corner cases
  src/integrationTest/java/org/openstreetmap/atlas/geography/atlas/raw/RawAtlasIntegrationTest.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/dynamic/policy/DynamicAtlasPolicy.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/packed/PackedAtlasBuilder.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/raw/creation/RawAtlasGenerator.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/raw/sectioning/WaySectionProcessor.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/raw/slicing/RawAtlasPointAndLineSlicer.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/raw/slicing/RawAtlasRelationSlicer.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/raw/slicing/changeset/RelationChangeSet.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/raw/slicing/changeset/RelationChangeSetHandler.java
  src/test/java/org/openstreetmap/atlas/geography/atlas/raw/creation/RawAtlasGeneratorTest.java
  src/test/java/org/openstreetmap/atlas/geography/atlas/raw/sectioning/WaySectionProcessorTest.java
  src/test/java/org/openstreetmap/atlas/geography/atlas/raw/sectioning/WaySectionProcessorTestRule.java
  src/test/java/org/openstreetmap/atlas/geography/atlas/raw/slicing/RelationSlicingTest.java
  src/test/resources/org/openstreetmap/atlas/geography/atlas/raw/sectioning/lineWithRepeatedLocation.atlas.txt
  src/test/resources/org/openstreetmap/atlas/geography/atlas/raw/sectioning/loopWithRepeatedLocation.atlas.txt
Labels: Bug, Enhancement

#125 Conditionally suppress log message in NumericValidator.setRange()
  src/main/java/org/openstreetmap/atlas/tags/annotations/validation/NumericValidator.java
Labels: Enhancement

#126 Fixed bugs with MultiEntities that caused incorrect empty relations() returns
  src/main/java/org/openstreetmap/atlas/geography/atlas/multi/MultiArea.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/multi/MultiAtlas.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/multi/MultiAtlasBorderFixer.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/multi/MultiLine.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/multi/MultiNode.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/multi/MultiPoint.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/multi/MultiRelation.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/multi/SubAreaList.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/multi/SubLineList.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/multi/SubNodeList.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/multi/SubPointList.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/multi/TemporaryRelationMember.java
  src/test/java/org/openstreetmap/atlas/geography/atlas/dynamic/DynamicAtlasFilteredEntitiesTest.java
  src/test/java/org/openstreetmap/atlas/geography/atlas/dynamic/DynamicAtlasTest.java
  src/test/java/org/openstreetmap/atlas/geography/atlas/dynamic/rules/DynamicAtlasTestRule.java
  src/test/java/org/openstreetmap/atlas/geography/atlas/multi/MissingMultiEntityRelationTest.java
Labels: Bug

#123 Parallelizing Raw Atlas Way-Sectioning and Point/Line Slicing
  src/main/java/org/openstreetmap/atlas/geography/atlas/raw/creation/RawAtlasGenerator.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/raw/sectioning/WaySectionChangeSet.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/raw/sectioning/WaySectionProcessor.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/raw/slicing/CoordinateToNewPointMapping.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/raw/slicing/RawAtlasPointAndLineSlicer.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/raw/slicing/RawAtlasRelationSlicer.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/raw/slicing/changeset/ChangeSetHandler.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/raw/slicing/changeset/RelationChangeSet.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/raw/slicing/changeset/RelationChangeSetHandler.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/raw/slicing/changeset/SimpleChangeSet.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/raw/slicing/changeset/SimpleChangeSetHandler.java
  src/main/java/org/openstreetmap/atlas/utilities/collections/StringList.java
  src/test/java/org/openstreetmap/atlas/geography/atlas/raw/sectioning/WaySectionProcessorTest.java
  src/test/java/org/openstreetmap/atlas/geography/atlas/raw/sectioning/WaySectionProcessorTestRule.java
  src/test/resources/org/openstreetmap/atlas/geography/atlas/raw/sectioning/selfIntersectingLoop.atlas.txt
Labels: Enhancement

#130 Geometric surface for sharding
  src/main/java/org/openstreetmap/atlas/geography/sharding/DynamicTileSharding.java
  src/main/java/org/openstreetmap/atlas/geography/sharding/Sharding.java
  src/main/java/org/openstreetmap/atlas/geography/sharding/SlippyTileSharding.java
  src/test/java/org/openstreetmap/atlas/geography/sharding/SlippyTileTest.java
Labels: Enhancement
