Repository osmlab/atlas, pull requests merged in 2018-07, with the labels that each got.

#150 Way improperly excluded from network stitching
  src/main/java/org/openstreetmap/atlas/geography/atlas/pbf/OsmPbfProcessor.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/pbf/store/PbfMemoryStore.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/raw/creation/OsmPbfCounter.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/raw/slicing/RawAtlasSlicer.java
  src/main/java/org/openstreetmap/atlas/geography/boundary/CountryBoundaryMap.java
  src/test/java/org/openstreetmap/atlas/geography/atlas/pbf/OsmPbfProcessorTest.java
  src/test/java/org/openstreetmap/atlas/geography/atlas/raw/RawAtlasTest.java
  src/test/java/org/openstreetmap/atlas/geography/boundary/CountryBoundaryMapTest.java
  src/test/resources/org/openstreetmap/atlas/geography/atlas/pbf/DMA_boundary.txt
  src/test/resources/org/openstreetmap/atlas/geography/atlas/pbf/osmPbfProcessorTest_keepOutsideWaysThatAreConnected.osm
  src/test/resources/org/openstreetmap/atlas/geography/atlas/raw/DMA_boundary.txt
  src/test/resources/org/openstreetmap/atlas/geography/atlas/raw/osmPbfProcessorTest_keepOutsideWaysThatAreConnected.osm
  src/test/resources/org/openstreetmap/atlas/geography/boundary/DMA_boundary.txt
Labels: Bug, Data Change

#155 Fixing time logging statement
  src/main/java/org/openstreetmap/atlas/geography/atlas/raw/creation/RawAtlasGenerator.java
Labels: Enhancement

#158 Snake features losing nearest neighbor country code tag
  src/main/java/org/openstreetmap/atlas/geography/boundary/CountryBoundaryMap.java
  src/test/java/org/openstreetmap/atlas/geography/boundary/CountryBoundaryMapTest.java
  src/test/resources/org/openstreetmap/atlas/geography/boundary/DMA_snake_polyline.wkt
Labels: Bug, Data Change

#160 Fix NPE introduced by #158
  src/main/java/org/openstreetmap/atlas/geography/boundary/CountryBoundaryMap.java
Labels: Bug

#159 Disable pyatlas autoreleases until a fix is determined.
  .travis/deploy.sh
Labels: Bug

#157 Fixing JtsMultiPolyLineConverter behavior
  src/main/java/org/openstreetmap/atlas/geography/converters/jts/JtsMultiPolyLineConverter.java
  src/test/java/org/openstreetmap/atlas/geography/MultiPolyLineTest.java
Labels: Bug

#161 Do not section edge rings (loops)
  src/integrationTest/java/org/openstreetmap/atlas/geography/atlas/pbf/slicing/WaySectionProcessorIntegrationTest.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/pbf/slicing/WaySectionProcessor.java
Labels: Data Change, Enhancement

#168 Raw Atlas Logging Tweaks
  src/main/java/org/openstreetmap/atlas/geography/atlas/raw/sectioning/WaySectionProcessor.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/raw/slicing/RawAtlasCountrySlicer.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/raw/slicing/RawAtlasPointAndLineSlicer.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/raw/slicing/RawAtlasRelationSlicer.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/raw/slicing/changeset/RelationChangeSetHandler.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/raw/slicing/changeset/SimpleChangeSetHandler.java
Labels: Enhancement

#166 Add sonar integration
  .travis.yml
  .travis/build.sh
  README.md
  build.gradle
Labels: Enhancement

#169 Allow objects as geojson properties
  src/main/java/org/openstreetmap/atlas/geography/geojson/GeoJsonBuilder.java
  src/main/java/org/openstreetmap/atlas/geography/geojson/GeoJsonObject.java
  src/test/java/org/openstreetmap/atlas/geography/geojson/GeoJsonBuilderTest.java
Labels: New Feature

#170 [Sonar] Remove code smells
  src/main/java/org/openstreetmap/atlas/geography/atlas/Atlas.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/AtlasResourceLoader.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/BareAtlas.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/command/AbstractAtlasSubCommand.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/pbf/CloseableOsmosisReader.java
  src/test/java/org/openstreetmap/atlas/geography/atlas/IsAtlasTestCase.java
  src/test/java/org/openstreetmap/atlas/geography/atlas/multi/MultiAtlasOverlappingNodesFixerTest.java
Labels: Enhancement

#172 Sonar: Include code coverage & Build script improvements
  .travis/build.sh
  build.gradle
  gradle/deployment.gradle
  gradle/protobuf.gradle
  gradle/pyatlas.gradle
  gradle/quality.gradle
  src/main/java/org/openstreetmap/atlas/geography/atlas/packed/PackedAtlasSerializer.java
Labels: Enhancement, New Feature

#173 Upgrade to gradle 4.8.1
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
Labels: Enhancement

#171 Some diff readability enhancements for AtlasDelta
  src/main/java/org/openstreetmap/atlas/geography/atlas/delta/AtlasDelta.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/delta/Diff.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/items/Area.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/items/AtlasEntity.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/items/DiffViewFriendlyItem.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/items/Edge.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/items/Line.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/items/Node.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/items/Point.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/items/Relation.java
  src/test/java/org/openstreetmap/atlas/geography/atlas/delta/AtlasDeltaEdgeTest.java
  src/test/java/org/openstreetmap/atlas/geography/atlas/delta/AtlasDeltaRelationTest.java
  src/test/java/org/openstreetmap/atlas/geography/atlas/delta/AtlasDeltaRelationsTest.java
Labels: Enhancement

#177 Fix code smells
  src/main/java/org/openstreetmap/atlas/exception/LoadAtlasFromResourceException.java
  src/main/java/org/openstreetmap/atlas/geography/PolyLine.java
  src/main/java/org/openstreetmap/atlas/geography/Polygon.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/AtlasMetaData.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/BareAtlas.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/builder/GeoJsonAtlasBuilder.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/builder/RelationBean.java
Labels: Enhancement

#176 Fix code smells
  src/main/java/org/openstreetmap/atlas/geography/atlas/multi/MultiAtlasLoaderCommand.java
  src/main/java/org/openstreetmap/atlas/tags/annotations/extraction/SpeedExtractor.java
  src/main/java/org/openstreetmap/atlas/tags/annotations/validation/SpeedValidator.java
  src/main/java/org/openstreetmap/atlas/utilities/scalars/Speed.java
  src/test/java/org/openstreetmap/atlas/geography/atlas/items/complex/water/AbstractWaterIslandTest.java
Labels: Enhancement

#175 Fix code smells
  src/main/java/org/openstreetmap/atlas/geography/PolyLine.java
  src/main/java/org/openstreetmap/atlas/geography/sharding/preparation/TilePrinter.java
  src/main/java/org/openstreetmap/atlas/streaming/resource/zip/ZipFileWritableResource.java
  src/main/java/org/openstreetmap/atlas/utilities/archive/Extractor.java
  src/main/java/org/openstreetmap/atlas/utilities/collections/Iterables.java
  src/test/java/org/openstreetmap/atlas/utilities/archive/ExtractorTest.java
  src/test/resources/org/openstreetmap/atlas/utilities/archive/testExtractor.zip
Labels: Enhancement

#180 Fixed some code smells.
  src/main/java/org/openstreetmap/atlas/geography/Location.java
  src/main/java/org/openstreetmap/atlas/geography/MultiPolygon.java
  src/main/java/org/openstreetmap/atlas/geography/Polygon.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/command/AtlasFindEntitiesByIdSubCommand.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/command/AtlasResourceLoaderErrorSubCommand.java
Labels: Enhancement

#182 Overlapping allowed in AtlasEntityPolygonsFilter
  src/main/java/org/openstreetmap/atlas/utilities/filters/AtlasEntityPolygonsFilter.java
  src/test/java/org/openstreetmap/atlas/utilities/filters/AtlasEntityPolygonsFilterTest.java
  src/test/java/org/openstreetmap/atlas/utilities/filters/AtlasEntityPolygonsFilterTestRule.java
  src/test/resources/org/openstreetmap/atlas/utilities/filters/overlappingPolygons.osm
Labels: Enhancement

#181 Fixing code smells
  src/main/java/org/openstreetmap/atlas/geography/Polygon.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/Crawler.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/items/TurnRestriction.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/items/complex/islands/ComplexIslandFinder.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/multi/MultiAtlasBorderFixer.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/pbf/slicing/ChangeSet.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/raw/creation/RawAtlasGenerator.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/raw/sectioning/WaySectionProcessor.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/raw/slicing/RawAtlasRelationSlicer.java
  src/main/java/org/openstreetmap/atlas/geography/boundary/CountryBoundaryMap.java
  src/main/java/org/openstreetmap/atlas/geography/boundary/CountryBoundaryMapCompareCommand.java
  src/main/java/org/openstreetmap/atlas/geography/boundary/CountryShardListing.java
  src/main/java/org/openstreetmap/atlas/geography/boundary/CountryToShardListing.java
  src/main/java/org/openstreetmap/atlas/streaming/readers/json/converters/PolyLineCoordinateConverter.java
  src/main/java/org/openstreetmap/atlas/streaming/readers/json/converters/PolygonCoordinateConverter.java
Labels: Enhancement
