Repository osmlab/atlas, pull requests merged in 2018-10, with the labels that each got.

#231 Added in FilteredIterable
  src/main/java/org/openstreetmap/atlas/utilities/collections/FilteredIterable.java
  src/main/java/org/openstreetmap/atlas/utilities/collections/Iterables.java
  src/main/java/org/openstreetmap/atlas/utilities/collections/StreamIterable.java
  src/test/java/org/openstreetmap/atlas/utilities/collections/FilteredIterableTest.java
Labels: New Feature

#230 Fixing way sectioning bug in raw atlas
  src/main/java/org/openstreetmap/atlas/geography/atlas/raw/sectioning/WaySectionProcessor.java
  src/test/java/org/openstreetmap/atlas/geography/atlas/raw/sectioning/WaySectionProcessorTest.java
  src/test/java/org/openstreetmap/atlas/geography/atlas/raw/sectioning/WaySectionProcessorTestRule.java
  src/test/resources/org/openstreetmap/atlas/geography/atlas/raw/sectioning/malformedPolyLine.atlas.txt
  src/test/resources/org/openstreetmap/atlas/geography/atlas/raw/sectioning/malformedPolyLineBoundaryMap.txt
Labels: Bug

#229 Improve and expand TaggableFilter and AtlasStatistics
  README.md
  src/main/java/org/openstreetmap/atlas/geography/atlas/statistics/Counter.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/statistics/coverage/Coverage.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/statistics/coverage/poi/CountCoverage.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/statistics/coverage/poi/EdgesCountCoverage.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/statistics/coverage/poi/LastUserNameCountCoverage.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/statistics/coverage/poi/SimpleCoverage.java
  src/main/java/org/openstreetmap/atlas/tags/filters/ConfiguredTaggableFilter.java
  src/main/java/org/openstreetmap/atlas/tags/filters/LineFilterConverter.java
  src/main/java/org/openstreetmap/atlas/tags/filters/README.md
  src/main/java/org/openstreetmap/atlas/tags/filters/TaggableFilter.java
  src/main/resources/org/openstreetmap/atlas/geography/atlas/statistics/coverage/poi/counts.txt
  src/test/java/org/openstreetmap/atlas/geography/atlas/statistics/AtlasStatisticsTest.java
  src/test/java/org/openstreetmap/atlas/geography/atlas/statistics/AtlasStatisticsTestRule.java
  src/test/java/org/openstreetmap/atlas/geography/atlas/statistics/coverage/poi/CountCoverageTest.java
  src/test/java/org/openstreetmap/atlas/tags/filters/ConfiguredTaggableFilterTest.java
  src/test/java/org/openstreetmap/atlas/tags/filters/TaggableFilterTest.java
  src/test/resources/org/openstreetmap/atlas/geography/atlas/statistics/addressAtlas.josm.osm
  src/test/resources/org/openstreetmap/atlas/geography/atlas/statistics/ferryAtlas.josm.osm
  src/test/resources/org/openstreetmap/atlas/geography/atlas/statistics/refsAtlas.josm.osm
  src/test/resources/org/openstreetmap/atlas/geography/atlas/statistics/waterAtlas.josm.osm
Labels: Enhancement, New Feature

#233 Added in Relation flattening
  src/main/java/org/openstreetmap/atlas/geography/atlas/items/Relation.java
  src/test/java/org/openstreetmap/atlas/geography/atlas/items/RelationFlatteningRule.java
  src/test/java/org/openstreetmap/atlas/geography/atlas/items/RelationFlatteningTest.java
Labels: New Feature

#234 Added parallelization support to StreamIterator
  src/main/java/org/openstreetmap/atlas/utilities/collections/Iterables.java
  src/main/java/org/openstreetmap/atlas/utilities/collections/StreamIterable.java
  src/test/java/org/openstreetmap/atlas/utilities/collections/StreamIterableTest.java
Labels: Enhancement

#236 Pool can have a companion ticker thread
  src/main/java/org/openstreetmap/atlas/utilities/scalars/Duration.java
  src/main/java/org/openstreetmap/atlas/utilities/threads/LogTicker.java
  src/main/java/org/openstreetmap/atlas/utilities/threads/Pool.java
  src/main/java/org/openstreetmap/atlas/utilities/threads/Result.java
  src/main/java/org/openstreetmap/atlas/utilities/threads/Ticker.java
  src/test/java/org/openstreetmap/atlas/utilities/scalars/DurationTest.java
  src/test/java/org/openstreetmap/atlas/utilities/threads/PoolTest.java
Labels: New Feature

#235 Improved PBF Ingest Documentation
  README.md
  src/integrationTest/java/org/openstreetmap/atlas/geography/atlas/raw/RawAtlasIntegrationTest.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/raw/creation/README.md
  src/main/java/org/openstreetmap/atlas/geography/atlas/raw/sectioning/NodeOccurrenceCounter.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/raw/sectioning/README.md
  src/main/java/org/openstreetmap/atlas/geography/atlas/raw/sectioning/WaySectionChangeSet.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/raw/sectioning/WaySectionProcessor.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/raw/slicing/README.md
  src/main/java/org/openstreetmap/atlas/geography/atlas/raw/slicing/RawAtlasPointAndLineSlicer.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/raw/slicing/RawAtlasRelationSlicer.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/raw/slicing/RawAtlasSlicer.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/raw/slicing/changeset/ChangeSetHandler.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/raw/slicing/changeset/RelationChangeSet.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/raw/slicing/changeset/RelationChangeSetHandler.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/raw/slicing/changeset/SimpleChangeSet.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/raw/temporary/TemporaryEdge.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/raw/temporary/TemporaryEntity.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/raw/temporary/TemporaryLine.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/raw/temporary/TemporaryNode.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/raw/temporary/TemporaryPoint.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/raw/temporary/TemporaryRelation.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/raw/temporary/TemporaryRelationMember.java
  src/test/java/org/openstreetmap/atlas/geography/atlas/raw/slicing/TemporaryEntityTest.java
Labels: Documentation, Enhancement

#238 Fixing main page README links
  README.md
Labels: Documentation

#240 Properly handling filtered out nested relations
  src/main/java/org/openstreetmap/atlas/geography/atlas/raw/sectioning/WaySectionProcessor.java
  src/test/java/org/openstreetmap/atlas/geography/atlas/raw/sectioning/WaySectionProcessorTest.java
  src/test/java/org/openstreetmap/atlas/geography/atlas/raw/sectioning/WaySectionProcessorTestRule.java
  src/test/resources/org/openstreetmap/atlas/geography/atlas/raw/sectioning/nestedRelationRemoval.atlas.txt
  src/test/resources/org/openstreetmap/atlas/geography/atlas/raw/sectioning/nestedRelationRemovalBoundaryMap.txt
Labels: Bug

#245 Add sudo:false for travis VM
  .travis.yml
Labels: Bug

#243 AtlasStatistics: protect from malformed multipolygons
  src/main/java/org/openstreetmap/atlas/geography/atlas/statistics/coverage/poi/SimpleCoverage.java
  src/main/java/org/openstreetmap/atlas/utilities/scalars/Surface.java
  src/test/java/org/openstreetmap/atlas/geography/atlas/statistics/AtlasStatisticsTest.java
  src/test/resources/org/openstreetmap/atlas/geography/atlas/statistics/waterAtlas.josm.osm
Labels: Bug

#244 Improve buildings tag coverage
  src/main/java/org/openstreetmap/atlas/tags/BuildingHeightTag.java
  src/main/java/org/openstreetmap/atlas/tags/BuildingPartTag.java
  src/main/java/org/openstreetmap/atlas/tags/BuildingTag.java
Labels: Enhancement

#237 Added Boundary deduplication logic
  src/main/java/org/openstreetmap/atlas/geography/atlas/items/complex/boundaries/ComplexBoundary.java
  src/main/java/org/openstreetmap/atlas/geography/boundary/CountryBoundaryMap.java
  src/test/java/org/openstreetmap/atlas/geography/boundary/CountryBoundaryMapTest.java
  src/test/resources/org/openstreetmap/atlas/geography/boundary/HTI_boundary.txt
  src/test/resources/org/openstreetmap/atlas/geography/boundary/USA_HTI_overlapping.atlas.txt
  src/test/resources/org/openstreetmap/atlas/geography/boundary/USA_boundary_reduced.txt
Labels: Enhancement

#226 Relation Bean from relation
  src/main/java/org/openstreetmap/atlas/geography/atlas/builder/RelationBean.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/items/Relation.java
  src/test/java/org/openstreetmap/atlas/geography/atlas/items/RelationBeanTest.java
  src/test/java/org/openstreetmap/atlas/geography/atlas/items/RelationBeanTestRule.java
Labels: Enhancement

#247 Fixing way-sectioning hotspot
  src/main/java/org/openstreetmap/atlas/geography/atlas/raw/sectioning/WaySectionChangeSet.java
Labels: Enhancement

#248 Remove duplicate building tags
  src/main/java/org/openstreetmap/atlas/tags/BuildingTag.java
  src/test/java/org/openstreetmap/atlas/utilities/collections/StreamIterableTest.java
Labels: Bug

#251 subAtlas(Polygon) missing reverse edge and performance
  src/main/java/org/openstreetmap/atlas/geography/atlas/BareAtlas.java
  src/test/java/org/openstreetmap/atlas/geography/atlas/SubAtlasRule.java
  src/test/java/org/openstreetmap/atlas/geography/atlas/SubAtlasTest.java
Labels: Bug, Enhancement

#249 Added a size cutoff to the BigNodeFinder.isDualCarriageWayJunctionRoute
  src/main/java/org/openstreetmap/atlas/geography/atlas/items/complex/bignode/BigNodeFinder.java
Labels: Bug, Data Change

#254 Fix double locking sonar error
  config/checkstyle/checkstyle.xml
  src/main/java/org/openstreetmap/atlas/geography/atlas/AbstractAtlas.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/Atlas.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/BareAtlas.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/items/ItemType.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/multi/MultiAtlas.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/packed/PackedAtlas.java
  src/test/java/org/openstreetmap/atlas/geography/atlas/BareAtlasTest.java
  src/test/java/org/openstreetmap/atlas/geography/atlas/items/ItemTypeTest.java
Labels: Bug, Enhancement

#256 TaggableFilter was not serializable in some cases
  src/main/java/org/openstreetmap/atlas/tags/filters/LineFilterConverter.java
  src/test/java/org/openstreetmap/atlas/tags/filters/TaggableFilterTest.java
Labels: Bug

#257 Add Node count to shard data density calculation
  src/main/java/org/openstreetmap/atlas/geography/sharding/preparation/TilePrinter.java
Labels: Enhancement

#259 Updated Enum Set For Turn Restrictions
  src/main/java/org/openstreetmap/atlas/tags/TurnRestrictionTag.java
Labels: Data Change, Enhancement

#262 Remove double-checked locking in DynamicGridIndexBuilder
  src/main/java/org/openstreetmap/atlas/geography/boundary/DynamicGridIndexBuilder.java
Labels: Bug

#263 Use latest gradle version - 4.10.2
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
Labels: Duplicate

#264 Now log an exception properly in PackedAtlasSerializer
  src/main/java/org/openstreetmap/atlas/geography/atlas/packed/PackedAtlasSerializer.java
Labels: Enhancement

#258 ResourceCache API overhaul
  src/main/java/org/openstreetmap/atlas/utilities/caching/ConcurrentResourceCache.java
  src/main/java/org/openstreetmap/atlas/utilities/caching/LocalFileInMemoryCache.java
  src/main/java/org/openstreetmap/atlas/utilities/caching/README.md
  src/main/java/org/openstreetmap/atlas/utilities/caching/ResourceCache.java
  src/main/java/org/openstreetmap/atlas/utilities/caching/strategies/AbstractCachingStrategy.java
  src/main/java/org/openstreetmap/atlas/utilities/caching/strategies/ByteArrayCachingStrategy.java
  src/main/java/org/openstreetmap/atlas/utilities/caching/strategies/CachingStrategy.java
  src/main/java/org/openstreetmap/atlas/utilities/caching/strategies/GlobalNamespaceCachingStrategy.java
  src/main/java/org/openstreetmap/atlas/utilities/caching/strategies/NamespaceCachingStrategy.java
  src/main/java/org/openstreetmap/atlas/utilities/caching/strategies/NoCachingStrategy.java
  src/main/java/org/openstreetmap/atlas/utilities/caching/strategies/SystemTemporaryFileCachingStrategy.java
  src/test/java/org/openstreetmap/atlas/utilities/caching/ByteArrayCachingStrategyResizeTest.java
  src/test/java/org/openstreetmap/atlas/utilities/caching/CachingTests.java
Labels: Enhancement

#260 Relation member consistency when an OSM Node is both a Node and Point
  src/main/java/org/openstreetmap/atlas/geography/atlas/raw/sectioning/WaySectionProcessor.java
  src/test/java/org/openstreetmap/atlas/geography/atlas/raw/sectioning/WaySectionProcessorTest.java
  src/test/java/org/openstreetmap/atlas/geography/atlas/raw/sectioning/WaySectionProcessorTestRule.java
  src/test/resources/org/openstreetmap/atlas/geography/atlas/raw/sectioning/nodeAndPointAsRelationMember.atlas.txt
  src/test/resources/org/openstreetmap/atlas/geography/atlas/raw/sectioning/nodeAndPointRelationMemberBoundaryMap.txt
Labels: Data Change, Enhancement

#261 Protect from number formatting errors in AtlasStatistics
  src/main/java/org/openstreetmap/atlas/geography/atlas/statistics/AtlasStatistics.java
  src/test/java/org/openstreetmap/atlas/geography/atlas/statistics/AtlasStatisticsTest.java
Labels: Bug

#265 Updating sectioning README with more details
  src/main/java/org/openstreetmap/atlas/geography/atlas/raw/sectioning/README.md
Labels: Documentation

#267 Added a getCacheID method to ConcurrentResourceCache
  src/main/java/org/openstreetmap/atlas/utilities/caching/ConcurrentResourceCache.java
  src/main/java/org/openstreetmap/atlas/utilities/caching/strategies/AbstractCachingStrategy.java
Labels: Enhancement
