Repository osmlab/atlas, pull requests merged in 2018-12, with the labels that each got.

#292 [Change] Fixed bug with missing parent relations
  src/main/java/org/openstreetmap/atlas/geography/atlas/bloated/BloatedArea.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/bloated/BloatedAtlas.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/bloated/BloatedEdge.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/bloated/BloatedEntity.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/bloated/BloatedLine.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/bloated/BloatedNode.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/bloated/BloatedPoint.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/bloated/BloatedRelation.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/builder/RelationBean.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/change/AtlasChangeGenerator.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/change/Change.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/change/ChangeArea.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/change/ChangeEdge.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/change/ChangeEntity.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/change/ChangeLine.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/change/ChangeNode.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/change/ChangePoint.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/change/ChangeRelation.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/change/FeatureChange.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/dynamic/DynamicRelation.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/items/Relation.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/multi/MultiRelation.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/packed/PackedRelation.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/validators/AtlasValidator.java
  src/test/java/org/openstreetmap/atlas/geography/atlas/bloated/BloatedAreaTest.java
  src/test/java/org/openstreetmap/atlas/geography/atlas/bloated/BloatedEdgeTest.java
  src/test/java/org/openstreetmap/atlas/geography/atlas/bloated/BloatedLineTest.java
  src/test/java/org/openstreetmap/atlas/geography/atlas/bloated/BloatedNodeTest.java
  src/test/java/org/openstreetmap/atlas/geography/atlas/bloated/BloatedPointTest.java
  src/test/java/org/openstreetmap/atlas/geography/atlas/bloated/BloatedRelationTest.java
  src/test/java/org/openstreetmap/atlas/geography/atlas/change/AtlasChangeGeneratorAddTurnRestrictions.java
  src/test/java/org/openstreetmap/atlas/geography/atlas/change/AtlasChangeGeneratorSplitRoundabout.java
  src/test/java/org/openstreetmap/atlas/geography/atlas/change/ChangeAtlasTest.java
  src/test/java/org/openstreetmap/atlas/geography/atlas/change/FeatureChangeTest.java
  src/test/java/org/openstreetmap/atlas/geography/atlas/change/MultipleChangeAtlasTest.java
Labels: Duplicate

#294 Expanding Atlas area definition, removing irrelevant test
  src/main/resources/org/openstreetmap/atlas/geography/atlas/pbf/atlas-area.json
  src/test/java/org/openstreetmap/atlas/geography/atlas/raw/sectioning/WaySectionProcessorTest.java
Labels: Data Change

#295 [Change] Keep track of explicitly removed relation members
  src/main/java/org/openstreetmap/atlas/geography/atlas/bloated/BloatedRelation.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/builder/RelationBean.java
  src/test/java/org/openstreetmap/atlas/geography/atlas/bloated/BloatedRelationTest.java
  src/test/java/org/openstreetmap/atlas/geography/atlas/change/AtlasChangeGeneratorSplitRoundabout.java
  src/test/java/org/openstreetmap/atlas/geography/atlas/change/ChangeAtlasTest.java
  src/test/java/org/openstreetmap/atlas/geography/atlas/change/MultipleChangeAtlasTest.java
Labels: Duplicate

#293 [Change] Added an AtlasDiff class to produce Changes from a before and after Atlas
  src/main/java/org/openstreetmap/atlas/geography/atlas/bloated/BloatedArea.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/bloated/BloatedEdge.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/bloated/BloatedLine.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/bloated/BloatedNode.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/bloated/BloatedPoint.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/bloated/BloatedRelation.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/builder/RelationBean.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/change/Change.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/change/ChangeBuilder.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/change/FeatureChange.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/change/diff/AtlasDiff.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/change/diff/AtlasDiffHelper.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/change/validators/ChangeValidator.java
  src/test/java/org/openstreetmap/atlas/geography/atlas/bloated/BloatedRelationTest.java
  src/test/java/org/openstreetmap/atlas/geography/atlas/change/AtlasChangeGeneratorSplitRoundabout.java
  src/test/java/org/openstreetmap/atlas/geography/atlas/change/ChangeAtlasTest.java
  src/test/java/org/openstreetmap/atlas/geography/atlas/change/MultipleChangeAtlasTest.java
  src/test/java/org/openstreetmap/atlas/geography/atlas/change/diff/AtlasDiffTest.java
  src/test/java/org/openstreetmap/atlas/geography/atlas/change/diff/AtlasDiffTestRule.java
  src/test/resources/org/openstreetmap/atlas/geography/atlas/change/diff/DiffAtlas1.josm.osm
  src/test/resources/org/openstreetmap/atlas/geography/atlas/change/diff/DiffAtlas2.josm.osm
Labels: Duplicate

#299 Enable sonar with each pull request
  .travis.yml
  .travis/sonar.sh
  build.gradle
Labels: New Feature

#303 Added College as an Amenity
  src/main/java/org/openstreetmap/atlas/tags/AmenityTag.java
Labels: Enhancement

#304 Fixed some Sonar issues. Mostly just ignoring false positives
  src/main/java/org/openstreetmap/atlas/geography/atlas/bloated/BloatedAtlas.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/change/ChangeAtlas.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/change/FeatureChange.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/change/diff/AtlasDiff.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/change/diff/AtlasDiffHelper.java
Labels: Duplicate

#305 [HACK] Allow travis to upload to Sonatype from GCE using scripts
  build.gradle
  gradle/deployment.gradle
  gradle/dropSonatype.sh
  gradle/releaseSonatype.sh
  gradle/uploadAndRelease.sh
  gradle/uploadToNexus.sh
Labels: Bug

#308 adding highway=toll_gantry tag
  src/main/java/org/openstreetmap/atlas/tags/HighwayTag.java
Labels: Enhancement

#307 Save change features as GeoJson
  src/main/java/org/openstreetmap/atlas/geography/GeojsonPrintable.java
  src/main/java/org/openstreetmap/atlas/geography/GeometricSurface.java
  src/main/java/org/openstreetmap/atlas/geography/GeometryPrintable.java
  src/main/java/org/openstreetmap/atlas/geography/Location.java
  src/main/java/org/openstreetmap/atlas/geography/MultiPolygon.java
  src/main/java/org/openstreetmap/atlas/geography/PolyLine.java
  src/main/java/org/openstreetmap/atlas/geography/Rectangle.java
  src/main/java/org/openstreetmap/atlas/geography/WkbPrintable.java
  src/main/java/org/openstreetmap/atlas/geography/WktPrintable.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/builder/RelationBean.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/change/Change.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/change/FeatureChange.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/change/serializer/ChangeGeoJsonSerializer.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/change/serializer/FeatureChangeGeoJsonSerializer.java
  src/test/java/org/openstreetmap/atlas/geography/RectangleTest.java
  src/test/java/org/openstreetmap/atlas/geography/atlas/change/serializer/ChangeGeoJsonSerializerTest.java
  src/test/java/org/openstreetmap/atlas/geography/atlas/change/serializer/FeatureChangeGeoJsonSerializerTest.java
  src/test/resources/org/openstreetmap/atlas/geography/atlas/change/serializer/change.json
  src/test/resources/org/openstreetmap/atlas/geography/atlas/change/serializer/serializedAreaFull.json
  src/test/resources/org/openstreetmap/atlas/geography/atlas/change/serializer/serializedAreaNull.json
  src/test/resources/org/openstreetmap/atlas/geography/atlas/change/serializer/serializedAreaRemove.json
  src/test/resources/org/openstreetmap/atlas/geography/atlas/change/serializer/serializedEdgeFull.json
  src/test/resources/org/openstreetmap/atlas/geography/atlas/change/serializer/serializedEdgeNull.json
  src/test/resources/org/openstreetmap/atlas/geography/atlas/change/serializer/serializedEdgeRemove.json
  src/test/resources/org/openstreetmap/atlas/geography/atlas/change/serializer/serializedLineFull.json
  src/test/resources/org/openstreetmap/atlas/geography/atlas/change/serializer/serializedLineNull.json
  src/test/resources/org/openstreetmap/atlas/geography/atlas/change/serializer/serializedLineRemove.json
  src/test/resources/org/openstreetmap/atlas/geography/atlas/change/serializer/serializedNodeFull.json
  src/test/resources/org/openstreetmap/atlas/geography/atlas/change/serializer/serializedNodeNull.json
  src/test/resources/org/openstreetmap/atlas/geography/atlas/change/serializer/serializedNodeRemove.json
  src/test/resources/org/openstreetmap/atlas/geography/atlas/change/serializer/serializedPointFull.json
  src/test/resources/org/openstreetmap/atlas/geography/atlas/change/serializer/serializedPointNull.json
  src/test/resources/org/openstreetmap/atlas/geography/atlas/change/serializer/serializedPointRemove.json
  src/test/resources/org/openstreetmap/atlas/geography/atlas/change/serializer/serializedRelationFull.json
  src/test/resources/org/openstreetmap/atlas/geography/atlas/change/serializer/serializedRelationNull.json
  src/test/resources/org/openstreetmap/atlas/geography/atlas/change/serializer/serializedRelationRemove.json
Labels: New Feature

#309 Length and Altitude Extraction
  src/main/java/org/openstreetmap/atlas/geography/atlas/items/complex/buildings/HeightConverter.java
  src/main/java/org/openstreetmap/atlas/tags/BuildingHeightTag.java
  src/main/java/org/openstreetmap/atlas/tags/HeightTag.java
  src/main/java/org/openstreetmap/atlas/tags/MaxHeightTag.java
  src/main/java/org/openstreetmap/atlas/tags/MaxWidthTag.java
  src/main/java/org/openstreetmap/atlas/tags/MinHeightTag.java
  src/main/java/org/openstreetmap/atlas/tags/WidthTag.java
  src/main/java/org/openstreetmap/atlas/tags/annotations/extraction/AltitudeExtractor.java
  src/main/java/org/openstreetmap/atlas/tags/annotations/extraction/LengthExtractor.java
  src/main/java/org/openstreetmap/atlas/tags/annotations/validation/LengthValidator.java
  src/main/java/org/openstreetmap/atlas/utilities/scalars/Distance.java
  src/test/java/org/openstreetmap/atlas/tags/annotations/extraction/AltitudeExtractorTest.java
  src/test/java/org/openstreetmap/atlas/tags/annotations/extraction/LengthExtractorTest.java
  src/test/java/org/openstreetmap/atlas/tags/annotations/validation/LengthValidatorTest.java
Labels: New Feature

#311 Fix some Sonar issues
  src/main/java/org/openstreetmap/atlas/geography/Location.java
  src/main/java/org/openstreetmap/atlas/geography/Snapper.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/geojson/LineDelimitedGeoJsonConverter.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/items/Edge.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/items/Route.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/items/TurnRestriction.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/items/complex/ComplexEntity.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/items/complex/boundaries/ComplexBoundary.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/items/complex/buildings/BuildingPart.java
  src/main/java/org/openstreetmap/atlas/locale/IsoCountry.java
  src/main/java/org/openstreetmap/atlas/streaming/resource/File.java
  src/main/java/org/openstreetmap/atlas/tags/annotations/validation/TagDocumenter.java
Labels: Enhancement

#312 DynamicAtlas: Aggressively load relations in preemptive loading
  src/main/java/org/openstreetmap/atlas/geography/WktPrintable.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/BareAtlas.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/builder/RelationBean.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/dynamic/DynamicAtlas.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/dynamic/DynamicAtlasExpander.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/dynamic/policy/DynamicAtlasPolicy.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/items/Area.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/items/AtlasEntity.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/items/LineItem.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/items/LocationItem.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/items/Relation.java
  src/main/java/org/openstreetmap/atlas/geography/sharding/Shard.java
  src/main/java/org/openstreetmap/atlas/geography/sharding/SlippyTile.java
  src/test/java/org/openstreetmap/atlas/geography/atlas/dynamic/DynamicAtlasAgressiveRelationsTest.java
  src/test/java/org/openstreetmap/atlas/geography/atlas/dynamic/DynamicAtlasFilteredEntitiesTest.java
  src/test/java/org/openstreetmap/atlas/geography/atlas/dynamic/DynamicAtlasTest.java
  src/test/java/org/openstreetmap/atlas/geography/atlas/dynamic/rules/DynamicAtlasTestRule.java
  src/test/resources/org/openstreetmap/atlas/geography/atlas/dynamic/rules/z12all.atlas.geojson
  src/test/resources/org/openstreetmap/atlas/geography/atlas/dynamic/rules/z12x1349y1869.atlas.geojson
  src/test/resources/org/openstreetmap/atlas/geography/atlas/dynamic/rules/z12x1349y1870.atlas.geojson
  src/test/resources/org/openstreetmap/atlas/geography/atlas/dynamic/rules/z12x1350y1869.atlas.geojson
  src/test/resources/org/openstreetmap/atlas/geography/atlas/dynamic/rules/z12x1350y1870.atlas.geojson
Labels: Bug, Enhancement
