Repository osmlab/atlas, pull requests merged in 2018-02, with the labels that each got.

#79 Added JTS Polygon implementation for special use cases
  src/main/java/org/openstreetmap/atlas/geography/Polygon.java
  src/test/java/org/openstreetmap/atlas/geography/PolygonTest.java
  src/test/java/org/openstreetmap/atlas/geography/PolygonTestRule.java
  src/test/resources/org/openstreetmap/atlas/geography/fourSelfIntersectingPolygon.osm
  src/test/resources/org/openstreetmap/atlas/geography/polygonWithFlatZeroAreaPart.osm
  src/test/resources/org/openstreetmap/atlas/geography/polygonWithInclinedZeroArea.osm
  src/test/resources/org/openstreetmap/atlas/geography/selfIntersectingPolygon.osm
Labels: Bug

#81 Update ShardFileOverlapsPolygon to match shard resources of other types
  src/main/java/org/openstreetmap/atlas/geography/atlas/ShardFileOverlapsPolygon.java
  src/test/java/org/openstreetmap/atlas/geography/atlas/ShardFileOverlapsPolygonTest.java
Labels: Enhancement

#78 Raw Atlas Way Sectioning
  src/integrationTest/java/org/openstreetmap/atlas/geography/atlas/raw/OsmPbfToSlicedRawAtlasTest.java
  src/main/java/org/openstreetmap/atlas/geography/PolyLine.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/AtlasMetaData.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/items/LineItem.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/multi/TemporaryOrderedLocation.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/pbf/AtlasLoadingOption.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/pbf/store/PbfOneWay.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/pbf/store/TagMap.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/raw/creation/RawAtlasGenerator.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/raw/sectioning/NodeOccurrenceCounter.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/raw/sectioning/WaySectionChangeSet.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/raw/sectioning/WaySectionProcessor.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/raw/slicing/RawAtlasPointAndLineSlicer.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/raw/slicing/RawAtlasRelationSlicer.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/raw/slicing/temporary/TemporaryEdge.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/raw/slicing/temporary/TemporaryNode.java
  src/main/java/org/openstreetmap/atlas/tags/SyntheticDuplicateOsmNodeTag.java
  src/main/java/org/openstreetmap/atlas/utilities/collections/StreamIterable.java
  src/main/resources/org/openstreetmap/atlas/geography/atlas/pbf/atlas-area.json
  src/test/java/org/openstreetmap/atlas/geography/PolyLineTest.java
  src/test/java/org/openstreetmap/atlas/geography/atlas/items/EdgeTest.java
  src/test/java/org/openstreetmap/atlas/geography/atlas/raw/creation/RawAtlasGeneratorTest.java
  src/test/java/org/openstreetmap/atlas/geography/atlas/raw/sectioning/WaySectionProcessorTest.java
  src/test/java/org/openstreetmap/atlas/geography/atlas/raw/sectioning/WaySectionProcessorTestRule.java
  src/test/java/org/openstreetmap/atlas/utilities/collections/StreamIterableTest.java
  src/test/resources/org/openstreetmap/atlas/geography/atlas/raw/sectioning/bidirectionalRing.atlas.txt
  src/test/resources/org/openstreetmap/atlas/geography/atlas/raw/sectioning/lineWithBarrier.atlas.txt
  src/test/resources/org/openstreetmap/atlas/geography/atlas/raw/sectioning/lineWithLoopAtEnd.atlas.txt
  src/test/resources/org/openstreetmap/atlas/geography/atlas/raw/sectioning/lineWithLoopAtStart.atlas.txt
  src/test/resources/org/openstreetmap/atlas/geography/atlas/raw/sectioning/loopingWayWithIntersection.atlas.txt
  src/test/resources/org/openstreetmap/atlas/geography/atlas/raw/sectioning/oneWayRing.atlas.txt
  src/test/resources/org/openstreetmap/atlas/geography/atlas/raw/sectioning/oneWaySimpleLine.atlas.txt
  src/test/resources/org/openstreetmap/atlas/geography/atlas/raw/sectioning/reversedOneWayLine.atlas.txt
  src/test/resources/org/openstreetmap/atlas/geography/atlas/raw/sectioning/ringWithSingleIntersection.atlas.txt
  src/test/resources/org/openstreetmap/atlas/geography/atlas/raw/sectioning/roundAbout.atlas.txt
  src/test/resources/org/openstreetmap/atlas/geography/atlas/raw/sectioning/simpleBiDirectionalLine.atlas.txt
Labels: Enhancement, New Feature

#80 Allow updating AtlasMetaData tags during PackedAtlasCloning
  src/main/java/org/openstreetmap/atlas/geography/atlas/AtlasMetaData.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/packed/PackedAtlasCloner.java
  src/test/java/org/openstreetmap/atlas/geography/atlas/packed/PackedAtlasClonerTest.java
Labels: Bug, Enhancement

#83 OsmPbfReader to close the pbf InputStreams once Atlas is produced
  src/main/java/org/openstreetmap/atlas/geography/atlas/pbf/OsmPbfLoader.java
  src/test/java/org/openstreetmap/atlas/geography/atlas/pbf/OsmosisReaderMock.java
Labels: Bug

#84 Changed how compression works with ZipWritableResource
  src/main/java/org/openstreetmap/atlas/streaming/resource/zip/ZipWritableResource.java
  src/test/java/org/openstreetmap/atlas/streaming/resource/zip/ZipResourceTest.java
Labels: Enhancement

#86 Way Sectioning Cleanup
  src/main/java/org/openstreetmap/atlas/geography/PolyLine.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/packed/PackedAtlas.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/pbf/CloseableOsmosisReader.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/pbf/OsmPbfLoader.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/raw/creation/RawAtlasGenerator.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/raw/sectioning/NodeOccurrenceCounter.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/raw/sectioning/WaySectionChangeSet.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/raw/sectioning/WaySectionProcessor.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/raw/slicing/temporary/TemporaryEdge.java
  src/main/java/org/openstreetmap/atlas/tags/RailwayTag.java
  src/main/resources/org/openstreetmap/atlas/geography/atlas/pbf/atlas-area.json
  src/test/java/org/openstreetmap/atlas/geography/atlas/pbf/OsmosisReaderMock.java
  src/test/java/org/openstreetmap/atlas/geography/atlas/raw/creation/RawAtlasGeneratorTest.java
Labels: Bug, Enhancement
