Repository osmlab/atlas, pull requests merged in 2018-04, with the labels that each got.

#104 AtlasStatistics Unterminated CSV quoted fields Fix
  src/main/java/org/openstreetmap/atlas/geography/atlas/statistics/AtlasStatistics.java
  src/test/java/org/openstreetmap/atlas/geography/atlas/statistics/AtlasStatisticsTest.java
Labels: Bug

#101 Updating Geojson Polygon/MultiPolygon Read/Write
  src/main/java/org/openstreetmap/atlas/geography/MultiPolygon.java
  src/main/java/org/openstreetmap/atlas/geography/geojson/GeoJsonBuilder.java
  src/main/java/org/openstreetmap/atlas/streaming/readers/json/converters/MultiPolygonCoordinateConverter.java
  src/main/java/org/openstreetmap/atlas/streaming/readers/json/converters/PolygonCoordinateConverter.java
  src/main/java/org/openstreetmap/atlas/streaming/readers/json/deserializers/PolygonDeserializer.java
  src/test/java/org/openstreetmap/atlas/geography/geojson/GeoJsonBuilderTest.java
  src/test/java/org/openstreetmap/atlas/streaming/readers/GeoJsonReaderTest.java
  src/test/resources/org/openstreetmap/atlas/streaming/readers/geojson-polygon.json
Labels: Enhancement

#100 GeometricSurface Interface added + Utilities
  src/main/java/org/openstreetmap/atlas/geography/GeometricSurface.java
  src/main/java/org/openstreetmap/atlas/geography/MultiPolygon.java
  src/main/java/org/openstreetmap/atlas/geography/Polygon.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/items/Area.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/items/AtlasEntity.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/items/LineItem.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/items/LocationItem.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/items/Relation.java
  src/main/java/org/openstreetmap/atlas/geography/index/QuadTree.java
  src/main/java/org/openstreetmap/atlas/geography/index/RTree.java
  src/main/java/org/openstreetmap/atlas/utilities/filters/AtlasEntityPolygonsFilter.java
  src/main/java/org/openstreetmap/atlas/utilities/filters/IntersectionPolicy.java
  src/test/java/org/openstreetmap/atlas/geography/MultiPolygonTest.java
  src/test/java/org/openstreetmap/atlas/geography/PolygonTest.java
  src/test/java/org/openstreetmap/atlas/utilities/filters/AtlasEntityPolygonsFilterTest.java
Labels: Enhancement, New Feature

#106 Raw Atlas Enhancements
  src/integrationTest/java/org/openstreetmap/atlas/geography/atlas/raw/OsmPbfToSlicedRawAtlasTest.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/raw/creation/OsmPbfCounter.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/raw/creation/OsmPbfReader.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/raw/creation/RawAtlasGenerator.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/raw/slicing/RawAtlasCountrySlicer.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/raw/slicing/RawAtlasPointAndLineSlicer.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/raw/slicing/changeset/SimpleChangeSet.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/raw/slicing/changeset/SimpleChangeSetHandler.java
  src/test/java/org/openstreetmap/atlas/geography/atlas/raw/creation/RawAtlasGeneratorTest.java
Labels: Enhancement

#96 Fix for DynamicTileSharding OOM
  src/main/java/org/openstreetmap/atlas/geography/sharding/DynamicTileSharding.java
  src/test/java/org/openstreetmap/atlas/geography/sharding/DynamicTileShardingTest.java
Labels: Bug

#108 MultiPolygon empty method and empty Clipping test
  src/main/java/org/openstreetmap/atlas/geography/MultiPolygon.java
  src/test/java/org/openstreetmap/atlas/geography/MultiPolygonTest.java
  src/test/java/org/openstreetmap/atlas/geography/clipping/MultiPolygonClipperTest.java
Labels: Bug, Enhancement

#109 Added shaded jar classifier
  build.gradle
Labels: Enhancement

#110 AmenityTags Additions
  src/main/java/org/openstreetmap/atlas/tags/AmenityTag.java
Labels: Enhancement

#111 Make Country->Shard listing re-usable
  src/main/java/org/openstreetmap/atlas/geography/boundary/CountryBoundaryMapPrinter.java
  src/main/java/org/openstreetmap/atlas/geography/boundary/CountryShardListing.java
  src/main/java/org/openstreetmap/atlas/geography/boundary/CountryShardListingProcessor.java
  src/main/java/org/openstreetmap/atlas/geography/boundary/CountryToShardListing.java
  src/test/java/org/openstreetmap/atlas/geography/boundary/CountryShardListingTest.java
  src/test/java/org/openstreetmap/atlas/geography/boundary/CountryToShardListingTest.java
Labels: Enhancement

#112 Raw Atlas bug fixes and improvements
  src/integrationTest/java/org/openstreetmap/atlas/geography/atlas/raw/DynamicRawAtlasSectioningTestRule.java
  src/integrationTest/java/org/openstreetmap/atlas/geography/atlas/raw/RawAtlasIntegrationTest.java
  src/integrationTest/resources/org/openstreetmap/atlas/geography/atlas/raw/8-122-122-trimmed.osm.pbf
  src/integrationTest/resources/org/openstreetmap/atlas/geography/atlas/raw/8-122-122.osm.pbf
  src/main/java/org/openstreetmap/atlas/geography/atlas/raw/sectioning/WaySectionProcessor.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/raw/slicing/RawAtlasCountrySlicer.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/raw/slicing/RawAtlasPointAndLineSlicer.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/raw/slicing/RawAtlasRelationSlicer.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/raw/slicing/RawAtlasSlicer.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/raw/slicing/changeset/ChangeSetHandler.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/raw/slicing/changeset/RelationChangeSetHandler.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/raw/slicing/changeset/SimpleChangeSetHandler.java
  src/main/java/org/openstreetmap/atlas/geography/sharding/DynamicTileSharding.java
  src/test/java/org/openstreetmap/atlas/geography/atlas/raw/creation/RawAtlasGeneratorTest.java
  src/test/java/org/openstreetmap/atlas/geography/atlas/raw/sectioning/WaySectionProcessorTest.java
  src/test/java/org/openstreetmap/atlas/geography/atlas/raw/sectioning/WaySectionProcessorTestRule.java
  src/test/java/org/openstreetmap/atlas/geography/atlas/raw/slicing/InvalidMultipolygonSlicingTest.java
  src/test/java/org/openstreetmap/atlas/geography/atlas/raw/slicing/LineAndPointSlicingTest.java
  src/test/java/org/openstreetmap/atlas/geography/atlas/raw/slicing/RelationSlicingTest.java
  src/test/resources/org/openstreetmap/atlas/geography/atlas/raw/sectioning/lineWithLoopInMiddle.atlas.txt
Labels: Bug, Enhancement

#113 ManMadeTag enum typo
  src/main/java/org/openstreetmap/atlas/tags/ManMadeTag.java
Labels: Bug

#115 StringList Serialization
  src/main/java/org/openstreetmap/atlas/utilities/collections/StringList.java
Labels: Enhancement

#114 PackedAtlas: Do not load non serializable fields
  src/main/java/org/openstreetmap/atlas/geography/atlas/packed/PackedAtlasSerializer.java
  src/test/java/org/openstreetmap/atlas/geography/atlas/packed/PackedAtlasSerializerTest.java
Labels: Bug

#117 Make ConfiguredTaggableFilter serializable
  src/main/java/org/openstreetmap/atlas/tags/filters/ConfiguredTaggableFilter.java
Labels: Enhancement

#121 EntranceTag Enum
  src/main/java/org/openstreetmap/atlas/tags/EntranceTag.java
Labels: Enhancement

#119 Fix for edge case of LargeArray.trim() causing ArrayIndexOutOfBoundsException
  src/main/java/org/openstreetmap/atlas/utilities/arrays/LargeArray.java
  src/test/java/org/openstreetmap/atlas/utilities/arrays/LargeArrayTest.java
Labels: Bug
