Repository osmlab/atlas, pull requests merged in 2018-03, with the labels that each got.

#87 Discard restriction relation with more than 1 via node
  src/main/java/org/openstreetmap/atlas/geography/atlas/items/TurnRestriction.java
  src/test/java/org/openstreetmap/atlas/geography/atlas/items/complex/restriction/ComplexTurnRestrictionTest.java
  src/test/java/org/openstreetmap/atlas/geography/atlas/items/complex/restriction/ComplexTurnRestrictionTestCaseRule.java
Labels: Enhancement

#90 Improve CountryBoundaryMap dynamic grid index generation performance and fix serialization
  src/integrationTest/java/org/openstreetmap/atlas/geography/atlas/pbf/OsmPbfLoaderIntegrationTest.java
  src/integrationTest/java/org/openstreetmap/atlas/geography/atlas/raw/OsmPbfToSlicedRawAtlasTest.java
  src/integrationTest/java/org/openstreetmap/atlas/geography/boundary/CountryBoundaryMapIntegrationTest.java
  src/integrationTest/resources/org/openstreetmap/atlas/geography/atlas/raw/CIV_GIN_LBR_osm_boundaries.txt.gz
  src/integrationTest/resources/org/openstreetmap/atlas/geography/atlas/raw/CIV_GIN_LBR_osm_boundaries_with_grid_index.txt.gz
  src/main/java/org/openstreetmap/atlas/geography/atlas/converters/AtlasDebugTool.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/pbf/OsmPbfProcessor.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/raw/slicing/RawAtlasCountrySlicer.java
  src/main/java/org/openstreetmap/atlas/geography/boundary/AbstractGridIndexBuilder.java
  src/main/java/org/openstreetmap/atlas/geography/boundary/CountryBoundaryMap.java
  src/main/java/org/openstreetmap/atlas/geography/boundary/CountryBoundaryMapArchiver.java
  src/main/java/org/openstreetmap/atlas/geography/boundary/CountryBoundaryMapCompareCommand.java
  src/main/java/org/openstreetmap/atlas/geography/boundary/CountryBoundaryMapFiller.java
  src/main/java/org/openstreetmap/atlas/geography/boundary/CountryBoundaryMapPrinter.java
  src/main/java/org/openstreetmap/atlas/geography/boundary/CountryCodeGenerator.java
  src/main/java/org/openstreetmap/atlas/geography/boundary/CountryToShardListing.java
  src/main/java/org/openstreetmap/atlas/geography/boundary/DynamicGridIndexBuilder.java
  src/main/java/org/openstreetmap/atlas/geography/boundary/FixedGridIndexBuilder.java
  src/main/java/org/openstreetmap/atlas/geography/boundary/GridIndexParts.java
  src/test/java/org/openstreetmap/atlas/geography/atlas/pbf/OsmPbfLoaderTest.java
  src/test/java/org/openstreetmap/atlas/geography/atlas/pbf/slicing/CountrySlicingProcessorTest.java
  src/test/java/org/openstreetmap/atlas/geography/atlas/raw/sectioning/WaySectionProcessorTest.java
  src/test/java/org/openstreetmap/atlas/geography/atlas/raw/slicing/InvalidMultipolygonSlicingTest.java
  src/test/java/org/openstreetmap/atlas/geography/atlas/raw/slicing/LineAndPointSlicingTest.java
  src/test/java/org/openstreetmap/atlas/geography/atlas/raw/slicing/RelationSlicingTest.java
  src/test/java/org/openstreetmap/atlas/geography/boundary/CountryBoundaryMapTest.java
  src/test/java/org/openstreetmap/atlas/geography/boundary/CountryToShardListingTest.java
  src/test/java/org/openstreetmap/atlas/geography/boundary/DynamicGridIndexBuilderTest.java
  src/test/java/org/openstreetmap/atlas/geography/boundary/GridIndexBuilderTest.java
  src/test/resources/org/openstreetmap/atlas/geography/atlas/raw/slicing/CIV_GIN_LBR_osm_boundaries.txt.gz
  src/test/resources/org/openstreetmap/atlas/geography/atlas/raw/slicing/CIV_GIN_LBR_osm_boundaries_with_grid_index.txt.gz
  src/test/resources/org/openstreetmap/atlas/geography/boundary/AIA_MAF_osm_boundaries_with_grid_index.txt.gz
  src/test/resources/org/openstreetmap/atlas/geography/boundary/MAF_AIA_osm_boundaries_with_grid_index.txt.gz
Labels: Bug, Enhancement

#91 Returning empty Iterable in case of invalid or two-point PolyLine truncate method
  src/main/java/org/openstreetmap/atlas/geography/PolyLine.java
  src/test/java/org/openstreetmap/atlas/geography/PolyLineTest.java
Labels: Bug

#92 Fix hasGridIndex behavior
  src/main/java/org/openstreetmap/atlas/geography/boundary/CountryBoundaryMap.java
  src/test/java/org/openstreetmap/atlas/geography/boundary/CountryBoundaryMapTest.java
Labels: Bug

#89 Atlas Entity Polygon Filter
  src/main/java/org/openstreetmap/atlas/geography/MultiPolygon.java
  src/main/java/org/openstreetmap/atlas/geography/converters/PolygonStringFormat.java
  src/main/java/org/openstreetmap/atlas/geography/converters/WkbMultiPolygonConverter.java
  src/main/java/org/openstreetmap/atlas/geography/geojson/GeoJsonBuilder.java
  src/main/java/org/openstreetmap/atlas/utilities/filters/AtlasEntityPolygonsFilter.java
  src/main/java/org/openstreetmap/atlas/utilities/filters/IntersectionPolicy.java
  src/test/java/org/openstreetmap/atlas/geography/MultiPolygonTest.java
  src/test/java/org/openstreetmap/atlas/geography/converters/WkbMultiPolygonConverterTest.java
  src/test/java/org/openstreetmap/atlas/utilities/filters/AtlasEntityPolygonsFilterTest.java
  src/test/java/org/openstreetmap/atlas/utilities/filters/AtlasEntityPolygonsFilterTestRule.java
  src/test/resources/org/openstreetmap/atlas/utilities/filters/includeExcludePolygonArrangements.osm
  src/test/resources/org/openstreetmap/atlas/utilities/filters/multiPolygons.osm
  src/test/resources/org/openstreetmap/atlas/utilities/filters/overlappingPolygons.osm
  src/test/resources/org/openstreetmap/atlas/utilities/filters/testCounts.osm
  src/test/resources/org/openstreetmap/atlas/utilities/filters/testForms.osm
Labels: New Feature

#93 Cross Shard Raw Atlas Sectioning
  src/integrationTest/java/org/openstreetmap/atlas/geography/atlas/raw/DynamicRawAtlasSectioningTestRule.java
  src/integrationTest/java/org/openstreetmap/atlas/geography/atlas/raw/OsmPbfToSlicedRawAtlasTest.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/raw/sectioning/WaySectionProcessor.java
  src/main/java/org/openstreetmap/atlas/geography/sharding/SlippyTile.java
  src/test/java/org/openstreetmap/atlas/geography/sharding/SlippyTileTest.java
Labels: Enhancement, New Feature

#94 Verify generated grid index for countries
  src/main/java/org/openstreetmap/atlas/geography/boundary/CountryBoundaryMap.java
  src/test/java/org/openstreetmap/atlas/geography/boundary/CountryBoundaryMapTest.java
  src/test/resources/org/openstreetmap/atlas/geography/boundary/duplicate_shape.dbf
  src/test/resources/org/openstreetmap/atlas/geography/boundary/duplicate_shape.prj
  src/test/resources/org/openstreetmap/atlas/geography/boundary/duplicate_shape.qpj
  src/test/resources/org/openstreetmap/atlas/geography/boundary/duplicate_shape.shp
  src/test/resources/org/openstreetmap/atlas/geography/boundary/duplicate_shape.shx
Labels: Enhancement

#95 Return results if there is a full overlap in slicing process
  src/main/java/org/openstreetmap/atlas/geography/boundary/CountryBoundaryMap.java
  src/test/java/org/openstreetmap/atlas/geography/atlas/pbf/OsmPbfLoaderTest.java
Labels: Enhancement

#98 Fix NPE in CountryBoundaryMap when country code is missing
  src/main/java/org/openstreetmap/atlas/geography/boundary/CountryBoundaryMap.java
  src/test/java/org/openstreetmap/atlas/geography/boundary/CountryBoundaryMapTest.java
Labels: Bug

#97 Fix for SQL file generation OOM
  src/main/java/org/openstreetmap/atlas/geography/sharding/SlippyTile.java
  src/main/java/org/openstreetmap/atlas/geography/sharding/preparation/TilePrinter.java
Labels: Bug

#99 Save Atlas to ProtobufAtlas similar to TextAtlas
  .gitignore
  README.md
  build.gradle
  config/checkstyle/suppressions.xml
  dependencies.gradle
  src/main/java/org/openstreetmap/atlas/geography/atlas/Atlas.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/BareAtlas.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/builder/proto/ProtoAtlasBuilder.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/command/PackedToProtoAtlasSubCommand.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/command/ProtoToPackedAtlasSubCommand.java
  src/main/java/org/openstreetmap/atlas/geography/converters/proto/ProtoLocationConverter.java
  src/main/java/org/openstreetmap/atlas/geography/converters/proto/ProtoTagListConverter.java
  src/main/java/org/openstreetmap/atlas/streaming/resource/FileSuffix.java
  src/main/proto/Area.proto
  src/main/proto/AtlasContainer.proto
  src/main/proto/Edge.proto
  src/main/proto/Line.proto
  src/main/proto/Location.proto
  src/main/proto/Node.proto
  src/main/proto/Point.proto
  src/main/proto/Relation.proto
  src/main/proto/Tag.proto
  src/test/java/org/openstreetmap/atlas/geography/atlas/builder/proto/ProtoAtlasBuilderTest.java
  src/test/java/org/openstreetmap/atlas/geography/converters/proto/ProtoLocationConverterTest.java
  src/test/java/org/openstreetmap/atlas/geography/converters/proto/ProtoTagListConverterTest.java
Labels: New Feature

#103 Ingest OSM Nodes with no tags, not a relation member or part of an OSM Way
  src/integrationTest/java/org/openstreetmap/atlas/geography/atlas/raw/OsmPbfToSlicedRawAtlasTest.java
  src/integrationTest/resources/org/openstreetmap/atlas/geography/atlas/raw/node-4353689487.pbf
  src/main/java/org/openstreetmap/atlas/geography/atlas/raw/creation/OsmPbfReader.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/raw/creation/RawAtlasGenerator.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/raw/sectioning/WaySectionProcessor.java
  src/test/java/org/openstreetmap/atlas/geography/boundary/CountryBoundaryMapTest.java
Labels: Enhancement
