Repository osmlab/atlas, pull requests merged in 2018-11, with the labels that each got.

#268 Fixed careless comment copy paste from previous PR
  src/main/java/org/openstreetmap/atlas/utilities/caching/ConcurrentResourceCache.java
Labels: Fail

#270 Remove legacy PBF Ingest Flow
  src/integrationTest/java/org/openstreetmap/atlas/geography/atlas/AtlasIntegrationTest.java
  src/integrationTest/java/org/openstreetmap/atlas/geography/atlas/multi/MultiAtlasIntegrationTest.java
  src/integrationTest/java/org/openstreetmap/atlas/geography/atlas/packed/PackedAtlasIntegrationTest.java
  src/integrationTest/java/org/openstreetmap/atlas/geography/atlas/pbf/OsmPbfIngestIntegrationTest.java
  src/integrationTest/java/org/openstreetmap/atlas/geography/atlas/pbf/slicing/WaySectionProcessorIntegrationTest.java
  src/integrationTest/java/org/openstreetmap/atlas/geography/atlas/raw/RawAtlasIntegrationTest.java
  src/integrationTest/resources/org/openstreetmap/atlas/geography/atlas/pbf/BHS-6-18-27.pbf
  src/integrationTest/resources/org/openstreetmap/atlas/geography/atlas/pbf/BHS_07082015.pbf
  src/main/java/org/openstreetmap/atlas/geography/atlas/AbstractAtlas.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/converters/AtlasDebugTool.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/pbf/AtlasLoadingOption.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/pbf/OsmPbfLoader.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/pbf/OsmPbfProcessor.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/pbf/OsmPbfStatistic.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/pbf/slicing/ChangeSet.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/pbf/slicing/CountrySlicingProcessor.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/pbf/slicing/README.md
  src/main/java/org/openstreetmap/atlas/geography/atlas/pbf/slicing/RelationType.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/pbf/slicing/WaySectionProcessor.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/pbf/store/PbfMemoryStore.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/pbf/store/SectionCounter.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/raw/creation/OsmPbfCounter.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/raw/creation/OsmPbfReader.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/raw/creation/RawAtlasGenerator.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/raw/sectioning/PbfOneWay.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/raw/sectioning/TagMap.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/raw/sectioning/WaySectionProcessor.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/raw/slicing/RuntimeCounter.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/raw/slicing/changeset/SimpleChangeSet.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/raw/slicing/changeset/SimpleChangeSetHandler.java
  src/main/java/org/openstreetmap/atlas/geography/boundary/CountryBoundaryMap.java
  src/main/java/org/openstreetmap/atlas/utilities/testing/TestAtlasHandler.java
  src/test/java/org/openstreetmap/atlas/geography/atlas/dynamic/DynamicAtlasTest.java
  src/test/java/org/openstreetmap/atlas/geography/atlas/pbf/OsmPbfIngestTest.java
  src/test/java/org/openstreetmap/atlas/geography/atlas/pbf/OsmPbfProcessorTest.java
  src/test/java/org/openstreetmap/atlas/geography/atlas/pbf/slicing/CountrySlicingProcessorTest.java
  src/test/java/org/openstreetmap/atlas/geography/atlas/pbf/slicing/WaySectionProcessorTest.java
  src/test/java/org/openstreetmap/atlas/geography/atlas/pbf/store/PbfOneWayTest.java
  src/test/java/org/openstreetmap/atlas/geography/atlas/raw/creation/RawAtlasGeneratorTest.java
  src/test/java/org/openstreetmap/atlas/geography/atlas/statistics/AtlasStatisticsTest.java
Labels: Breaking Change, Enhancement

#269 Tippecanoe & Line Delimited GeoJSON
  build.gradle
  dependencies.gradle
  src/main/java/org/openstreetmap/atlas/geography/GeometricSurface.java
  src/main/java/org/openstreetmap/atlas/geography/Location.java
  src/main/java/org/openstreetmap/atlas/geography/MultiPolygon.java
  src/main/java/org/openstreetmap/atlas/geography/PolyLine.java
  src/main/java/org/openstreetmap/atlas/geography/Polygon.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/Atlas.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/BareAtlas.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/geojson/LineDelimitedGeoJsonConverter.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/items/Area.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/items/AtlasEntity.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/items/Edge.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/items/LineItem.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/items/LocationItem.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/items/Node.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/items/Relation.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/packed/PackedAtlas.java
  src/main/java/org/openstreetmap/atlas/geography/geojson/GeoJsonBuilder.java
  src/main/java/org/openstreetmap/atlas/geography/geojson/GeoJsonUtils.java
  src/main/java/org/openstreetmap/atlas/streaming/writers/JsonWriter.java
  src/main/java/org/openstreetmap/atlas/utilities/runtime/RunScript.java
  src/main/java/org/openstreetmap/atlas/utilities/vectortiles/MinimumZoom.java
  src/main/java/org/openstreetmap/atlas/utilities/vectortiles/README.md
  src/main/java/org/openstreetmap/atlas/utilities/vectortiles/TippecanoeExporter.java
  src/main/java/org/openstreetmap/atlas/utilities/vectortiles/TippecanoeGeoJsonExtension.java
  src/main/java/org/openstreetmap/atlas/utilities/vectortiles/TippecanoeSettings.java
  src/main/resources/org/openstreetmap/atlas/utilities/vectortiles/minimum-zooms.json
  src/test/java/org/openstreetmap/atlas/geography/MultiPolygonTest.java
  src/test/java/org/openstreetmap/atlas/geography/PolyLineTest.java
  src/test/java/org/openstreetmap/atlas/geography/PolygonTest.java
  src/test/java/org/openstreetmap/atlas/geography/atlas/BareAtlasTest.java
  src/test/java/org/openstreetmap/atlas/geography/geojson/GeoJsonUtilsTest.java
  src/test/java/org/openstreetmap/atlas/utilities/runtime/RunScriptTest.java
  src/test/java/org/openstreetmap/atlas/utilities/vectortiles/MinimumZoomTest.java
  src/test/resources/org/openstreetmap/atlas/geography/atlas/line-delimited-geojson.txt
Labels: Enhancement, New Feature

#272 Fixed inconsistent geometry
  src/main/java/org/openstreetmap/atlas/geography/atlas/raw/slicing/CoordinateToNewPointMapping.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/raw/slicing/RawAtlasCountrySlicer.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/raw/slicing/RawAtlasPointAndLineSlicer.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/raw/slicing/RawAtlasRelationSlicer.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/raw/slicing/RawAtlasSlicer.java
  src/test/java/org/openstreetmap/atlas/geography/atlas/raw/slicing/RelationSlicingTest.java
Labels: Bug, Enhancement

#273 [Change] Skeleton for Atlas Change feature
  src/main/java/org/openstreetmap/atlas/geography/atlas/bloated/BloatedArea.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/bloated/BloatedAtlas.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/bloated/BloatedEdge.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/bloated/BloatedLine.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/bloated/BloatedNode.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/bloated/BloatedPoint.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/bloated/BloatedRelation.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/builder/RelationBean.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/change/Change.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/change/ChangeArea.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/change/ChangeAtlas.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/change/ChangeBuilder.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/change/ChangeEdge.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/change/ChangeEntity.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/change/ChangeLine.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/change/ChangeNode.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/change/ChangePoint.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/change/ChangeRelation.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/change/rule/ChangeType.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/change/rule/FeatureChange.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/change/validators/ChangeAtlasEdgeValidator.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/change/validators/ChangeAtlasLineItemValidator.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/change/validators/ChangeAtlasLocationItemValidator.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/change/validators/ChangeAtlasNodeValidator.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/change/validators/ChangeAtlasValidator.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/change/validators/ChangeValidator.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/items/RelationMember.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/items/RelationMemberList.java
  src/main/java/org/openstreetmap/atlas/utilities/collections/Sets.java
  src/test/java/org/openstreetmap/atlas/geography/atlas/bloated/BloatedAreaTest.java
  src/test/java/org/openstreetmap/atlas/geography/atlas/bloated/BloatedAtlasTest.java
  src/test/java/org/openstreetmap/atlas/geography/atlas/bloated/BloatedEdgeTest.java
  src/test/java/org/openstreetmap/atlas/geography/atlas/bloated/BloatedLineTest.java
  src/test/java/org/openstreetmap/atlas/geography/atlas/bloated/BloatedNodeTest.java
  src/test/java/org/openstreetmap/atlas/geography/atlas/bloated/BloatedPointTest.java
  src/test/java/org/openstreetmap/atlas/geography/atlas/bloated/BloatedRelationTest.java
  src/test/java/org/openstreetmap/atlas/geography/atlas/bloated/BloatedTestRule.java
  src/test/java/org/openstreetmap/atlas/geography/atlas/change/validators/ChangeAtlasEdgeValidatorTest.java
  src/test/java/org/openstreetmap/atlas/geography/atlas/change/validators/ChangeAtlasEdgeValidatorTestRule.java
  src/test/resources/org/openstreetmap/atlas/geography/atlas/change/validators/ChangeAtlasEdgeValidatorTest.josm.osm
Labels: Duplicate

#275 Tippecanoe Line Delimited GeoJSON Tweaks for atlas-checks
  src/main/java/org/openstreetmap/atlas/geography/atlas/geojson/LineDelimitedGeoJsonConverter.java
  src/main/java/org/openstreetmap/atlas/utilities/vectortiles/TippecanoeCommands.java
  src/main/java/org/openstreetmap/atlas/utilities/vectortiles/TippecanoeExporter.java
  src/main/java/org/openstreetmap/atlas/utilities/vectortiles/TippecanoeGeoJsonExtension.java
  src/main/java/org/openstreetmap/atlas/utilities/vectortiles/TippecanoeSettings.java
Labels: Enhancement

#277 Simple Edge Walker
  src/main/java/org/openstreetmap/atlas/geography/atlas/walker/SimpleEdgeWalker.java
  src/test/java/org/openstreetmap/atlas/geography/atlas/walker/SimpleEdgeWalkerTest.java
  src/test/java/org/openstreetmap/atlas/geography/atlas/walker/SimpleEdgeWalkerTestRule.java
Labels: New Feature

#280 [Change] Finished implementing methods for ChangeAtlas
  src/main/java/org/openstreetmap/atlas/geography/PolyLine.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/AtlasMetaData.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/change/ChangeAtlas.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/change/ChangeRelation.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/change/validators/ChangeAtlasEdgeValidator.java
  src/main/java/org/openstreetmap/atlas/utilities/collections/Iterables.java
  src/main/java/org/openstreetmap/atlas/utilities/collections/StreamIterable.java
  src/test/java/org/openstreetmap/atlas/geography/atlas/change/ChangeAtlasTest.java
  src/test/java/org/openstreetmap/atlas/geography/atlas/change/ChangeAtlasTestRule.java
  src/test/java/org/openstreetmap/atlas/utilities/collections/IterablesTest.java
  src/test/resources/org/openstreetmap/atlas/geography/atlas/change/ChangeAtlasTest.josm.osm
Labels: Duplicate

#284 [Change] More ChangeAtlas updates
  src/main/java/org/openstreetmap/atlas/geography/atlas/bloated/BloatedArea.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/bloated/BloatedAtlas.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/bloated/BloatedEdge.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/bloated/BloatedLine.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/bloated/BloatedNode.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/bloated/BloatedPoint.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/bloated/BloatedRelation.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/change/ChangeAtlas.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/change/ChangeNode.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/change/rule/FeatureChange.java
  src/test/java/org/openstreetmap/atlas/geography/atlas/change/ChangeAtlasTest.java
  src/test/java/org/openstreetmap/atlas/geography/atlas/change/validators/ChangeAtlasEdgeValidatorTest.java
Labels: Duplicate

#285 [Change] Fixed failing unit tests
  src/test/java/org/openstreetmap/atlas/geography/atlas/bloated/BloatedAreaTest.java
  src/test/java/org/openstreetmap/atlas/geography/atlas/bloated/BloatedNodeTest.java
  src/test/java/org/openstreetmap/atlas/geography/atlas/bloated/BloatedPointTest.java
Labels: Duplicate

#286 [Change] Add validation and related testing to FeatureChange and Change
  src/main/java/org/openstreetmap/atlas/geography/atlas/bloated/BloatedArea.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/bloated/BloatedAtlas.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/bloated/BloatedEdge.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/bloated/BloatedEntity.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/bloated/BloatedLine.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/bloated/BloatedNode.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/bloated/BloatedPoint.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/bloated/BloatedRelation.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/change/Change.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/change/ChangeBuilder.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/change/rule/FeatureChange.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/change/validators/ChangeValidator.java
  src/test/java/org/openstreetmap/atlas/geography/atlas/change/ChangeTest.java
  src/test/java/org/openstreetmap/atlas/geography/atlas/change/rules/FeatureChangeTest.java
  src/test/java/org/openstreetmap/atlas/geography/atlas/change/validators/ChangeAtlasEdgeValidatorTest.java
  src/test/java/org/openstreetmap/atlas/geography/atlas/change/validators/ChangeValidatorTest.java
Labels: Duplicate

#276 SubAtlas cut type functionality
  src/main/java/org/openstreetmap/atlas/geography/Rectangle.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/AbstractAtlas.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/Atlas.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/AtlasResourceLoader.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/BareAtlas.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/dynamic/DynamicAtlas.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/items/Relation.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/raw/sectioning/WaySectionProcessor.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/sub/AtlasCutType.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/sub/SubAtlas.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/sub/SubAtlasCreator.java
  src/test/java/org/openstreetmap/atlas/geography/RectangleTest.java
  src/test/java/org/openstreetmap/atlas/geography/atlas/SubAtlasRule.java
  src/test/java/org/openstreetmap/atlas/geography/atlas/SubAtlasTest.java
  src/test/java/org/openstreetmap/atlas/geography/atlas/items/AtlasItemIntersectionTest.java
  src/test/java/org/openstreetmap/atlas/geography/atlas/items/AtlasItemIntersectionTestRule.java
Labels: Bug, Enhancement, New Feature

#287 [Change] Lots of filtering implemented
  src/main/java/org/openstreetmap/atlas/geography/atlas/change/ChangeAtlas.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/change/ChangeEntity.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/change/ChangeNode.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/change/ChangeRelation.java
  src/test/java/org/openstreetmap/atlas/geography/atlas/change/ChangeAtlasTest.java
  src/test/resources/org/openstreetmap/atlas/geography/atlas/change/ChangeAtlasTest.josm.osm
Labels: Duplicate

#289 [Change] Simple refactor and Javadoc
  src/main/java/org/openstreetmap/atlas/geography/atlas/bloated/BloatedArea.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/bloated/BloatedAtlas.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/bloated/BloatedEntity.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/bloated/BloatedLine.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/bloated/BloatedPoint.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/bloated/BloatedRelation.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/change/Change.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/change/ChangeArea.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/change/ChangeAtlas.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/change/ChangeBuilder.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/change/ChangeEdge.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/change/ChangeLine.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/change/ChangeNode.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/change/ChangePoint.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/change/ChangeRelation.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/change/ChangeType.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/change/FeatureChange.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/change/validators/ChangeValidator.java
  src/test/java/org/openstreetmap/atlas/geography/atlas/change/ChangeAtlasTest.java
  src/test/java/org/openstreetmap/atlas/geography/atlas/change/ChangeTest.java
  src/test/java/org/openstreetmap/atlas/geography/atlas/change/FeatureChangeTest.java
  src/test/java/org/openstreetmap/atlas/geography/atlas/change/validators/ChangeValidatorTest.java
Labels: Duplicate

#290 [Change] More complex unit tests
  src/main/java/org/openstreetmap/atlas/geography/atlas/AbstractAtlas.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/Atlas.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/bloated/BloatedArea.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/bloated/BloatedEdge.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/bloated/BloatedEntity.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/bloated/BloatedLine.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/bloated/BloatedNode.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/bloated/BloatedPoint.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/bloated/BloatedRelation.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/change/AtlasChangeGenerator.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/change/FeatureChange.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/change/validators/ChangeValidator.java
  src/test/java/org/openstreetmap/atlas/geography/atlas/bloated/BloatedAreaTest.java
  src/test/java/org/openstreetmap/atlas/geography/atlas/bloated/BloatedEdgeTest.java
  src/test/java/org/openstreetmap/atlas/geography/atlas/bloated/BloatedLineTest.java
  src/test/java/org/openstreetmap/atlas/geography/atlas/bloated/BloatedNodeTest.java
  src/test/java/org/openstreetmap/atlas/geography/atlas/bloated/BloatedPointTest.java
  src/test/java/org/openstreetmap/atlas/geography/atlas/bloated/BloatedRelationTest.java
  src/test/java/org/openstreetmap/atlas/geography/atlas/change/AtlasChangeGeneratorRemoveReverseEdges.java
  src/test/java/org/openstreetmap/atlas/geography/atlas/change/AtlasChangeGeneratorSplitRoundabout.java
  src/test/java/org/openstreetmap/atlas/geography/atlas/change/ChangeAtlasTest.java
  src/test/java/org/openstreetmap/atlas/geography/atlas/change/MultipleChangeAtlasTest.java
  src/test/java/org/openstreetmap/atlas/geography/atlas/change/MultipleChangeAtlasTestRule.java
  src/test/resources/org/openstreetmap/atlas/geography/atlas/change/MultipleChangeAtlasTest.atlas.txt
  src/test/resources/org/openstreetmap/atlas/geography/atlas/change/MultipleChangeAtlasTest.osm
Labels: Duplicate

#291 [Change] Ability to merge FeatureChange objects
  src/main/java/org/openstreetmap/atlas/geography/atlas/builder/RelationBean.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/change/Change.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/change/FeatureChange.java
  src/main/java/org/openstreetmap/atlas/utilities/collections/Maps.java
  src/main/java/org/openstreetmap/atlas/utilities/collections/Sets.java
  src/test/java/org/openstreetmap/atlas/geography/atlas/change/ChangeTest.java
  src/test/java/org/openstreetmap/atlas/geography/atlas/change/FeatureChangeTest.java
  src/test/java/org/openstreetmap/atlas/utilities/collections/MapsTest.java
  src/test/java/org/openstreetmap/atlas/utilities/collections/SetsTest.java
Labels: Duplicate
