Repository osmlab/atlas, pull requests merged in 2018-09, with the labels that each got.

#212 Fix single nested relations issue in RawAtlasGenerator
  src/main/java/org/openstreetmap/atlas/geography/atlas/raw/creation/RawAtlasGenerator.java
  src/test/java/org/openstreetmap/atlas/geography/atlas/raw/creation/RawAtlasGeneratorTest.java
  src/test/resources/org/openstreetmap/atlas/geography/atlas/raw/creation/nestedSingleRelations.josm.osm
  src/test/resources/org/openstreetmap/atlas/geography/atlas/raw/creation/nestedSingleRelations.osm
  src/test/resources/org/openstreetmap/atlas/geography/atlas/raw/creation/nestedSingleRelations.osm.pbf
Labels: Bug

#213 Double precision in Distance
  src/main/java/org/openstreetmap/atlas/geography/atlas/packed/PackedAtlas.java
  src/main/java/org/openstreetmap/atlas/utilities/scalars/Distance.java
  src/test/java/org/openstreetmap/atlas/utilities/scalars/DistanceTest.java
  src/test/java/org/openstreetmap/atlas/utilities/scalars/SpeedTest.java
Labels: Enhancement

#215 Fixed a resource leak in PackedAtlasSerializer
  src/main/java/org/openstreetmap/atlas/geography/atlas/packed/PackedAtlasSerializer.java
  src/test/java/org/openstreetmap/atlas/geography/atlas/AtlasResourceLoaderTest.java
  src/test/java/org/openstreetmap/atlas/geography/atlas/packed/PackedAtlasSerializerTest.java
Labels: Bug

#216 Fixed a bug in DynamicRelation.members() that broke BareAtlas.relationsLowerOrderFirst()
  src/integrationTest/java/org/openstreetmap/atlas/geography/atlas/raw/RawAtlasIntegrationTest.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/dynamic/DynamicRelation.java
  src/test/java/org/openstreetmap/atlas/geography/atlas/dynamic/DynamicAtlasTest.java
  src/test/java/org/openstreetmap/atlas/geography/atlas/dynamic/rules/DynamicAtlasTestRule.java
Labels: Bug

#217 Addressed some PR comments
  src/test/java/org/openstreetmap/atlas/geography/atlas/packed/PackedAtlasSerializerTest.java
Labels: Enhancement

#209 Find By Atlas Identifier Sub Command
  src/main/java/org/openstreetmap/atlas/geography/atlas/command/AtlasFindByAtlasIdentifierSubCommand.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/command/AtlasJoinerSubCommand.java
  src/test/java/org/openstreetmap/atlas/geography/atlas/command/AtlasFindByAtlasIdentifierSubCommandTest.java
  src/test/java/org/openstreetmap/atlas/geography/atlas/command/AtlasJoinerSubCommandTest.java
  src/test/java/org/openstreetmap/atlas/geography/atlas/command/CaptureOutputStream.java
  src/test/resources/org/openstreetmap/atlas/geography/atlas/command/DNK_Copenhagen/DNK_1.atlas
  src/test/resources/org/openstreetmap/atlas/geography/atlas/command/DNK_Copenhagen/DNK_1.txt
  src/test/resources/org/openstreetmap/atlas/geography/atlas/command/DNK_Copenhagen/DNK_2.atlas
  src/test/resources/org/openstreetmap/atlas/geography/atlas/command/DNK_Copenhagen/DNK_2.txt
  src/test/resources/org/openstreetmap/atlas/geography/atlas/command/DNK_Copenhagen/DNK_3.atlas
  src/test/resources/org/openstreetmap/atlas/geography/atlas/command/DNK_Copenhagen/DNK_3.txt
Labels: Enhancement

#218 Fixed a small typo in the trigger-release script
  .travis/trigger-release.sh
Labels: Bug

#221 Improved DynamicAtlas documentation
  src/main/java/org/openstreetmap/atlas/geography/atlas/dynamic/README.md
Labels: Documentation

#222 Remove Binary Atlases
  src/test/resources/org/openstreetmap/atlas/geography/atlas/command/DNK_Copenhagen/DNK_1.atlas
  src/test/resources/org/openstreetmap/atlas/geography/atlas/command/DNK_Copenhagen/DNK_2.atlas
  src/test/resources/org/openstreetmap/atlas/geography/atlas/command/DNK_Copenhagen/DNK_3.atlas
Labels: Enhancement

#220 Fixing edge connectivity for OSM ways with differing layer tag values
  src/integrationTest/java/org/openstreetmap/atlas/geography/atlas/raw/RawAtlasIntegrationTest.java
  src/integrationTest/resources/org/openstreetmap/atlas/geography/atlas/raw/layerIntersectionAtEndBoundaryMap.txt
  src/integrationTest/resources/org/openstreetmap/atlas/geography/atlas/raw/layerIntersectionAtStartBoundaryMap.txt
  src/integrationTest/resources/org/openstreetmap/atlas/geography/atlas/raw/layerIntersectionInMiddleBoundaryMap.txt
  src/integrationTest/resources/org/openstreetmap/atlas/geography/atlas/raw/twoWaysWithDifferentLayersIntersectingAtEnd.pbf
  src/integrationTest/resources/org/openstreetmap/atlas/geography/atlas/raw/twoWaysWithDifferentLayersIntersectingAtStart.pbf
  src/integrationTest/resources/org/openstreetmap/atlas/geography/atlas/raw/twoWaysWithDifferentLayersIntersectingInMiddle.pbf
  src/main/java/org/openstreetmap/atlas/geography/atlas/raw/sectioning/WaySectionProcessor.java
Labels: Bug, Enhancement

#224 Adding check in closedLoop method to ensure no duplicate locations.
  src/main/java/org/openstreetmap/atlas/geography/Polygon.java
  src/test/java/org/openstreetmap/atlas/geography/PolygonTest.java
Labels: Enhancement

#227 Fixed relation return types in DynamicRelation.allKnownOsmMembers()
  src/main/java/org/openstreetmap/atlas/geography/atlas/dynamic/DynamicRelation.java
  src/test/java/org/openstreetmap/atlas/geography/atlas/dynamic/DynamicAtlasTest.java
Labels: Bug

#225 File extension is now preserved by the temp file caching strategy
  src/main/java/org/openstreetmap/atlas/utilities/caching/strategies/SystemTemporaryFileCachingStrategy.java
  src/test/java/org/openstreetmap/atlas/utilities/caching/CachingTests.java
  src/test/resources/org/openstreetmap/atlas/utilities/caching/feature.json
  src/test/resources/org/openstreetmap/atlas/utilities/caching/fileNoExt
Labels: Enhancement
