Repository osmlab/atlas, pull requests merged in 2018-06, with the labels that each got.

#136 Allow force-country-slicing based on a predicate
  src/main/java/org/openstreetmap/atlas/geography/atlas/pbf/slicing/CountrySlicingProcessor.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/raw/slicing/RawAtlasPointAndLineSlicer.java
  src/main/java/org/openstreetmap/atlas/geography/boundary/CountryBoundaryMap.java
  src/test/java/org/openstreetmap/atlas/geography/atlas/pbf/slicing/CountrySlicingProcessorTest.java
  src/test/java/org/openstreetmap/atlas/geography/boundary/CountryBoundaryMapTest.java
  src/test/resources/org/openstreetmap/atlas/geography/atlas/pbf/slicing/testForceSlicingBoundaryMap.txt
Labels: Data Change, New Feature

#141 Fixed bug in areasCovering that overincluded results.
  src/main/java/org/openstreetmap/atlas/geography/Location.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/AbstractAtlas.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/items/RelationMember.java
  src/test/java/org/openstreetmap/atlas/geography/atlas/packed/PackedAtlasSerializerTest.java
  src/test/java/org/openstreetmap/atlas/geography/atlas/packed/PackedAtlasTest.java
Labels: Bug

#143 Fix for travis release.
  .travis/deploy.sh
  .travis/install.sh
  gradle.properties
Labels: Bug

#144 Second round of travis fixes
  .travis.yml
  gradle.properties
  pyatlas/package.sh
  pyatlas/setup.py
Labels: Bug

#142 Aerialway & Building Tag Updates
  src/main/java/org/openstreetmap/atlas/tags/AerialWayTag.java
  src/main/java/org/openstreetmap/atlas/tags/BuildingTag.java
Labels: Enhancement

#138 Raw Atlas Bug Fixes
  src/integrationTest/java/org/openstreetmap/atlas/geography/atlas/raw/RawAtlasIntegrationTest.java
  src/integrationTest/resources/org/openstreetmap/atlas/geography/atlas/raw/layerTagTestCase.pbf
  src/integrationTest/resources/org/openstreetmap/atlas/geography/atlas/raw/testNodesWithDifferentLayerTagsBoundaryMap.txt
  src/main/java/org/openstreetmap/atlas/geography/atlas/raw/creation/RawAtlasGenerator.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/raw/sectioning/WaySectionProcessor.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/raw/slicing/changeset/ChangeSetHandler.java
  src/main/java/org/openstreetmap/atlas/tags/LayerTag.java
  src/test/java/org/openstreetmap/atlas/geography/atlas/raw/creation/RawAtlasGeneratorTest.java
Labels: Bug

#146 [PyAtlas] Made printouts for geometric objects WKT compatible
  pyatlas/pyatlas/geometry.py
Labels: Enhancement

#151 Handle null subatlas returned after filtering single resource in load()
  src/main/java/org/openstreetmap/atlas/geography/atlas/AtlasResourceLoader.java
  src/test/java/org/openstreetmap/atlas/geography/atlas/AtlasResourceLoaderTest.java
  src/test/resources/org/openstreetmap/atlas/geography/atlas/ECU_6-16-31.atlas
Labels: Bug

#148 Atlas documentation breakdown and refactor
  CONTRIBUTING.md
  README.md
  src/main/java/org/openstreetmap/atlas/geography/atlas/README.md
  src/main/java/org/openstreetmap/atlas/geography/atlas/dynamic/README.md
  src/main/java/org/openstreetmap/atlas/geography/atlas/items/complex/README.md
  src/main/java/org/openstreetmap/atlas/geography/atlas/multi/README.md
  src/main/java/org/openstreetmap/atlas/geography/atlas/packed/README.md
  src/main/java/org/openstreetmap/atlas/geography/atlas/routing/README.md
  src/main/java/org/openstreetmap/atlas/geography/sharding/README.md
Labels: Documentation

#152 Added a method to get a StandardConfiguration data keyset.
  src/main/java/org/openstreetmap/atlas/utilities/configuration/Configuration.java
  src/main/java/org/openstreetmap/atlas/utilities/configuration/MergedConfiguration.java
  src/main/java/org/openstreetmap/atlas/utilities/configuration/StandardConfiguration.java
  src/test/java/org/openstreetmap/atlas/utilities/configuration/MergedConfigurationTest.java
  src/test/java/org/openstreetmap/atlas/utilities/configuration/StandardConfigurationTest.java
Labels: Enhancement

#153 PbfOneWay should not decide what is closed
  src/main/java/org/openstreetmap/atlas/geography/atlas/pbf/store/PbfOneWay.java
  src/test/java/org/openstreetmap/atlas/geography/atlas/pbf/OsmPbfLoaderTest.java
  src/test/java/org/openstreetmap/atlas/geography/atlas/pbf/store/PbfOneWayTest.java
  src/test/resources/org/openstreetmap/atlas/geography/atlas/pbf/AIA_boundary.txt
  src/test/resources/org/openstreetmap/atlas/geography/atlas/pbf/edge-filter.json
  src/test/resources/org/openstreetmap/atlas/geography/atlas/pbf/one_way_roads_in_AIA.osm
Labels: Bug, Data Change

#154 Lowering serialization logging level
  src/main/java/org/openstreetmap/atlas/geography/atlas/packed/PackedAtlasSerializer.java
Labels: Enhancement
