Repository osmlab/atlas, pull requests merged in 2018-08, with the labels that each got.

#186 Fixing Turn Restriction NP
  src/main/java/org/openstreetmap/atlas/geography/atlas/items/TurnRestriction.java
Labels: Bug

#179 Longitude Compare at +180 degrees
  src/main/java/org/openstreetmap/atlas/utilities/scalars/Angle.java
  src/test/java/org/openstreetmap/atlas/geography/LongitudeTest.java
  src/test/java/org/openstreetmap/atlas/geography/RectangleTest.java
Labels: Bug

#184 ShardBucketCollection
  src/main/java/org/openstreetmap/atlas/geography/Rectangle.java
  src/main/java/org/openstreetmap/atlas/utilities/collections/ShardBucketCollection.java
  src/main/java/org/openstreetmap/atlas/utilities/scalars/Counter.java
  src/test/java/org/openstreetmap/atlas/geography/RectangleTest.java
  src/test/java/org/openstreetmap/atlas/utilities/collections/ShardBucketCollectionTest.java
  src/test/java/org/openstreetmap/atlas/utilities/collections/ShardBucketCollectionTestClasses.java
Labels: New Feature

#187 Fix way-section identifier bug for closed loops
  src/main/java/org/openstreetmap/atlas/geography/atlas/raw/sectioning/WaySectionProcessor.java
  src/test/java/org/openstreetmap/atlas/geography/atlas/raw/sectioning/WaySectionProcessorTest.java
Labels: Bug

#189 Serialize
  src/main/java/org/openstreetmap/atlas/utilities/collections/ShardBucketCollection.java
  src/test/java/org/openstreetmap/atlas/utilities/collections/ShardBucketCollectionTest.java
Labels: Enhancement

#191 Turn Restriction Unit Test
  src/test/java/org/openstreetmap/atlas/geography/atlas/items/complex/restriction/ComplexTurnRestrictionTest.java
  src/test/java/org/openstreetmap/atlas/geography/atlas/items/complex/restriction/ComplexTurnRestrictionTestCaseRule.java
Labels: Enhancement

#192 Fixed Max Width Polygon Enclosure Bug
  src/main/java/org/openstreetmap/atlas/geography/Polygon.java
  src/test/java/org/openstreetmap/atlas/geography/PolygonTest.java
Labels: Bug

#188 Update TestAtlasHandler to rely on Raw Atlas Flow
  src/main/java/org/openstreetmap/atlas/utilities/testing/TestAtlasHandler.java
Labels: Enhancement

#193 Small changes to AtlasDelta toDiffViewFriendlyString method
  src/main/java/org/openstreetmap/atlas/geography/atlas/delta/Diff.java
Labels: Logging

#183 Added generic Resource caching capabilities
  src/main/java/org/openstreetmap/atlas/utilities/caching/ConcurrentResourceCache.java
  src/main/java/org/openstreetmap/atlas/utilities/caching/LocalFileInMemoryCache.java
  src/main/java/org/openstreetmap/atlas/utilities/caching/README.md
  src/main/java/org/openstreetmap/atlas/utilities/caching/strategies/AbstractCachingStrategy.java
  src/main/java/org/openstreetmap/atlas/utilities/caching/strategies/ByteArrayCachingStrategy.java
  src/main/java/org/openstreetmap/atlas/utilities/caching/strategies/CachingStrategy.java
  src/main/java/org/openstreetmap/atlas/utilities/caching/strategies/NoCachingStrategy.java
  src/main/java/org/openstreetmap/atlas/utilities/caching/strategies/SystemTemporaryFileCachingStrategy.java
  src/test/java/org/openstreetmap/atlas/utilities/caching/ByteArrayCachingStrategyResizeTest.java
  src/test/java/org/openstreetmap/atlas/utilities/caching/CachingTests.java
Labels: New Feature

#194 Adding Ice Road Tag and Updating Access Tag Values
  src/main/java/org/openstreetmap/atlas/tags/AccessTag.java
  src/main/java/org/openstreetmap/atlas/tags/IceRoadTag.java
Labels: Enhancement

#196 Addressed a bug in the new caching code as reported by Sonar
  src/main/java/org/openstreetmap/atlas/utilities/caching/strategies/ByteArrayCachingStrategy.java
Labels: Bug

#197 Added a sonar badge
  README.md
Labels: Documentation

#195 AtlasDelta and AtlasDeltaGenerator Revamp
  CONTRIBUTING.md
  images/slf4j.png
  src/integrationTest/java/org/openstreetmap/atlas/geography/atlas/delta/AtlasDeltaGeoJsonIntegrationTest.java
  src/integrationTest/java/org/openstreetmap/atlas/geography/atlas/delta/AtlasDeltaIntegrationTest.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/delta/AtlasDelta.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/delta/AtlasDeltaGenerator.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/delta/Diff.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/packed/README.md
  src/test/java/org/openstreetmap/atlas/geography/atlas/delta/AtlasDeltaEdgeTest.java
Labels: Documentation, Enhancement

#198 Added an always true filter for atlas loading
  src/main/java/org/openstreetmap/atlas/geography/atlas/AtlasResourceLoader.java
  src/test/java/org/openstreetmap/atlas/geography/atlas/AtlasResourceLoaderTest.java
Labels: Enhancement

#199 Atlas Delta Generator Sharded
  src/main/java/org/openstreetmap/atlas/geography/atlas/delta/AtlasDeltaGenerator.java
Labels: Enhancement

#201 Synthetic Boundary Node Tagging
  src/main/java/org/openstreetmap/atlas/geography/atlas/pbf/OsmPbfProcessor.java
  src/test/java/org/openstreetmap/atlas/geography/atlas/pbf/OsmPbfProcessorTest.java
  src/test/java/org/openstreetmap/atlas/geography/atlas/raw/RawAtlasTest.java
  src/test/resources/org/openstreetmap/atlas/geography/atlas/pbf/DNK_SWE_boundary.txt
  src/test/resources/org/openstreetmap/atlas/geography/atlas/pbf/outsideConnectedOneWayWays.osm
  src/test/resources/org/openstreetmap/atlas/geography/atlas/raw/DNK_SWE_boundary.txt
  src/test/resources/org/openstreetmap/atlas/geography/atlas/raw/outsideConnectedOneWayWays.osm
Labels: Bug

#200 StringCompressedPolyLine now supports WKB for incompressible polylines
  src/main/java/org/openstreetmap/atlas/geography/PolyLine.java
  src/main/java/org/openstreetmap/atlas/geography/StringCompressedPolyLine.java
  src/test/java/org/openstreetmap/atlas/geography/StringCompressedPolyLineTest.java
Labels: Bug

#202 Added CountryToShardList Caching
  src/main/java/org/openstreetmap/atlas/geography/boundary/CountryToShardListCache.java
  src/test/java/org/openstreetmap/atlas/geography/boundary/CountryToShardListCacheTest.java
  src/test/resources/org/openstreetmap/atlas/geography/boundary/countryToShardList.txt
Labels: New Feature

#203 Fixing Way Section Exceeding Limit Bug
  src/main/java/org/openstreetmap/atlas/geography/atlas/raw/sectioning/WaySectionProcessor.java
  src/main/java/org/openstreetmap/atlas/tags/SyntheticInvalidWaySectionTag.java
  src/test/java/org/openstreetmap/atlas/geography/atlas/raw/sectioning/WaySectionProcessorTest.java
  src/test/java/org/openstreetmap/atlas/geography/atlas/raw/sectioning/WaySectionProcessorTestRule.java
  src/test/resources/org/openstreetmap/atlas/geography/atlas/raw/sectioning/wayExceedingSectioningLimit.atlas.txt
Labels: Bug

#206 Adding Direction Tag
  src/main/java/org/openstreetmap/atlas/tags/DirectionTag.java
Labels: Enhancement

#205 Feature concatenate geojson with object properties
  src/main/java/org/openstreetmap/atlas/geography/geojson/ConcatenateGeoJsonCommand.java
  src/main/java/org/openstreetmap/atlas/geography/geojson/GeoJsonBuilder.java
  src/main/java/org/openstreetmap/atlas/streaming/resource/File.java
  src/test/java/org/openstreetmap/atlas/geography/geojson/ConcatenateGeoJsonCommandTest.java
  src/test/java/org/openstreetmap/atlas/geography/geojson/GeoJsonBuilderTest.java
  src/test/resources/org/openstreetmap/atlas/geography/geojson/concatenated_geojson_files_expected
  src/test/resources/org/openstreetmap/atlas/geography/geojson/test1.geojson
  src/test/resources/org/openstreetmap/atlas/geography/geojson/test2.geojson
Labels: Enhancement

#211 Removing IsoCountry from country code assignment when merging relations
  src/main/java/org/openstreetmap/atlas/geography/atlas/raw/slicing/RawAtlasRelationSlicer.java
Labels: Bug

#210 WaySectionProcessor performance improvements
  src/integrationTest/java/org/openstreetmap/atlas/geography/atlas/raw/RawAtlasIntegrationTest.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/raw/sectioning/WaySectionProcessor.java
  src/test/java/org/openstreetmap/atlas/geography/atlas/raw/sectioning/WaySectionProcessorTest.java
  src/test/java/org/openstreetmap/atlas/geography/atlas/raw/sectioning/WaySectionProcessorTestRule.java
  src/test/resources/org/openstreetmap/atlas/geography/atlas/raw/sectioning/rawAtlasSpanningOutsideBoundary.atlas.txt
Labels: Bug, Enhancement, Performance

#208 DynamicAtlas improvements: Multi-Atlas loading and hotspots
  src/main/java/org/openstreetmap/atlas/geography/atlas/AbstractAtlas.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/BareAtlas.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/dynamic/DynamicAtlas.java
  src/test/java/org/openstreetmap/atlas/geography/atlas/dynamic/DynamicAtlasPreemptiveLoadTest.java
Labels: Enhancement, Performance
