Repository osmlab/atlas, pull requests merged in 2019-09, with the labels that each got.

#516 Implemented more CompleteRelation API methods for ease of use
  src/main/java/org/openstreetmap/atlas/geography/atlas/builder/RelationBean.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/complete/CompleteArea.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/complete/CompleteEdge.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/complete/CompleteEntity.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/complete/CompleteLine.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/complete/CompleteNode.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/complete/CompletePoint.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/complete/CompleteRelation.java
  src/test/java/org/openstreetmap/atlas/geography/atlas/change/ChangeAtlasTest.java
  src/test/java/org/openstreetmap/atlas/geography/atlas/change/ChangeAtlasTestRule.java
  src/test/java/org/openstreetmap/atlas/geography/atlas/change/MemberMergeStrategiesTest.java
  src/test/java/org/openstreetmap/atlas/utilities/identifiers/EntityIdentifierGeneratorTest.java
Labels: Enhancement

#518 Atlas Command: AtlasShardingConverterCommand
  src/main/java/org/openstreetmap/atlas/geography/sharding/DynamicTileSharding.java
  src/main/java/org/openstreetmap/atlas/geography/sharding/GeoHashSharding.java
  src/main/java/org/openstreetmap/atlas/geography/sharding/Sharding.java
  src/main/java/org/openstreetmap/atlas/geography/sharding/SlippyTileSharding.java
  src/main/java/org/openstreetmap/atlas/utilities/command/subcommands/AtlasShardingConverterCommand.java
  src/main/resources/org/openstreetmap/atlas/utilities/command/subcommands/AtlasShardingConverterCommandDescriptionSection.txt
  src/main/resources/org/openstreetmap/atlas/utilities/command/subcommands/AtlasShardingConverterCommandExamplesSection.txt
  src/test/java/org/openstreetmap/atlas/geography/sharding/DynamicTileShardingTest.java
  src/test/java/org/openstreetmap/atlas/geography/sharding/GeoHashShardingTest.java
  src/test/java/org/openstreetmap/atlas/geography/sharding/SlippyTileShardingTest.java
  src/test/java/org/openstreetmap/atlas/utilities/command/subcommands/ShardingConverterCommandTest.java
  src/test/resources/org/openstreetmap/atlas/utilities/command/subcommands/shardingConverter.josm.osm
Labels: New Feature

#519 CompleteEntity: Truncate pretty strings for large geometries
  src/main/java/org/openstreetmap/atlas/geography/atlas/complete/CompleteArea.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/complete/CompleteEdge.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/complete/CompleteEntity.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/complete/CompleteLine.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/complete/PrettifyStringFormat.java
  src/test/java/org/openstreetmap/atlas/geography/atlas/complete/CompleteEntityTest.java
Labels: Logging

#520 Cap message size in FeatureChangeMergeException
  src/main/java/org/openstreetmap/atlas/exception/change/FeatureChangeMergeException.java
  src/test/java/org/openstreetmap/atlas/exception/change/FeatureChangeMergeExceptionTest.java
Labels: Logging

#521 Included more points during point and line slicing
  src/main/java/org/openstreetmap/atlas/geography/atlas/raw/slicing/RawAtlasPointAndLineSlicer.java
  src/test/java/org/openstreetmap/atlas/geography/atlas/command/OsmPbfToAtlasSubCommandTest.java
Labels: Bug

#522 Fixed a bug with FeatureChange beforeView merging
  src/main/java/org/openstreetmap/atlas/geography/atlas/change/FeatureChangeMergingHelpers.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/complete/CompleteArea.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/complete/CompleteEdge.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/complete/CompleteLine.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/complete/CompleteNode.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/complete/CompletePoint.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/items/AtlasEntity.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/items/Edge.java
  src/main/java/org/openstreetmap/atlas/utilities/command/subcommands/AtlasSearchCommand.java
  src/test/java/org/openstreetmap/atlas/geography/atlas/change/ChangeAtlasTest.java
  src/test/java/org/openstreetmap/atlas/geography/atlas/change/FeatureChangeMergerTest.java
Labels: Bug

#523 Truncate now shows a triple dot for clarity
  src/main/java/org/openstreetmap/atlas/geography/atlas/complete/CompleteEntity.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/complete/PrettifyStringFormat.java
  src/test/java/org/openstreetmap/atlas/geography/atlas/complete/CompleteEntityTest.java
Labels: Enhancement

#524 FeatureChangeMergeException:Truncate after message re-construction
  src/main/java/org/openstreetmap/atlas/exception/CoreException.java
  src/main/java/org/openstreetmap/atlas/exception/change/FeatureChangeMergeException.java
  src/test/java/org/openstreetmap/atlas/exception/change/FeatureChangeMergeExceptionTest.java
Labels: Bug

#525 Revert partial naming change inadvertently included in PR 522
  src/main/java/org/openstreetmap/atlas/geography/atlas/complete/CompleteNode.java
  src/test/java/org/openstreetmap/atlas/geography/atlas/change/ChangeAtlasTest.java
  src/test/java/org/openstreetmap/atlas/geography/atlas/change/FeatureChangeMergerTest.java
Labels: Bug

#526 Refactored CompleteEntity method names for consistency
  src/main/java/org/openstreetmap/atlas/geography/atlas/change/testing/AtlasChangeGeneratorSplitRoundabout.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/complete/CompleteEntity.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/complete/CompleteNode.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/complete/CompleteRelation.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/raw/slicing/RawAtlasPointAndLineSlicer.java
  src/test/java/org/openstreetmap/atlas/geography/atlas/change/ChangeAtlasTest.java
  src/test/java/org/openstreetmap/atlas/geography/atlas/change/FeatureChangeMergerTest.java
  src/test/java/org/openstreetmap/atlas/geography/atlas/complete/CompleteRelationTest.java
Labels: Breaking Change

#532 Cache: Retry downloading the file from the fetcher
  src/main/java/org/openstreetmap/atlas/utilities/caching/strategies/NamespaceCachingStrategy.java
Labels: Breaking Change, Bug

#533 Added ChangeDescription to the FeatureChange GeoJSON serialization
  src/main/java/org/openstreetmap/atlas/geography/atlas/change/Change.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/change/FeatureChange.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/change/description/ChangeDescription.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/change/description/ChangeDescriptorGenerator.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/change/description/descriptors/ChangeDescriptor.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/change/description/descriptors/ChangeDescriptorComparator.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/change/description/descriptors/ChangeDescriptorName.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/change/description/descriptors/GenericElementChangeDescriptor.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/change/description/descriptors/GeometryChangeDescriptor.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/change/description/descriptors/RelationMemberChangeDescriptor.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/change/description/descriptors/TagChangeDescriptor.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/change/serializer/ChangeGeoJsonSerializer.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/change/serializer/FeatureChangeGeoJsonSerializer.java
  src/test/java/org/openstreetmap/atlas/geography/atlas/change/FeatureChangeTest.java
  src/test/java/org/openstreetmap/atlas/geography/atlas/change/FeatureChangeUnitTestFactory.java
  src/test/java/org/openstreetmap/atlas/geography/atlas/change/description/descriptors/ChangeDescriptorComparatorTest.java
  src/test/java/org/openstreetmap/atlas/geography/atlas/change/serializer/ChangeGeoJsonSerializerTest.java
  src/test/java/org/openstreetmap/atlas/geography/atlas/change/serializer/FeatureChangeGeoJsonSerializerTest.java
  src/test/resources/org/openstreetmap/atlas/geography/atlas/change/serializer/serializedAddEdgeWithDescription.json
  src/test/resources/org/openstreetmap/atlas/geography/atlas/change/serializer/serializedAddRelationWithDescription.json
  src/test/resources/org/openstreetmap/atlas/geography/atlas/change/serializer/serializedRemoveAreaWithDescription.json
  src/test/resources/org/openstreetmap/atlas/geography/atlas/change/serializer/serializedUpdateEdgeWithDescription.json
Labels: Enhancement

#534 Refactored Shard string parsing to handle arbitrary shard types
  src/main/java/org/openstreetmap/atlas/geography/boundary/CountryToShardListCache.java
  src/main/java/org/openstreetmap/atlas/geography/sharding/CountryShard.java
  src/main/java/org/openstreetmap/atlas/geography/sharding/GeoHashTile.java
  src/main/java/org/openstreetmap/atlas/geography/sharding/Shard.java
  src/main/java/org/openstreetmap/atlas/geography/sharding/SlippyTile.java
  src/main/java/org/openstreetmap/atlas/geography/sharding/converters/SlippyTileConverter.java
  src/main/java/org/openstreetmap/atlas/geography/sharding/converters/StringToShardConverter.java
  src/main/java/org/openstreetmap/atlas/utilities/collections/StringList.java
  src/main/java/org/openstreetmap/atlas/utilities/command/subcommands/PbfToAtlasCommand.java
  src/main/java/org/openstreetmap/atlas/utilities/command/subcommands/ShardToBoundsCommand.java
  src/main/resources/org/openstreetmap/atlas/utilities/command/subcommands/ShardToBoundsCommandDescriptionSection.txt
  src/main/resources/org/openstreetmap/atlas/utilities/command/subcommands/ShardToBoundsCommandExamplesSection.txt
  src/test/java/org/openstreetmap/atlas/geography/boundary/CountryToShardListCacheTest.java
  src/test/java/org/openstreetmap/atlas/geography/sharding/converters/StringToShardConverterTest.java
Labels: Enhancement

#535 Extend FC bounds expansion to relation members
  src/main/java/org/openstreetmap/atlas/geography/atlas/change/AtlasChangeGenerator.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/change/FeatureChangeBoundsExpander.java
  src/test/java/org/openstreetmap/atlas/geography/atlas/change/AtlasChangeGeneratorTest.java
  src/test/resources/org/openstreetmap/atlas/geography/atlas/change/nodeBoundsExpansionAtlas.josm.osm
Labels: Enhancement

#536 Allow Namespace caching implementations to validate local file
  src/main/java/org/openstreetmap/atlas/geography/atlas/packed/PackedAtlasSerializer.java
  src/main/java/org/openstreetmap/atlas/utilities/caching/strategies/NamespaceCachingStrategy.java
Labels: New Feature

#537 Some QoL updates to Atlas Shell Tools
  atlas-shell-tools/ast_completions.bash
  atlas-shell-tools/man/man1/atlas-config-activate.1
  atlas-shell-tools/man/man1/atlas-config-deactivate.1
  atlas-shell-tools/man/man1/atlas-config-install.1
  atlas-shell-tools/man/man1/atlas-config-list.1
  atlas-shell-tools/man/man1/atlas-config-log.1
  atlas-shell-tools/man/man1/atlas-config-preset.1
  atlas-shell-tools/man/man1/atlas-config-repo.1
  atlas-shell-tools/man/man1/atlas-config-reset.1
  atlas-shell-tools/man/man1/atlas-config-sync.1
  atlas-shell-tools/man/man1/atlas-config-uninstall.1
  atlas-shell-tools/man/man1/atlas-config-update.1
  atlas-shell-tools/man/man1/atlas-config.1
  atlas-shell-tools/man/man1/atlas.1
  atlas-shell-tools/man/man5/atlas-plumbing.5
  atlas-shell-tools/man/man7/atlas-cli.7
  atlas-shell-tools/man/man7/atlas-cookbook.7
  atlas-shell-tools/man/man7/atlas-glossary.7
  atlas-shell-tools/man/man7/atlas-presets.7
  atlas-shell-tools/man/man7/atlas-shell-tools.7
  atlas-shell-tools/scripts/atlas
  atlas-shell-tools/scripts/atlas-config
  atlas-shell-tools/scripts/common/ast_module_subsystem.pm
  atlas-shell-tools/scripts/common/ast_preset_subsystem.pm
  atlas-shell-tools/scripts/common/ast_repo_subsystem.pm
  atlas-shell-tools/scripts/common/ast_utilities.pm
  src/main/java/org/openstreetmap/atlas/utilities/command/documentation/PagerHelper.java
Labels: Enhancement

#538 EntityIdentifierGenerator no longer relies on external toString methods
  src/main/java/org/openstreetmap/atlas/utilities/identifiers/EntityIdentifierGenerator.java
  src/test/java/org/openstreetmap/atlas/utilities/identifiers/EntityIdentifierGeneratorTest.java
Labels: Bug
