Repository osmlab/atlas, pull requests merged in 2019-10, with the labels that each got.

#543 Added converter for converting multiple PolyLines to MultiPolygon
  src/main/java/org/openstreetmap/atlas/geography/converters/MultiplePolyLineToMultiPolygonConverter.java
  src/test/java/org/openstreetmap/atlas/geography/converters/MultiplePolyLineToMultiPolygonConverterTest.java
Labels: Enhancement

#541 Shard listing now uses getName instead of toString
  src/main/java/org/openstreetmap/atlas/geography/boundary/CountryToShardListing.java
  src/test/java/org/openstreetmap/atlas/geography/sharding/converters/StringToShardConverterTest.java
Labels: Bug

#544 Added any2geojson command to convert various data to GeoJSON
  src/main/java/org/openstreetmap/atlas/geography/boundary/CountryBoundaryMap.java
  src/main/java/org/openstreetmap/atlas/geography/boundary/converters/CountryBoundaryMapGeoJsonConverter.java
  src/main/java/org/openstreetmap/atlas/geography/sharding/Sharding.java
  src/main/java/org/openstreetmap/atlas/utilities/command/subcommands/AnyToGeoJsonCommand.java
  src/main/java/org/openstreetmap/atlas/utilities/command/subcommands/OsmToAtlasCommand.java
  src/main/resources/org/openstreetmap/atlas/utilities/command/subcommands/AnyToGeoJsonCommandDescriptionSection.txt
  src/main/resources/org/openstreetmap/atlas/utilities/command/subcommands/AnyToGeoJsonCommandExamplesSection.txt
  src/test/java/org/openstreetmap/atlas/geography/boundary/converters/CountryBoundaryMapGeoJsonConverterTest.java
  src/test/resources/org/openstreetmap/atlas/geography/boundary/AAA_boundary.expected.json
  src/test/resources/org/openstreetmap/atlas/geography/boundary/AAA_boundary.txt
Labels: Enhancement

#546 Added CountryShard string constructor
  src/main/java/org/openstreetmap/atlas/geography/sharding/CountryShard.java
  src/test/java/org/openstreetmap/atlas/geography/sharding/CountryShardTest.java
Labels: Enhancement

#547 ZSH support for Atlas Shell Tools
  atlas-shell-tools/README.md
  atlas-shell-tools/ast_completions.bash
  atlas-shell-tools/ast_completions.zsh
  atlas-shell-tools/quick_install_zsh.sh
  atlas-shell-tools/scripts/atlas-config
  atlas-shell-tools/scripts/common/ast_completions.pm
Labels: Enhancement

#548 Some Atlas Shell Tools bug fixes and zsh support follow-up
  atlas-shell-tools/man/man1/atlas-config-list.1
  atlas-shell-tools/man/man1/atlas-config-preset.1
  atlas-shell-tools/man/man1/atlas-config-uninstall.1
  atlas-shell-tools/man/man1/atlas-config-update.1
  atlas-shell-tools/man/man1/atlas-config.1
  atlas-shell-tools/man/man1/atlas.1
  atlas-shell-tools/man/man7/atlas-glossary.7
  atlas-shell-tools/man/man7/atlas-presets.7
  atlas-shell-tools/man/man7/atlas-shell-tools.7
  atlas-shell-tools/scripts/atlas
  atlas-shell-tools/scripts/atlas-config
  atlas-shell-tools/scripts/common/ast_completions.pm
  atlas-shell-tools/scripts/common/ast_preset_subsystem.pm
  atlas-shell-tools/scripts/common/ast_utilities.pm
Labels: Enhancement

#549 Convert to WKT Polygon when MultiPolygon has only one outer
  src/integrationTest/java/org/openstreetmap/atlas/geography/boundary/CountryBoundaryMapIntegrationTest.java
  src/main/java/org/openstreetmap/atlas/geography/converters/WkMultiPolygonConverter.java
  src/main/java/org/openstreetmap/atlas/geography/converters/jts/JtsPolygonToMultiPolygonConverter.java
  src/test/java/org/openstreetmap/atlas/geography/converters/WktMultiPolygonConverterTest.java
  src/test/resources/org/openstreetmap/atlas/geography/boundary/HTI_boundary.txt
  src/test/resources/org/openstreetmap/atlas/geography/boundary/USA_boundary_reduced.txt
Labels: Breaking Change, Bug

#552 Better error description when PolyLines are corrupted
  src/main/java/org/openstreetmap/atlas/geography/StringCompressedPolyLine.java
Labels: Enhancement

#553 Remove hyphen from FeatureChange metadata property name
  src/main/java/org/openstreetmap/atlas/geography/atlas/change/serializer/FeatureChangeGeoJsonSerializer.java
  src/test/resources/org/openstreetmap/atlas/geography/atlas/change/serializer/change.json
  src/test/resources/org/openstreetmap/atlas/geography/atlas/change/serializer/serializedAddEdgeWithDescription.json
  src/test/resources/org/openstreetmap/atlas/geography/atlas/change/serializer/serializedAddRelationWithDescription.json
  src/test/resources/org/openstreetmap/atlas/geography/atlas/change/serializer/serializedAreaFull.json
  src/test/resources/org/openstreetmap/atlas/geography/atlas/change/serializer/serializedAreaNull.json
  src/test/resources/org/openstreetmap/atlas/geography/atlas/change/serializer/serializedAreaRemove.json
  src/test/resources/org/openstreetmap/atlas/geography/atlas/change/serializer/serializedEdgeFull.json
  src/test/resources/org/openstreetmap/atlas/geography/atlas/change/serializer/serializedEdgeNull.json
  src/test/resources/org/openstreetmap/atlas/geography/atlas/change/serializer/serializedEdgeRemove.json
  src/test/resources/org/openstreetmap/atlas/geography/atlas/change/serializer/serializedLineFull.json
  src/test/resources/org/openstreetmap/atlas/geography/atlas/change/serializer/serializedLineNull.json
  src/test/resources/org/openstreetmap/atlas/geography/atlas/change/serializer/serializedLineRemove.json
  src/test/resources/org/openstreetmap/atlas/geography/atlas/change/serializer/serializedNodeFull.json
  src/test/resources/org/openstreetmap/atlas/geography/atlas/change/serializer/serializedNodeNull.json
  src/test/resources/org/openstreetmap/atlas/geography/atlas/change/serializer/serializedNodeRemove.json
  src/test/resources/org/openstreetmap/atlas/geography/atlas/change/serializer/serializedPointFull.json
  src/test/resources/org/openstreetmap/atlas/geography/atlas/change/serializer/serializedPointNull.json
  src/test/resources/org/openstreetmap/atlas/geography/atlas/change/serializer/serializedPointRemove.json
  src/test/resources/org/openstreetmap/atlas/geography/atlas/change/serializer/serializedRelationFull.json
  src/test/resources/org/openstreetmap/atlas/geography/atlas/change/serializer/serializedRelationNull.json
  src/test/resources/org/openstreetmap/atlas/geography/atlas/change/serializer/serializedRelationRemove.json
  src/test/resources/org/openstreetmap/atlas/geography/atlas/change/serializer/serializedRemoveAreaWithDescription.json
  src/test/resources/org/openstreetmap/atlas/geography/atlas/change/serializer/serializedUpdateEdgeWithDescription.json
Labels: Data Change

#550 Fixed a GZIP bug in NamespaceCachingStrategy
  src/main/java/org/openstreetmap/atlas/utilities/caching/strategies/NamespaceCachingStrategy.java
  src/test/java/org/openstreetmap/atlas/utilities/caching/CachingTests.java
  src/test/resources/org/openstreetmap/atlas/utilities/caching/hello.txt.gz
Labels: Bug

#555 CountryBoundaryMapArchiver consolidation
  src/integrationTest/java/org/openstreetmap/atlas/geography/boundary/CountryBoundaryMapArchiverIntegrationTest.java
  src/integrationTest/resources/org/openstreetmap/atlas/geography/boundary/oceanTestBoundary.txt
  src/main/java/org/openstreetmap/atlas/geography/boundary/CountryBoundaryMapArchiver.java
  src/main/java/org/openstreetmap/atlas/geography/boundary/CountryBoundaryMapPrinter.java
  src/main/java/org/openstreetmap/atlas/geography/boundary/OceanCountryBoundaryMap.java
  src/main/java/org/openstreetmap/atlas/streaming/resource/File.java
  src/main/java/org/openstreetmap/atlas/streaming/resource/TemporaryFile.java
  src/main/java/org/openstreetmap/atlas/utilities/collections/StringList.java
  src/test/java/org/openstreetmap/atlas/geography/boundary/OceanCountryBoundaryMapTest.java
  src/test/java/org/openstreetmap/atlas/utilities/collections/StringListTest.java
Labels: Breaking Change, Enhancement

#556 FeatureChange GeoJSON serialization now uses consistent ordering
  src/main/java/org/openstreetmap/atlas/geography/atlas/change/FeatureChangeMergingHelpers.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/change/serializer/FeatureChangeGeoJsonSerializer.java
  src/test/java/org/openstreetmap/atlas/geography/atlas/change/FeatureChangeMergerTest.java
  src/test/java/org/openstreetmap/atlas/geography/atlas/change/serializer/FeatureChangeGeoJsonSerializerTest.java
  src/test/resources/org/openstreetmap/atlas/geography/atlas/change/serializer/serializedPointWithTags.json
Labels: Bug, Enhancement
