Repository osmlab/atlas, pull requests merged in 2019-12, with the labels that each got.

#576 pyatlas now supports Python 3!
  pyatlas/README.md
  pyatlas/package.sh
  pyatlas/pyatlas/__init__.py
  pyatlas/pyatlas/atlas.py
  pyatlas/pyatlas/atlas_entities.py
  pyatlas/pyatlas/geometry.py
  pyatlas/pyatlas/identifier_converters.py
  pyatlas/pyatlas/pyatlas_globalfunc.py
  pyatlas/pyatlas/spatial_index.py
  pyatlas/setup.py
  pyatlas/unit_tests/test_atlas.py
  pyatlas/unit_tests/test_polygon_converters.py
  pyatlas/unit_tests/test_spatial_index.py
  pyatlas/venv.sh
  pyatlas/yapf_format.py
Labels: Breaking Change, Enhancement

#578 Added another spatial function to pyatlas
  gradle.properties
  pyatlas/pyatlas/atlas.py
  pyatlas/pyatlas/geometry.py
  pyatlas/unit_tests/test_polyline_polygon.py
Labels: Enhancement

#579 Added in tag summary map method for Change
  src/main/java/org/openstreetmap/atlas/geography/atlas/change/Change.java
  src/test/java/org/openstreetmap/atlas/geography/atlas/change/diff/AtlasDiffTest.java
Labels: Enhancement

#581 Tippecanoe Bugs and Redundancy
  src/main/java/org/openstreetmap/atlas/geography/atlas/geojson/LineDelimitedGeoJsonConverter.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/items/AtlasEntity.java
  src/test/resources/org/openstreetmap/atlas/geography/atlas/line-delimited-geojson.txt
Labels: Bug
