Repository osmlab/atlas, pull requests merged in 2019-04, with the labels that each got.

#392 Make test AtlasChangeGenerators available to other projects
  src/main/java/org/openstreetmap/atlas/geography/atlas/change/testing/AtlasChangeGeneratorAddTurnRestrictions.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/change/testing/AtlasChangeGeneratorRemoveReverseEdges.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/change/testing/AtlasChangeGeneratorSplitRoundabout.java
  src/test/java/org/openstreetmap/atlas/geography/atlas/change/MultipleChangeAtlasTest.java
Labels: Enhancement

#404 Allow for empty changes in AtlasChangeGenerator
  src/main/java/org/openstreetmap/atlas/geography/atlas/change/AtlasChangeGenerator.java
  src/test/java/org/openstreetmap/atlas/geography/atlas/change/AtlasChangeGeneratorTest.java
Labels: Bug

#405 Force Atlas context to be applied in AtlasChangeGenerator
  src/main/java/org/openstreetmap/atlas/geography/atlas/change/AtlasChangeGenerator.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/change/FeatureChange.java
  src/test/java/org/openstreetmap/atlas/geography/atlas/change/AtlasChangeGeneratorTest.java
Labels: Enhancement

#406 Make a test AtlasChangeGenerator configurable
  src/main/java/org/openstreetmap/atlas/geography/atlas/change/testing/AtlasChangeGeneratorAddTurnRestrictions.java
Labels: Enhancement

#403 FeatureChange merging now incorporates explicitlyExcluded sets
  src/main/java/org/openstreetmap/atlas/geography/atlas/builder/RelationBean.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/change/MemberMergeStrategies.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/complete/CompleteRelation.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/items/RelationMemberList.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/packed/PackedAtlas.java
  src/test/java/org/openstreetmap/atlas/geography/atlas/change/FeatureChangeMergerTest.java
  src/test/java/org/openstreetmap/atlas/geography/atlas/change/MemberMergeStrategiesTest.java
  src/test/java/org/openstreetmap/atlas/geography/atlas/complete/CompleteRelationTest.java
  src/test/java/org/openstreetmap/atlas/geography/atlas/items/RelationMemberListTest.java
Labels: Bug, Documentation

#401 AtlasDiff now uses atlas context
  src/main/java/org/openstreetmap/atlas/geography/atlas/change/diff/AtlasDiff.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/change/diff/AtlasDiffHelper.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/validators/FeatureChangeUsefulnessValidator.java
  src/test/java/org/openstreetmap/atlas/geography/atlas/change/diff/AtlasDiffTest.java
  src/test/java/org/openstreetmap/atlas/geography/atlas/change/diff/AtlasDiffTestRule.java
Labels: Enhancement

#407 ChangeAtlas performance improvements
  src/main/java/org/openstreetmap/atlas/geography/atlas/change/AtlasChangeGenerator.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/change/ChangeArea.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/change/ChangeAtlas.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/change/ChangeEdge.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/change/ChangeEntity.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/change/ChangeLine.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/change/ChangeNode.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/change/ChangePoint.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/change/ChangeRelation.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/change/FeatureChange.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/validators/AtlasValidator.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/validators/FeatureChangeUsefulnessValidator.java
  src/test/java/org/openstreetmap/atlas/geography/atlas/change/AtlasChangeGeneratorTest.java
  src/test/java/org/openstreetmap/atlas/geography/atlas/validators/AtlasValidatorTest.java
Labels: Enhancement

#410 ChangeAtlas: have member extraction names for better debugging
  src/main/java/org/openstreetmap/atlas/geography/atlas/change/ChangeArea.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/change/ChangeEdge.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/change/ChangeEntity.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/change/ChangeLine.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/change/ChangeNode.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/change/ChangePoint.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/change/ChangeRelation.java
Labels: Enhancement

#409 Ocean boundary map command
  build.gradle
  dependencies.gradle
  src/main/java/org/openstreetmap/atlas/geography/boundary/CountryBoundaryMap.java
  src/main/java/org/openstreetmap/atlas/geography/boundary/OceanCountryBoundaryMap.java
  src/test/java/org/openstreetmap/atlas/geography/boundary/OceanCountryBoundaryMapTest.java
  src/test/resources/org/openstreetmap/atlas/geography/boundary/oceanTestBoundary.txt
Labels: New Feature

#411 use configuration to handle water types
  src/main/java/org/openstreetmap/atlas/geography/atlas/items/complex/islands/ComplexIslandFinder.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/items/complex/waters/ComplexWaterEntity.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/items/complex/waters/ComplexWaterEntityFinder.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/items/complex/waters/ComplexWaterbody.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/items/complex/waters/ComplexWaterway.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/items/complex/waters/WaterType.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/items/complex/waters/handler/AbstractWaterHandler.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/items/complex/waters/handler/CanalHandler.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/items/complex/waters/handler/CreekHandler.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/items/complex/waters/handler/DitchHandler.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/items/complex/waters/handler/HarbourHandler.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/items/complex/waters/handler/LagoonHandler.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/items/complex/waters/handler/LakeHandler.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/items/complex/waters/handler/PondHandler.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/items/complex/waters/handler/PoolHandler.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/items/complex/waters/handler/ReservoirHandler.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/items/complex/waters/handler/RiverHandler.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/items/complex/waters/handler/SeaHandler.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/items/complex/waters/handler/WaterHandler.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/items/complex/waters/handler/WetlandHandler.java
  src/main/java/org/openstreetmap/atlas/utilities/configuration/ConfigurationReader.java
  src/main/java/org/openstreetmap/atlas/utilities/configuration/ConfiguredFilter.java
  src/main/resources/org/openstreetmap/atlas/geography/atlas/items/complex/waters/water-handlers.json
  src/test/java/org/openstreetmap/atlas/geography/atlas/items/complex/water/ComplexHarbourTest.java
  src/test/java/org/openstreetmap/atlas/geography/atlas/items/complex/water/ComplexIslandTest.java
  src/test/java/org/openstreetmap/atlas/geography/atlas/items/complex/water/ComplexWaterEntityTest.java
Labels: Data Change, Enhancement

#413 Lombok support in Atlas
  build.gradle
  dependencies.gradle
  gradle/quality.gradle
  src/test/java/org/openstreetmap/atlas/dependency/LombokTest.java
Labels: Enhancement

#412 Change Event Handling
  src/main/java/org/openstreetmap/atlas/geography/atlas/change/ChangeType.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/change/FeatureChange.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/change/eventhandling/event/EntityChangeEvent.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/change/eventhandling/event/TagChangeEvent.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/change/eventhandling/event/consts/FieldChangeOperation.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/change/eventhandling/listenable/EntityChangeListenable.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/change/eventhandling/listenable/TagChangeListenable.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/change/eventhandling/listener/EntityChangeListener.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/change/eventhandling/listener/TagChangeListener.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/complete/CompleteArea.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/complete/CompleteEdge.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/complete/CompleteEntity.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/complete/CompleteLine.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/complete/CompleteLineItem.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/complete/CompleteLocationItem.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/complete/CompleteNode.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/complete/CompletePoint.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/complete/CompleteRelation.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/complete/TagChangeDelegate.java
  src/test/java/org/openstreetmap/atlas/geography/atlas/change/eventhandling/listener/TagChangeListenerTest.java
  src/test/java/org/openstreetmap/atlas/geography/atlas/change/eventhandling/listener/TestTagChangeListenerImplementation.java
Labels: Enhancement

#419 Update atlas-area.json
  src/main/resources/org/openstreetmap/atlas/geography/atlas/pbf/atlas-area.json
Labels: Enhancement

#417 Count point barriers only
  src/main/resources/org/openstreetmap/atlas/geography/atlas/statistics/coverage/poi/counts.txt
Labels: Enhancement

#416 Make CountryShard implement Shard directly
  src/main/java/org/openstreetmap/atlas/geography/sharding/CountryShard.java
  src/test/java/org/openstreetmap/atlas/geography/sharding/CountryShardTest.java
Labels: New Feature

#418 Conflicting beforeView forgiveness for Relations
  config/checkstyle/suppressions.xml
  src/main/java/org/openstreetmap/atlas/geography/atlas/builder/RelationBean.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/change/FeatureChange.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/change/FeatureChangeMergingHelpers.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/change/MemberMergeStrategies.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/change/MemberMerger.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/change/MergedMemberBean.java
  src/main/java/org/openstreetmap/atlas/utilities/function/QuaternaryFunction.java
  src/main/java/org/openstreetmap/atlas/utilities/function/QuaternaryOperator.java
  src/test/java/org/openstreetmap/atlas/geography/atlas/change/FeatureChangeMergerTest.java
  src/test/java/org/openstreetmap/atlas/geography/atlas/change/MemberMergeStrategiesTest.java
  src/test/java/org/openstreetmap/atlas/geography/atlas/change/TagChangeTest.java
Labels: Enhancement

#423 Improve zip reading performance
  src/main/java/org/openstreetmap/atlas/streaming/resource/zip/ZipResource.java
Labels: Enhancement

#425 buildNoTrim option for RawAtlasGenerator
  src/main/java/org/openstreetmap/atlas/geography/atlas/raw/creation/RawAtlasGenerator.java
Labels: Enhancement

#422 Conflicting beforeView forgiveness for Nodes
  config/checkstyle/suppressions.xml
  src/main/java/org/openstreetmap/atlas/geography/atlas/change/ChangeNode.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/change/FeatureChangeMergingHelpers.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/change/MemberMergeStrategies.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/change/MemberMerger.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/change/diff/AtlasDiffHelper.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/complete/CompleteNode.java
  src/main/java/org/openstreetmap/atlas/utilities/function/SenaryFunction.java
  src/main/java/org/openstreetmap/atlas/utilities/function/SenaryOperator.java
  src/test/java/org/openstreetmap/atlas/geography/atlas/change/ChangeAtlasTest.java
  src/test/java/org/openstreetmap/atlas/geography/atlas/change/ChangeAtlasTestRule.java
  src/test/java/org/openstreetmap/atlas/geography/atlas/change/FeatureChangeMergerTest.java
  src/test/java/org/openstreetmap/atlas/geography/atlas/change/MemberMergeStrategiesTest.java
Labels: Enhancement

#424 Fixed a copy-reference bug with CompleteEntity tag updates
  src/main/java/org/openstreetmap/atlas/geography/atlas/change/MemberMergeStrategies.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/complete/CompleteArea.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/complete/CompleteEdge.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/complete/CompleteEntity.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/complete/CompleteLine.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/complete/CompleteNode.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/complete/CompletePoint.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/complete/CompleteRelation.java
  src/test/java/org/openstreetmap/atlas/geography/atlas/change/ChangeAtlasTest.java
  src/test/java/org/openstreetmap/atlas/geography/atlas/change/ChangeAtlasTestRule.java
  src/test/java/org/openstreetmap/atlas/geography/atlas/change/TagChangeTest.java
Labels: Bug
