Repository osmlab/atlas, pull requests merged in 2019-11, with the labels that each got.

#558 Fixed bug with FeatureChange JSON serialization
  src/main/java/org/openstreetmap/atlas/geography/atlas/change/serializer/FeatureChangeGeoJsonSerializer.java
  src/test/resources/org/openstreetmap/atlas/geography/atlas/change/serializer/serializedAreaNull.json
  src/test/resources/org/openstreetmap/atlas/geography/atlas/change/serializer/serializedAreaRemove.json
  src/test/resources/org/openstreetmap/atlas/geography/atlas/change/serializer/serializedEdgeNull.json
  src/test/resources/org/openstreetmap/atlas/geography/atlas/change/serializer/serializedEdgeRemove.json
  src/test/resources/org/openstreetmap/atlas/geography/atlas/change/serializer/serializedLineNull.json
  src/test/resources/org/openstreetmap/atlas/geography/atlas/change/serializer/serializedLineRemove.json
  src/test/resources/org/openstreetmap/atlas/geography/atlas/change/serializer/serializedNodeNull.json
  src/test/resources/org/openstreetmap/atlas/geography/atlas/change/serializer/serializedNodeRemove.json
  src/test/resources/org/openstreetmap/atlas/geography/atlas/change/serializer/serializedPointNull.json
  src/test/resources/org/openstreetmap/atlas/geography/atlas/change/serializer/serializedPointRemove.json
  src/test/resources/org/openstreetmap/atlas/geography/atlas/change/serializer/serializedRelationNull.json
  src/test/resources/org/openstreetmap/atlas/geography/atlas/change/serializer/serializedRelationRemove.json
Labels: Bug, Data Change

#559 Reworked relation slicing
  src/main/java/org/openstreetmap/atlas/geography/atlas/items/RelationMemberList.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/raw/slicing/RawAtlasCountrySlicer.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/raw/slicing/RawAtlasRelationSlicer.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/raw/slicing/RawAtlasSlicer.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/raw/slicing/changeset/ChangeSetHandler.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/raw/slicing/changeset/RelationChangeSet.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/raw/slicing/changeset/RelationChangeSetHandler.java
  src/main/java/org/openstreetmap/atlas/geography/boundary/CountryBoundaryMap.java
  src/main/java/org/openstreetmap/atlas/tags/ISOCountryTag.java
  src/main/resources/org/openstreetmap/atlas/geography/atlas/pbf/atlas-relation-slicing.json
  src/test/java/org/openstreetmap/atlas/geography/atlas/raw/slicing/RelationSlicingTest.java
  src/test/java/org/openstreetmap/atlas/geography/atlas/raw/slicing/RelationSlicingTestRule.java
Labels: Data Change, Enhancement

#565 Removed generics in ChangeDescriptorGenerator
  src/main/java/org/openstreetmap/atlas/geography/atlas/change/description/ChangeDescriptorGenerator.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/change/description/descriptors/ChangeDescriptorComparator.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/change/description/descriptors/LongElementChangeDescriptor.java
  src/test/java/org/openstreetmap/atlas/geography/atlas/change/description/descriptors/ChangeDescriptorComparatorTest.java
Labels: Enhancement

#566 Cache polyLine bounds for leafNodesIntersecting
  src/main/java/org/openstreetmap/atlas/geography/sharding/DynamicTileSharding.java
Labels: Enhancement

#568 Fixed a false positive bug in the Change validation
  src/main/java/org/openstreetmap/atlas/geography/atlas/change/validators/ChangeValidator.java
  src/main/java/org/openstreetmap/atlas/utilities/command/abstractcommand/AbstractAtlasShellToolsCommand.java
  src/main/java/org/openstreetmap/atlas/utilities/command/parsing/SimpleOptionAndArgumentParser.java
  src/test/java/org/openstreetmap/atlas/geography/atlas/change/ChangeTest.java
  src/test/java/org/openstreetmap/atlas/geography/atlas/change/validators/ChangeValidatorTest.java
  src/test/java/org/openstreetmap/atlas/utilities/command/SimpleOptionAndArgumentParserTest.java
Labels: Bug

#569 Fix bug with empty MultiPolygon conversion
  src/main/java/org/openstreetmap/atlas/geography/converters/jts/JtsCoordinateArrayConverter.java
  src/main/java/org/openstreetmap/atlas/geography/converters/jts/JtsLinearRingConverter.java
  src/main/java/org/openstreetmap/atlas/geography/converters/jts/JtsPolygonToMultiPolygonConverter.java
  src/test/java/org/openstreetmap/atlas/geography/converters/WktMultiPolygonConverterTest.java
Labels: Bug

#570 DynamicAtlasExpander: Cache covered entities to save time
  src/main/java/org/openstreetmap/atlas/geography/atlas/dynamic/DynamicAtlasExpander.java
Labels: Enhancement

#571 Enhance caching in DynamicAtlasExpander
  src/main/java/org/openstreetmap/atlas/geography/atlas/dynamic/DynamicAtlasExpander.java
Labels: Enhancement

#573 Changed field name to match geojson Descriptor class
  src/main/java/org/openstreetmap/atlas/geography/atlas/change/description/descriptors/LongElementChangeDescriptor.java
  src/test/resources/org/openstreetmap/atlas/geography/atlas/change/serializer/serializedAddEdgeWithDescription.json
  src/test/resources/org/openstreetmap/atlas/geography/atlas/change/serializer/serializedAddRelationWithDescription.json
  src/test/resources/org/openstreetmap/atlas/geography/atlas/change/serializer/serializedUpdateEdgeWithDescription.json
Labels: Data Change
