Repository osmlab/atlas, pull requests merged in 2019-08, with the labels that each got.

#495 Fix loxodromic midpoint on same circle of latitude
  src/main/java/org/openstreetmap/atlas/geography/Location.java
  src/test/java/org/openstreetmap/atlas/geography/LocationTest.java
Labels: Bug

#497 nodeForLocation now chooses lowest ID node if more than one Node is available
  src/main/java/org/openstreetmap/atlas/geography/atlas/packed/PackedAtlas.java
Labels: Data Change, Enhancement

#498 Return Optional.empty overall heading for looping LineItems
  src/main/java/org/openstreetmap/atlas/geography/atlas/items/LineItem.java
  src/test/java/org/openstreetmap/atlas/geography/atlas/items/LineItemTest.java
  src/test/java/org/openstreetmap/atlas/geography/atlas/items/LineItemTestRule.java
Labels: Bug

#499 Cleanup sonar issues and code duplications in PackedAtlas
  src/main/java/org/openstreetmap/atlas/geography/atlas/packed/PackedAtlas.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/packed/PackedAtlasLogMessages.java
Labels: Enhancement

#500 Fix Sonar issues
  src/main/java/org/openstreetmap/atlas/geography/atlas/command/AtlasItemsWithSharedShapepointsSubCommand.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/command/AtlasResourceLoaderErrorSubCommand.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/delta/AtlasDeltaGenerator.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/geojson/LineDelimitedGeoJsonConverter.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/items/complex/ComplexEntity.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/items/complex/aoi/ComplexAreaOfInterest.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/items/complex/bignode/BigNodeFinder.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/items/complex/buildings/BuildingPart.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/items/complex/highwayarea/ComplexHighwayArea.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/items/complex/islands/ComplexIsland.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/items/complex/waters/ComplexWaterEntity.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/packed/PackedAtlas.java
  src/main/java/org/openstreetmap/atlas/geography/converters/jts/GeometryStreamer.java
  src/main/java/org/openstreetmap/atlas/utilities/collections/Iterables.java
  src/main/java/org/openstreetmap/atlas/utilities/testing/OsmosisXmlReaderFromResource.java
  src/test/java/org/openstreetmap/atlas/utilities/collections/IterablesTest.java
Labels: Enhancement

#501 Fix sonar issues
  src/main/java/org/openstreetmap/atlas/geography/Longitude.java
  src/main/java/org/openstreetmap/atlas/geography/Polygon.java
  src/main/java/org/openstreetmap/atlas/geography/sharding/DynamicTileSharding.java
  src/main/java/org/openstreetmap/atlas/geography/sharding/SlippyTile.java
  src/main/java/org/openstreetmap/atlas/streaming/readers/CsvLine.java
  src/main/java/org/openstreetmap/atlas/streaming/readers/GeoJsonReader.java
  src/main/java/org/openstreetmap/atlas/streaming/resource/Resource.java
  src/main/java/org/openstreetmap/atlas/tags/FerryTag.java
  src/main/java/org/openstreetmap/atlas/tags/Taggable.java
  src/main/java/org/openstreetmap/atlas/utilities/arrays/ByteArrayOfArrays.java
  src/main/java/org/openstreetmap/atlas/utilities/arrays/IntegerArrayOfArrays.java
  src/main/java/org/openstreetmap/atlas/utilities/arrays/LargeArray.java
  src/main/java/org/openstreetmap/atlas/utilities/runtime/SingleLineMonitor.java
  src/main/java/org/openstreetmap/atlas/utilities/scalars/Angle.java
  src/main/java/org/openstreetmap/atlas/utilities/scalars/Duration.java
  src/main/java/org/openstreetmap/atlas/utilities/threads/Pool.java
  src/main/java/org/openstreetmap/atlas/utilities/threads/Result.java
  src/main/java/org/openstreetmap/atlas/utilities/timezone/TimeZoneMap.java
  src/test/java/org/openstreetmap/atlas/streaming/resource/ResourceTest.java
  src/test/java/org/openstreetmap/atlas/tags/FerryTagTest.java
  src/test/java/org/openstreetmap/atlas/tags/TaggableTest.java
  src/test/java/org/openstreetmap/atlas/utilities/scalars/DurationTest.java
  src/test/java/org/openstreetmap/atlas/utilities/threads/PoolTest.java
Labels: Enhancement

#503 Support for GeoHash sharding
  build.gradle
  dependencies.gradle
  src/main/java/org/openstreetmap/atlas/geography/sharding/DynamicTileSharding.java
  src/main/java/org/openstreetmap/atlas/geography/sharding/GeoHashSharding.java
  src/main/java/org/openstreetmap/atlas/geography/sharding/GeoHashTile.java
  src/main/java/org/openstreetmap/atlas/geography/sharding/GeoHashTileIterable.java
  src/main/java/org/openstreetmap/atlas/geography/sharding/Sharding.java
  src/main/java/org/openstreetmap/atlas/geography/sharding/SlippyTileSharding.java
  src/main/java/org/openstreetmap/atlas/geography/sharding/converters/RectangleToSpatial4JRectangleConverter.java
  src/test/java/org/openstreetmap/atlas/geography/sharding/GeoHashShardingTest.java
  src/test/java/org/openstreetmap/atlas/geography/sharding/GeoHashTileTest.java
  src/test/java/org/openstreetmap/atlas/geography/sharding/converters/RectangleToSpatial4JRectangleConverterTest.java
Labels: New Feature

#505 Fixed a bounds bug in CompleteRelation.withExtraMember
  src/main/java/org/openstreetmap/atlas/geography/atlas/complete/CompleteArea.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/complete/CompleteEdge.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/complete/CompleteEntity.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/complete/CompleteLine.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/complete/CompleteNode.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/complete/CompletePoint.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/complete/CompleteRelation.java
  src/test/java/org/openstreetmap/atlas/geography/atlas/complete/CompleteAreaTest.java
  src/test/java/org/openstreetmap/atlas/geography/atlas/complete/CompleteEdgeTest.java
  src/test/java/org/openstreetmap/atlas/geography/atlas/complete/CompleteLineTest.java
  src/test/java/org/openstreetmap/atlas/geography/atlas/complete/CompleteNodeTest.java
  src/test/java/org/openstreetmap/atlas/geography/atlas/complete/CompletePointTest.java
  src/test/java/org/openstreetmap/atlas/geography/atlas/complete/CompleteRelationTest.java
  src/test/java/org/openstreetmap/atlas/geography/atlas/complete/CompleteTestRule.java
Labels: Bug

#506 Copy CompleteEntity(ies)
  src/main/java/org/openstreetmap/atlas/geography/atlas/complete/CompleteArea.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/complete/CompleteEdge.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/complete/CompleteLine.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/complete/CompleteNode.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/complete/CompletePoint.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/complete/CompleteRelation.java
  src/test/java/org/openstreetmap/atlas/geography/atlas/complete/CompleteAreaTest.java
  src/test/java/org/openstreetmap/atlas/geography/atlas/complete/CompleteEdgeTest.java
  src/test/java/org/openstreetmap/atlas/geography/atlas/complete/CompleteLineTest.java
  src/test/java/org/openstreetmap/atlas/geography/atlas/complete/CompleteNodeTest.java
  src/test/java/org/openstreetmap/atlas/geography/atlas/complete/CompletePointTest.java
  src/test/java/org/openstreetmap/atlas/geography/atlas/complete/CompleteRelationTest.java
Labels: New Feature

#508 Use Gradle 5.6
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
Labels: Duplicate

#509 Validation of NodeToEdgeLocationAccuracy: Better error message
  src/main/java/org/openstreetmap/atlas/geography/atlas/validators/AtlasNodeValidator.java
Labels: Bug

#510 Allow to retrieve the DynamicAtlasPolicy from a DynamicAtlas
  src/main/java/org/openstreetmap/atlas/geography/atlas/dynamic/DynamicAtlas.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/dynamic/DynamicAtlasExpander.java
  src/test/java/org/openstreetmap/atlas/geography/atlas/dynamic/DynamicAtlasTest.java
Labels: Enhancement
