Repository osmlab/atlas, pull requests merged in 2019-06, with the labels that each got.

#454 Updated atlasDiff command to use pretty print strings
  src/main/java/org/openstreetmap/atlas/geography/atlas/change/Change.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/change/FeatureChange.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/change/serializer/ChangeGeoJsonSerializer.java
  src/main/java/org/openstreetmap/atlas/utilities/command/subcommands/AtlasDiffCommand.java
  src/main/resources/org/openstreetmap/atlas/utilities/command/subcommands/AtlasDiffCommandDescriptionSection.txt
  src/main/resources/org/openstreetmap/atlas/utilities/command/subcommands/AtlasDiffCommandExamplesSection.txt
Labels: Enhancement

#455 Update Validators.isOfSameType() to operate on type T
  src/main/java/org/openstreetmap/atlas/tags/annotations/validation/Validators.java
  src/test/java/org/openstreetmap/atlas/tags/annotations/validation/ValidatorsHasValuesForTestCase.java
Labels: Enhancement

#456 Added meta-data to FeatureChange
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  src/main/java/org/openstreetmap/atlas/geography/atlas/change/FeatureChange.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/change/FeatureChangeMergingHelpers.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/change/serializer/FeatureChangeGeoJsonSerializer.java
  src/test/java/org/openstreetmap/atlas/geography/atlas/change/FeatureChangeMergerTest.java
  src/test/java/org/openstreetmap/atlas/geography/atlas/change/serializer/FeatureChangeGeoJsonSerializerTest.java
  src/test/resources/org/openstreetmap/atlas/geography/atlas/change/serializer/change.json
  src/test/resources/org/openstreetmap/atlas/geography/atlas/change/serializer/serializedAreaFull.json
  src/test/resources/org/openstreetmap/atlas/geography/atlas/change/serializer/serializedAreaNull.json
  src/test/resources/org/openstreetmap/atlas/geography/atlas/change/serializer/serializedAreaRemove.json
  src/test/resources/org/openstreetmap/atlas/geography/atlas/change/serializer/serializedEdgeFull.json
  src/test/resources/org/openstreetmap/atlas/geography/atlas/change/serializer/serializedEdgeNull.json
  src/test/resources/org/openstreetmap/atlas/geography/atlas/change/serializer/serializedEdgeRemove.json
  src/test/resources/org/openstreetmap/atlas/geography/atlas/change/serializer/serializedLineFull.json
  src/test/resources/org/openstreetmap/atlas/geography/atlas/change/serializer/serializedLineNull.json
  src/test/resources/org/openstreetmap/atlas/geography/atlas/change/serializer/serializedLineRemove.json
  src/test/resources/org/openstreetmap/atlas/geography/atlas/change/serializer/serializedNodeFull.json
  src/test/resources/org/openstreetmap/atlas/geography/atlas/change/serializer/serializedNodeNull.json
  src/test/resources/org/openstreetmap/atlas/geography/atlas/change/serializer/serializedNodeRemove.json
  src/test/resources/org/openstreetmap/atlas/geography/atlas/change/serializer/serializedPointFull.json
  src/test/resources/org/openstreetmap/atlas/geography/atlas/change/serializer/serializedPointNull.json
  src/test/resources/org/openstreetmap/atlas/geography/atlas/change/serializer/serializedPointRemove.json
  src/test/resources/org/openstreetmap/atlas/geography/atlas/change/serializer/serializedRelationFull.json
  src/test/resources/org/openstreetmap/atlas/geography/atlas/change/serializer/serializedRelationNull.json
  src/test/resources/org/openstreetmap/atlas/geography/atlas/change/serializer/serializedRelationRemove.json
Labels: New Feature

#458 Show beforeView before afterView in FeatureChange pretty string
  src/main/java/org/openstreetmap/atlas/geography/atlas/change/FeatureChange.java
Labels: Enhancement

#459 Fixed a bug where some FeatureChange merges were too collision-strict
  src/main/java/org/openstreetmap/atlas/geography/atlas/change/FeatureChange.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/change/FeatureChangeMergingHelpers.java
Labels: Bug

#457 Reworked antimeridian handling to allow for both -180 and 180
  src/main/java/org/openstreetmap/atlas/geography/Location.java
  src/main/java/org/openstreetmap/atlas/geography/Longitude.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/multi/MultiAtlasOverlappingNodesFixer.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/packed/PackedAtlas.java
  src/test/java/org/openstreetmap/atlas/geography/LocationTest.java
  src/test/java/org/openstreetmap/atlas/geography/LongitudeTest.java
  src/test/java/org/openstreetmap/atlas/geography/PolyLineTest.java
  src/test/java/org/openstreetmap/atlas/geography/PolygonTest.java
  src/test/java/org/openstreetmap/atlas/geography/SegmentTest.java
  src/test/java/org/openstreetmap/atlas/geography/atlas/AtlasResourceLoaderTest.java
  src/test/java/org/openstreetmap/atlas/geography/atlas/change/ChangeAtlasTest.java
Labels: Data Change, Enhancement

#460 Slicing fix and raw atlas ingest update
  src/integrationTest/java/org/openstreetmap/atlas/geography/atlas/pbf/OsmPbfIngestIntegrationTest.java
  src/integrationTest/java/org/openstreetmap/atlas/geography/atlas/raw/RawAtlasIntegrationTest.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/raw/creation/OsmPbfCounter.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/raw/slicing/RawAtlasPointAndLineSlicer.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/raw/slicing/RawAtlasRelationSlicer.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/raw/slicing/changeset/ChangeSetHandler.java
  src/main/java/org/openstreetmap/atlas/geography/boundary/CountryToShardListing.java
  src/test/java/org/openstreetmap/atlas/geography/atlas/raw/creation/RawAtlasGeneratorTest.java
Labels: Enhancement

#461 Updated FeatureChange prettify output format
  src/main/java/org/openstreetmap/atlas/geography/atlas/change/FeatureChange.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/complete/CompleteArea.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/complete/CompleteEdge.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/complete/CompleteLine.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/complete/CompleteNode.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/complete/CompletePoint.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/complete/CompleteRelation.java
  src/test/java/org/openstreetmap/atlas/geography/atlas/change/TagChangeTest.java
Labels: Enhancement

#464 Added an option name to option mapping
  src/main/java/org/openstreetmap/atlas/utilities/command/parsing/SimpleOptionAndArgumentParser.java
  src/test/java/org/openstreetmap/atlas/utilities/command/SimpleOptionAndArgumentParserTest.java
Labels: Enhancement

#462 Checkstyle RequireThis changed and update was missed
  config/checkstyle/checkstyle.xml
  src/integrationTest/java/org/openstreetmap/atlas/geography/atlas/delta/AtlasDeltaGeoJsonIntegrationTest.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/change/eventhandling/event/EntityChangeEvent.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/change/eventhandling/event/TagChangeEvent.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/complete/CompleteItemType.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/complete/TagChangeDelegate.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/delta/AtlasDeltaGenerator.java
  src/main/java/org/openstreetmap/atlas/geography/converters/PolygonStringFormat.java
  src/main/java/org/openstreetmap/atlas/geography/sharding/DynamicTileSharding.java
  src/main/java/org/openstreetmap/atlas/utilities/collections/OptionalIterable.java
  src/main/java/org/openstreetmap/atlas/utilities/configuration/ConfigurationReader.java
  src/main/java/org/openstreetmap/atlas/utilities/matching/NameMatcher.java
  src/main/java/org/openstreetmap/atlas/utilities/vectortiles/MinimumZoom.java
  src/main/java/org/openstreetmap/atlas/utilities/vectortiles/TippecanoeGeoJsonExtension.java
  src/test/java/org/openstreetmap/atlas/geography/atlas/AtlasTest.java
  src/test/java/org/openstreetmap/atlas/geography/atlas/change/CascadeDeleteTest.java
  src/test/java/org/openstreetmap/atlas/geography/atlas/change/CascadeDeleteTestHelper.java
  src/test/java/org/openstreetmap/atlas/geography/atlas/change/CascadeDeleteTestRule.java
  src/test/java/org/openstreetmap/atlas/geography/atlas/change/MultiCascadeDeleteTest.java
  src/test/java/org/openstreetmap/atlas/geography/atlas/change/MultipleChangeAtlasTest.java
  src/test/java/org/openstreetmap/atlas/geography/atlas/change/TagChangeTestRule.java
  src/test/java/org/openstreetmap/atlas/geography/atlas/change/eventhandling/listener/TestTagChangeListenerImplementation.java
  src/test/java/org/openstreetmap/atlas/geography/atlas/complete/CompleteItemTypeTest.java
  src/test/java/org/openstreetmap/atlas/geography/atlas/items/AtlasEntityTest.java
  src/test/java/org/openstreetmap/atlas/geography/atlas/items/complex/RelationOrAreaToMultiPolygonConverterTest.java
  src/test/java/org/openstreetmap/atlas/geography/atlas/walker/SimpleEdgeWalkerTest.java
  src/test/java/org/openstreetmap/atlas/utilities/matching/NameMatcherTestCase.java
Labels: Fail

#466 Small change to FeatureChange log format
  src/main/java/org/openstreetmap/atlas/geography/atlas/change/FeatureChange.java
Labels: Enhancement

#468 Update area filter to allow in certain piers and footways
  src/main/resources/org/openstreetmap/atlas/geography/atlas/pbf/atlas-area.json
Labels: Data Change, Enhancement

#469 Generate deterministic IDs for CompleteEntities
  src/main/java/org/openstreetmap/atlas/geography/PolyLine.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/complete/CompleteArea.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/complete/CompleteEdge.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/complete/CompleteEntity.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/complete/CompleteLine.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/complete/CompleteNode.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/complete/CompletePoint.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/complete/CompleteRelation.java
  src/main/java/org/openstreetmap/atlas/utilities/identifiers/EntityIdentifierGenerator.java
  src/test/java/org/openstreetmap/atlas/geography/atlas/complete/CompleteAreaTest.java
  src/test/java/org/openstreetmap/atlas/geography/atlas/complete/CompleteEdgeTest.java
  src/test/java/org/openstreetmap/atlas/geography/atlas/complete/CompleteLineTest.java
  src/test/java/org/openstreetmap/atlas/geography/atlas/complete/CompleteNodeTest.java
  src/test/java/org/openstreetmap/atlas/geography/atlas/complete/CompletePointTest.java
  src/test/java/org/openstreetmap/atlas/geography/atlas/complete/CompleteRelationTest.java
  src/test/java/org/openstreetmap/atlas/utilities/identifiers/EntityIdentifierGeneratorTest.java
Labels: New Feature

#472 Checkstyle plugin to check member arrangement
  build.gradle
  dependencies.gradle
  gradle/quality.gradle
  src/main/java/org/openstreetmap/atlas/utilities/checkstyle/ArrangementCheck.java
  src/main/java/org/openstreetmap/atlas/utilities/checkstyle/README.md
  src/main/resources/org/openstreetmap/atlas/utilities/checkstyle/arrangement.txt
  src/test/java/org/openstreetmap/atlas/utilities/checkstyle/ArrangementCheckTest.java
  src/test/resources/org/openstreetmap/atlas/utilities/checkstyle/ArrangementCheckRight.java
  src/test/resources/org/openstreetmap/atlas/utilities/checkstyle/ArrangementCheckWrongField0.java
  src/test/resources/org/openstreetmap/atlas/utilities/checkstyle/ArrangementCheckWrongField1.java
  src/test/resources/org/openstreetmap/atlas/utilities/checkstyle/ArrangementCheckWrongField2.java
  src/test/resources/org/openstreetmap/atlas/utilities/checkstyle/ArrangementCheckWrongInitializerBlock.java
  src/test/resources/org/openstreetmap/atlas/utilities/checkstyle/ArrangementCheckWrongInitializerStaticBlock.java
  src/test/resources/org/openstreetmap/atlas/utilities/checkstyle/ArrangementCheckWrongMethodModifier.java
  src/test/resources/org/openstreetmap/atlas/utilities/checkstyle/ArrangementCheckWrongMethodName.java
  src/test/resources/org/openstreetmap/atlas/utilities/checkstyle/ArrangementCheckWrongMethodVisibility1.java
  src/test/resources/org/openstreetmap/atlas/utilities/checkstyle/ArrangementCheckWrongMethodVisibility2.java
Labels: Huzzah!, New Feature

#471 ComplexRoundabout
  src/main/java/org/openstreetmap/atlas/geography/atlas/items/complex/roundabout/ComplexRoundabout.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/items/complex/roundabout/ComplexRoundaboutFinder.java
  src/test/java/org/openstreetmap/atlas/geography/atlas/items/complex/roundabout/ComplexRoundaboutTest.java
  src/test/java/org/openstreetmap/atlas/geography/atlas/items/complex/roundabout/ComplexRoundaboutTestRule.java
Labels: New Feature

#474 Add CircleCI as build option
  .circleci/config.yml
  README.md
Labels: Duplicate

#475 Reverted issue with country to shard listing
  src/main/java/org/openstreetmap/atlas/geography/boundary/CountryToShardListing.java
Labels: Bug

#467 Updated slicing logic to include fallback to lower precision
  src/main/java/org/openstreetmap/atlas/geography/boundary/CountryBoundaryMap.java
Labels: Enhancement
