Repository osmlab/atlas, pull requests merged in 2019-05, with the labels that each got.

#427 Removed FeatureChange usefulness validation at creation time
  src/main/java/org/openstreetmap/atlas/geography/atlas/change/FeatureChange.java
  src/test/java/org/openstreetmap/atlas/geography/atlas/change/FeatureChangeTest.java
Labels: Enhancement

#428 separate out configuration reader from ComplexWaterEntityFinder
  src/main/java/org/openstreetmap/atlas/geography/atlas/items/complex/islands/ComplexIslandFinder.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/items/complex/waters/ComplexWaterEntityFinder.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/items/complex/waters/WaterConfigurationHandler.java
  src/main/java/org/openstreetmap/atlas/utilities/configuration/ConfiguredFilter.java
Labels: Enhancement

#430 Disable deserialization of corrupted Atlas resources
  src/main/java/org/openstreetmap/atlas/geography/atlas/packed/PackedAtlasSerializer.java
Labels: Bug

#433 CompleteEntity now supports generic geometry updates
  src/main/java/org/openstreetmap/atlas/geography/Location.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/complete/CompleteArea.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/complete/CompleteEdge.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/complete/CompleteEntity.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/complete/CompleteLine.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/complete/CompleteNode.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/complete/CompletePoint.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/complete/CompleteRelation.java
  src/test/java/org/openstreetmap/atlas/geography/atlas/complete/CompleteAreaTest.java
  src/test/java/org/openstreetmap/atlas/geography/atlas/complete/CompleteEdgeTest.java
  src/test/java/org/openstreetmap/atlas/geography/atlas/complete/CompleteLineTest.java
  src/test/java/org/openstreetmap/atlas/geography/atlas/complete/CompleteNodeTest.java
  src/test/java/org/openstreetmap/atlas/geography/atlas/complete/CompletePointTest.java
Labels: Enhancement

#432 A test of cascading nature of delete for all atlas entities
  src/main/java/org/openstreetmap/atlas/geography/atlas/complete/CompleteItemType.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/items/ConnectedEdgeType.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/items/ItemType.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/items/Node.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/items/Relation.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/items/RelationMemberList.java
  src/test/java/org/openstreetmap/atlas/geography/atlas/change/CascadeDeleteTest.java
  src/test/java/org/openstreetmap/atlas/geography/atlas/change/CascadeDeleteTestHelper.java
  src/test/java/org/openstreetmap/atlas/geography/atlas/change/CascadeDeleteTestRule.java
Labels: Testing

#434 Reworked sectioning logic
  src/main/java/org/openstreetmap/atlas/geography/atlas/raw/sectioning/WaySectionProcessor.java
  src/main/resources/org/openstreetmap/atlas/geography/atlas/pbf/atlas-area.json
  src/test/java/org/openstreetmap/atlas/geography/atlas/raw/sectioning/WaySectionProcessorTest.java
  src/test/java/org/openstreetmap/atlas/geography/atlas/raw/sectioning/WaySectionProcessorTestRule.java
  src/test/resources/org/openstreetmap/atlas/geography/atlas/raw/sectioning/pedestrianRing.atlas.txt
Labels: Data Change, Enhancement

#437 Added a new CompleteEntity#shallowFrom API
  src/main/java/org/openstreetmap/atlas/geography/atlas/complete/CompleteEntity.java
Labels: Enhancement

#436 Remove MultiAtlasBorderFixer
  config/log4j/log4j.properties
  src/integrationTest/java/org/openstreetmap/atlas/geography/atlas/dynamic/DynamicAtlasIntegrationTest.java
  src/integrationTest/java/org/openstreetmap/atlas/geography/atlas/multi/MultiAtlasBorderFixerIntegrationTest.java
  src/integrationTest/java/org/openstreetmap/atlas/geography/atlas/multi/MultiAtlasIntegrationTest.java
  src/integrationTest/java/org/openstreetmap/atlas/geography/atlas/multi/MultiAtlasIntegrationTestRule.java
  src/integrationTest/resources/org/openstreetmap/atlas/geography/atlas/dynamic/DMA_9-168-233.atlas.txt.gz
  src/integrationTest/resources/org/openstreetmap/atlas/geography/atlas/dynamic/DMA_9-168-234.atlas.txt.gz
  src/integrationTest/resources/org/openstreetmap/atlas/geography/atlas/multi/DEU_11-1084-708.atlas.txt.gz
  src/integrationTest/resources/org/openstreetmap/atlas/geography/atlas/multi/DEU_11-1084-709.atlas.txt.gz
  src/main/java/org/openstreetmap/atlas/geography/atlas/multi/MultiAtlas.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/multi/MultiAtlasBorderFixer.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/multi/MultiEdge.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/multi/MultiNode.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/multi/MultiRelation.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/multi/SubAreaList.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/multi/SubEdgeList.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/multi/SubLineList.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/multi/SubNodeList.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/multi/SubPointList.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/multi/SubRelationList.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/multi/TemporaryEdge.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/multi/TemporaryOrderedLocation.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/multi/TemporaryOrderedNode.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/multi/TemporaryRelation.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/multi/TemporaryRelationMember.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/multi/TemporaryRoad.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/raw/sectioning/WaySectionChangeSet.java
  src/test/java/org/openstreetmap/atlas/geography/atlas/dynamic/DynamicAtlasFilteredEntitiesTest.java
  src/test/java/org/openstreetmap/atlas/geography/atlas/dynamic/DynamicAtlasTest.java
  src/test/java/org/openstreetmap/atlas/geography/atlas/dynamic/rules/DynamicAtlasTestRule.java
  src/test/java/org/openstreetmap/atlas/geography/atlas/multi/MissingMultiEntityRelationTest.java
  src/test/java/org/openstreetmap/atlas/geography/atlas/multi/MultiAtlasBorderFixerTest.java
  src/test/java/org/openstreetmap/atlas/geography/atlas/multi/MultiAtlasBorderFixerTestRule.java
  src/test/java/org/openstreetmap/atlas/geography/atlas/multi/MultiAtlasOverlappingNodesFixerTest.java
  src/test/java/org/openstreetmap/atlas/geography/atlas/multi/MultiAtlasOverlappingNodesFixerTestRule.java
  src/test/java/org/openstreetmap/atlas/geography/atlas/multi/MultiAtlasTest.java
  src/test/resources/log4j.properties
Labels: Deprecation, Enhancement, Huzzah!, Performance

#441 Dynamic tile sharding equals function
  src/main/java/org/openstreetmap/atlas/geography/sharding/DynamicTileSharding.java
  src/test/java/org/openstreetmap/atlas/geography/sharding/DynamicTileShardingTest.java
  src/test/resources/org/openstreetmap/atlas/geography/sharding/testDynamicSharding.txt
  src/test/resources/org/openstreetmap/atlas/geography/sharding/testDynamicShardingChildOrdering.txt
  src/test/resources/org/openstreetmap/atlas/geography/sharding/testDynamicShardingMissingChildren.txt
Labels: Enhancement

#444 Fixed winding reversing for some areas post-slicing
  src/main/java/org/openstreetmap/atlas/geography/atlas/raw/slicing/RawAtlasPointAndLineSlicer.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/raw/slicing/changeset/SimpleChangeSet.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/raw/slicing/changeset/SimpleChangeSetHandler.java
  src/test/java/org/openstreetmap/atlas/geography/atlas/raw/slicing/LineAndPointSlicingTest.java
  src/test/java/org/openstreetmap/atlas/geography/atlas/raw/slicing/LineAndPointSlicingTestRule.java
Labels: Data Change, Enhancement

#446 Atlas diff cascade test
  src/main/java/org/openstreetmap/atlas/geography/atlas/change/AtlasEntityKey.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/change/Change.java
  src/test/java/org/openstreetmap/atlas/geography/atlas/change/MultiCascadeDeleteTest.java
  src/test/java/org/openstreetmap/atlas/geography/atlas/change/MultiCascadeDeleteTestRule.java
Labels: Enhancement

#447 Added some CompleteEntity and FeatureChange pretty print options
  src/main/java/org/openstreetmap/atlas/geography/atlas/change/FeatureChange.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/complete/CompleteArea.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/complete/CompleteEdge.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/complete/CompleteEntity.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/complete/CompleteLine.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/complete/CompleteNode.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/complete/CompletePoint.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/complete/CompleteRelation.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/complete/PrettifyStringFormat.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/items/AtlasEntity.java
Labels: Enhancement

#445 Pbf2Atlas command
  src/main/java/org/openstreetmap/atlas/geography/converters/WkMultiPolygonConverter.java
  src/main/java/org/openstreetmap/atlas/geography/converters/WkbMultiPolygonConverter.java
  src/main/java/org/openstreetmap/atlas/geography/converters/WktMultiPolygonConverter.java
  src/main/java/org/openstreetmap/atlas/geography/converters/jts/JtsPolygonToMultiPolygonConverter.java
  src/main/java/org/openstreetmap/atlas/utilities/command/subcommands/PbfToAtlasCommand.java
  src/main/resources/org/openstreetmap/atlas/utilities/command/subcommands/PbfToAtlasCommandExamplesSection.txt
  src/main/resources/org/openstreetmap/atlas/utilities/command/subcommands/PbfToAtlasDescriptionSection.txt
  src/main/resources/org/openstreetmap/atlas/utilities/command/subcommands/PbfToRawAtlasCommandExamplesSection.txt
  src/test/java/org/openstreetmap/atlas/geography/converters/WkBPolygonConverterTest.java
  src/test/java/org/openstreetmap/atlas/geography/converters/WkbPolygonConverterTest.java
  src/test/java/org/openstreetmap/atlas/geography/converters/WktMultiPolygonConverterTest.java
Labels: New Feature

#449 Pbf2AtlasCommand Test
  src/main/java/org/openstreetmap/atlas/utilities/command/subcommands/PbfToAtlasCommand.java
  src/test/java/org/openstreetmap/atlas/utilities/command/subcommands/PbfToAtlasCommandTest.java
  src/test/resources/org/openstreetmap/atlas/utilities/command/subcommands/testPbf2Atlas.josm.osm
Labels: Enhancement, Fail

#452 Save FeatureChanges as ldgeojson by default
  src/main/java/org/openstreetmap/atlas/geography/atlas/change/FeatureChange.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/change/serializer/FeatureChangeGeoJsonSerializer.java
  src/test/java/org/openstreetmap/atlas/geography/atlas/change/serializer/FeatureChangeGeoJsonSerializerTest.java
Labels: New Feature
