Repository osmlab/atlas, pull requests merged in 2019-03, with the labels that each got.

#370 Name tag exposed directly from AtlasEntity
  src/main/java/org/openstreetmap/atlas/geography/atlas/items/AtlasEntity.java
  src/test/java/org/openstreetmap/atlas/geography/atlas/items/AreaEntityTestRule.java
  src/test/java/org/openstreetmap/atlas/geography/atlas/items/AtlasEntityTest.java
Labels: Enhancement

#369 Atlas GeoJson Interfaces
  src/main/java/org/openstreetmap/atlas/geography/GeojsonPrintable.java
  src/main/java/org/openstreetmap/atlas/geography/GeometryPrintable.java
  src/main/java/org/openstreetmap/atlas/geography/Location.java
  src/main/java/org/openstreetmap/atlas/geography/MultiPolyLine.java
  src/main/java/org/openstreetmap/atlas/geography/MultiPolygon.java
  src/main/java/org/openstreetmap/atlas/geography/PolyLine.java
  src/main/java/org/openstreetmap/atlas/geography/Polygon.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/Atlas.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/AtlasMetaData.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/BareAtlas.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/builder/AtlasSize.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/change/serializer/FeatureChangeGeoJsonSerializer.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/command/AtlasGeoJSONSubCommand.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/complete/EmptyAtlas.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/items/Area.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/items/AtlasEntity.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/items/Edge.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/items/LineItem.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/items/LocationItem.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/items/Node.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/items/Relation.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/items/RelationMember.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/items/complex/boundaries/ComplexBoundary.java
  src/main/java/org/openstreetmap/atlas/geography/converters/WkbMultiPolyLineConverter.java
  src/main/java/org/openstreetmap/atlas/geography/geojson/GeoJson.java
  src/main/java/org/openstreetmap/atlas/geography/geojson/GeoJsonBuilder.java
  src/main/java/org/openstreetmap/atlas/geography/geojson/GeoJsonCollection.java
  src/main/java/org/openstreetmap/atlas/geography/geojson/GeoJsonConstants.java
  src/main/java/org/openstreetmap/atlas/geography/geojson/GeoJsonFeature.java
  src/main/java/org/openstreetmap/atlas/geography/geojson/GeoJsonFeatureCollection.java
  src/main/java/org/openstreetmap/atlas/geography/geojson/GeoJsonGeometry.java
  src/main/java/org/openstreetmap/atlas/geography/geojson/GeoJsonProperties.java
  src/main/java/org/openstreetmap/atlas/geography/geojson/GeoJsonType.java
  src/main/java/org/openstreetmap/atlas/geography/geojson/GeoJsonUtils.java
  src/main/java/org/openstreetmap/atlas/geography/geojson/GeojsonGeometryCollection.java
  src/main/java/org/openstreetmap/atlas/geography/sharding/SlippyTile.java
  src/main/java/org/openstreetmap/atlas/streaming/readers/json/deserializers/LocatedDeserializer.java
  src/test/java/org/openstreetmap/atlas/geography/MultiPolyLineTest.java
  src/test/java/org/openstreetmap/atlas/geography/geojson/GeoJsonBuilderTest.java
  src/test/java/org/openstreetmap/atlas/geography/geojson/GeoJsonUtilsTest.java
  src/test/java/org/openstreetmap/atlas/streaming/writers/JsonWriterTest.java
  src/test/java/org/openstreetmap/atlas/utilities/filters/AtlasEntityPolygonsFilterTest.java
  src/test/resources/org/openstreetmap/atlas/geography/atlas/line-delimited-geojson.txt
Labels: Enhancement

#374 JDK11 Followup
  .travis.yml
  dependencies.gradle
Labels: Enhancement

#343 Subatlas command now supports predicate slicing
  build.gradle
  dependencies.gradle
  src/main/java/org/openstreetmap/atlas/utilities/command/subcommands/IdentifierSearchCommand.java
  src/main/java/org/openstreetmap/atlas/utilities/command/subcommands/SubAtlasCommand.java
  src/main/java/org/openstreetmap/atlas/utilities/conversion/StringToPredicateConverter.java
  src/main/resources/org/openstreetmap/atlas/utilities/command/subcommands/SubAtlasCommandDescriptionSection.txt
  src/main/resources/org/openstreetmap/atlas/utilities/command/subcommands/SubAtlasCommandExamplesSection.txt
  src/main/resources/org/openstreetmap/atlas/utilities/command/subcommands/SubAtlasCommandPredicateSection.txt
  src/test/java/org/openstreetmap/atlas/utilities/command/subcommands/SubAtlasCommandTest.java
  src/test/java/org/openstreetmap/atlas/utilities/conversion/StringToPredicateConverterTest.java
  src/test/java/org/openstreetmap/atlas/utilities/conversion/StringToPredicateConverterTestRule.java
Labels: Enhancement

#375 Entities by ids
  src/main/java/org/openstreetmap/atlas/geography/atlas/Atlas.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/items/ItemType.java
  src/test/java/org/openstreetmap/atlas/geography/atlas/AtlasTest.java
  src/test/java/org/openstreetmap/atlas/geography/atlas/AtlasTestRule.java
Labels: New Feature

#376 Added in SilkCut with predicate and used that in relation slicing
  src/main/java/org/openstreetmap/atlas/geography/atlas/BareAtlas.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/raw/slicing/RawAtlasRelationSlicer.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/sub/SubAtlasCreator.java
  src/test/java/org/openstreetmap/atlas/geography/atlas/SubAtlasTest.java
Labels: Enhancement

#377 Upgrade to Gradle 5
  README.md
  build.gradle
  config/checkstyle/checkstyle.xml
  dependencies.gradle
  gradle/quality.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  src/integrationTest/java/org/openstreetmap/atlas/geography/PolygonPerformanceTest.java
  src/integrationTest/java/org/openstreetmap/atlas/geography/atlas/multi/MultiAtlasBorderFixerIntegrationTest.java
  src/integrationTest/java/org/openstreetmap/atlas/geography/atlas/raw/RawAtlasIntegrationTest.java
  src/main/java/org/openstreetmap/atlas/event/README.md
  src/main/java/org/openstreetmap/atlas/exception/CoreException.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/AtlasResourceLoader.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/builder/store/AtlasPrimitiveRouteIdentifier.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/command/AtlasFeatureCountsSubCommand.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/items/complex/aoi/ComplexAreaOfInterest.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/items/complex/bignode/BigNodeFinder.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/items/complex/waters/ComplexWaterEntityFinder.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/multi/MultiAtlasBorderFixer.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/multi/MultiNode.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/raw/creation/README.md
  src/main/java/org/openstreetmap/atlas/geography/atlas/raw/sectioning/WaySectionProcessor.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/statistics/coverage/poi/SimpleCoverage.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/walker/OsmWayWalker.java
  src/main/java/org/openstreetmap/atlas/proto/adapters/ProtoLongToLongMapAdapter.java
  src/main/java/org/openstreetmap/atlas/proto/adapters/ProtoLongToLongMultiMapAdapter.java
  src/main/java/org/openstreetmap/atlas/proto/builder/ProtoAtlasBuilder.java
  src/main/java/org/openstreetmap/atlas/tags/annotations/validation/TagDocumenter.java
  src/main/java/org/openstreetmap/atlas/tags/names/BulkNameFinder.java
  src/main/java/org/openstreetmap/atlas/utilities/archive/Archiver.java
  src/main/java/org/openstreetmap/atlas/utilities/caching/README.md
  src/main/java/org/openstreetmap/atlas/utilities/collections/EnumSetCollector.java
  src/main/java/org/openstreetmap/atlas/utilities/collections/ImmutableListCollector.java
  src/main/java/org/openstreetmap/atlas/utilities/collections/MultiIterable.java
  src/main/java/org/openstreetmap/atlas/utilities/collections/UnmodifiableSortedMapCollector.java
  src/main/java/org/openstreetmap/atlas/utilities/collections/UnmodifiableSortedSetCollector.java
  src/main/java/org/openstreetmap/atlas/utilities/filters/AtlasEntityPolygonsFilter.java
  src/main/java/org/openstreetmap/atlas/utilities/threads/Pool.java
  src/test/java/org/openstreetmap/atlas/geography/MultiPolyLineTest.java
  src/test/java/org/openstreetmap/atlas/geography/PolyLineCoveringPolygonTestRule.java
  src/test/java/org/openstreetmap/atlas/geography/PolyLineTest.java
  src/test/java/org/openstreetmap/atlas/geography/PolygonTest.java
  src/test/java/org/openstreetmap/atlas/geography/atlas/SubAtlasTest.java
  src/test/java/org/openstreetmap/atlas/geography/atlas/change/ChangeAtlasTest.java
  src/test/java/org/openstreetmap/atlas/geography/atlas/change/TagChangeTest.java
  src/test/java/org/openstreetmap/atlas/geography/atlas/routing/RoutingTestRule.java
  src/test/java/org/openstreetmap/atlas/geography/atlas/statistics/coverage/poi/CountCoverageTestCaseRule.java
Labels: Enhancement

#373 Segment intersection bug fix
  src/main/java/org/openstreetmap/atlas/geography/Segment.java
  src/test/java/org/openstreetmap/atlas/geography/SegmentTest.java
Labels: Bug

#380 Allowed additional imports for predicates
  src/main/java/org/openstreetmap/atlas/utilities/command/subcommands/SubAtlasCommand.java
  src/main/java/org/openstreetmap/atlas/utilities/conversion/StringToPredicateConverter.java
  src/test/java/org/openstreetmap/atlas/utilities/conversion/StringToPredicateConverterTest.java
Labels: Enhancement

#381 Improved dynamic slicing performance
  src/main/java/org/openstreetmap/atlas/geography/atlas/raw/slicing/RawAtlasCountrySlicer.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/raw/slicing/changeset/RelationChangeSetHandler.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/sub/SubAtlasCreator.java
Labels: Enhancement

#382 Retrieve DAG process groups
  src/main/java/org/openstreetmap/atlas/utilities/graphs/DirectedAcyclicGraph.java
  src/test/java/org/openstreetmap/atlas/utilities/graphs/DirectedAcyclicGraphTest.java
Labels: New Feature

#383 Make AtlasChangeGenerator serializable
  src/main/java/org/openstreetmap/atlas/geography/atlas/change/AtlasChangeGenerator.java
  src/test/java/org/openstreetmap/atlas/geography/atlas/change/AtlasChangeGeneratorAddTurnRestrictions.java
  src/test/java/org/openstreetmap/atlas/geography/atlas/change/AtlasChangeGeneratorRemoveReverseEdges.java
  src/test/java/org/openstreetmap/atlas/geography/atlas/change/AtlasChangeGeneratorSplitRoundabout.java
Labels: Enhancement

#384 Override towkb
  src/main/java/org/openstreetmap/atlas/geography/Polygon.java
  src/test/java/org/openstreetmap/atlas/geography/PolygonTest.java
Labels: Bug

#386 Allow for ChangeAtlas to have no source and node bound expansion
  src/main/java/org/openstreetmap/atlas/geography/atlas/change/AtlasChangeGenerator.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/change/Change.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/change/ChangeAtlas.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/change/FeatureChange.java
  src/test/java/org/openstreetmap/atlas/geography/atlas/change/AtlasChangeGeneratorTest.java
  src/test/java/org/openstreetmap/atlas/geography/atlas/change/AtlasChangeGeneratorTestRule.java
  src/test/java/org/openstreetmap/atlas/geography/atlas/change/ChangeAtlasTest.java
  src/test/java/org/openstreetmap/atlas/geography/atlas/change/FeatureChangeTest.java
  src/test/resources/org/openstreetmap/atlas/geography/atlas/change/nodeBoundsExpansionAtlas.josm.osm
Labels: New Feature

#388 Name a ChangeAtlas made only of changes
  src/main/java/org/openstreetmap/atlas/geography/atlas/change/ChangeAtlas.java
Labels: New Feature

#385 Add a command that takes a JOSM OSM file and produces an OSM file
  src/main/java/org/openstreetmap/atlas/utilities/command/subcommands/OsmFileParserCommand.java
  src/main/resources/org/openstreetmap/atlas/utilities/command/subcommands/OsmFileParserCommandDescriptionSection.txt
  src/main/resources/org/openstreetmap/atlas/utilities/command/subcommands/OsmFileParserCommandExamplesSection.txt
Labels: New Feature

#391 utilities.configuration: Sonar and warnings cleanup
  src/main/java/org/openstreetmap/atlas/utilities/configuration/Configurable.java
  src/main/java/org/openstreetmap/atlas/utilities/configuration/Configuration.java
  src/main/java/org/openstreetmap/atlas/utilities/configuration/ConfigurationDeserializer.java
  src/main/java/org/openstreetmap/atlas/utilities/configuration/MergedConfiguration.java
  src/main/java/org/openstreetmap/atlas/utilities/configuration/StandardConfiguration.java
  src/test/java/org/openstreetmap/atlas/utilities/configuration/MergedConfigurationTest.java
  src/test/java/org/openstreetmap/atlas/utilities/configuration/StandardConfigurationTest.java
Labels: Enhancement

#394 Fix source-sink bug with DAG processGroups
  src/main/java/org/openstreetmap/atlas/utilities/graphs/DirectedAcyclicGraph.java
  src/test/java/org/openstreetmap/atlas/utilities/graphs/DirectedAcyclicGraphTest.java
Labels: Bug

#396 Improved performance for WaySectionProcessor
  src/main/java/org/openstreetmap/atlas/geography/atlas/raw/sectioning/WaySectionProcessor.java
Labels: Enhancement

#389 A few slicing changes
  src/integrationTest/java/org/openstreetmap/atlas/geography/atlas/AtlasIntegrationTest.java
  src/integrationTest/java/org/openstreetmap/atlas/geography/atlas/pbf/OsmPbfIngestIntegrationTest.java
  src/integrationTest/java/org/openstreetmap/atlas/geography/atlas/raw/RawAtlasIntegrationTest.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/AbstractAtlas.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/command/OsmPbfToAtlasSubCommand.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/converters/AtlasDebugTool.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/pbf/slicing/identifier/AbstractIdentifierFactory.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/pbf/slicing/identifier/CountrySlicingIdentifierFactory.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/pbf/slicing/identifier/PointIdentifierFactory.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/pbf/slicing/identifier/ReverseIdentifierFactory.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/raw/slicing/RawAtlasCountrySlicer.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/raw/slicing/RawAtlasPointAndLineSlicer.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/raw/slicing/RawAtlasRelationSlicer.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/raw/slicing/RawAtlasSlicer.java
  src/test/java/org/openstreetmap/atlas/geography/atlas/pbf/OsmPbfIngestTest.java
  src/test/java/org/openstreetmap/atlas/geography/atlas/raw/RawAtlasTest.java
  src/test/java/org/openstreetmap/atlas/geography/atlas/raw/slicing/InvalidMultipolygonSlicingTest.java
  src/test/java/org/openstreetmap/atlas/geography/atlas/raw/slicing/LineAndPointSlicingTest.java
  src/test/java/org/openstreetmap/atlas/geography/atlas/raw/slicing/LineAndPointSlicingTestRule.java
  src/test/java/org/openstreetmap/atlas/geography/atlas/raw/slicing/RelationSlicingTest.java
  src/test/java/org/openstreetmap/atlas/geography/atlas/raw/slicing/RelationSlicingTestRule.java
Labels: Data Change, Enhancement

#399 Throw exception when groovy predicate is unparseable
  src/main/java/org/openstreetmap/atlas/utilities/conversion/StringToPredicateConverter.java
Labels: Breaking Change, Enhancement

#393 FeatureChange now supports a beforeView for more robust merging
  config/checkstyle/suppressions.xml
  src/main/java/org/openstreetmap/atlas/geography/PolyLine.java
  src/main/java/org/openstreetmap/atlas/geography/Polygon.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/builder/RelationBean.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/change/AtlasChangeGenerator.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/change/ChangeAtlas.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/change/FeatureChange.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/change/FeatureChangeMergeGroup.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/change/FeatureChangeMergingHelpers.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/change/MemberMergeStrategies.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/change/MergedMemberBean.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/change/diff/AtlasDiffHelper.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/change/serializer/FeatureChangeGeoJsonSerializer.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/change/validators/ChangeValidator.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/complete/CompleteArea.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/complete/CompleteEdge.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/complete/CompleteEntity.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/complete/CompleteLine.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/complete/CompleteLineItem.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/complete/CompleteNode.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/complete/CompletePoint.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/complete/CompleteRelation.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/complete/EmptyAtlas.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/items/Relation.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/items/RelationMemberList.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/validators/FeatureChangeUsefulnessValidator.java
  src/main/java/org/openstreetmap/atlas/utilities/collections/Sets.java
  src/main/java/org/openstreetmap/atlas/utilities/function/TernaryFunction.java
  src/main/java/org/openstreetmap/atlas/utilities/function/TernaryOperator.java
  src/test/java/org/openstreetmap/atlas/geography/atlas/change/AbstractChangeTest.java
  src/test/java/org/openstreetmap/atlas/geography/atlas/change/AtlasChangeGeneratorRemoveReverseEdges.java
  src/test/java/org/openstreetmap/atlas/geography/atlas/change/AtlasChangeGeneratorSplitRoundabout.java
  src/test/java/org/openstreetmap/atlas/geography/atlas/change/ChangeBuilderTest.java
  src/test/java/org/openstreetmap/atlas/geography/atlas/change/ChangeTest.java
  src/test/java/org/openstreetmap/atlas/geography/atlas/change/FeatureChangeMergerTest.java
  src/test/java/org/openstreetmap/atlas/geography/atlas/change/FeatureChangeTest.java
  src/test/java/org/openstreetmap/atlas/geography/atlas/change/MemberMergeStrategiesTest.java
  src/test/java/org/openstreetmap/atlas/geography/atlas/change/MultipleChangeAtlasTest.java
  src/test/java/org/openstreetmap/atlas/geography/atlas/change/diff/AtlasDiffTest.java
  src/test/java/org/openstreetmap/atlas/geography/atlas/change/serializer/ChangeGeoJsonSerializerTest.java
  src/test/java/org/openstreetmap/atlas/geography/atlas/change/serializer/FeatureChangeGeoJsonSerializerTest.java
  src/test/java/org/openstreetmap/atlas/geography/atlas/change/validators/ChangeValidatorTest.java
  src/test/java/org/openstreetmap/atlas/geography/atlas/complete/CompleteAreaTest.java
  src/test/java/org/openstreetmap/atlas/geography/atlas/complete/CompleteEdgeTest.java
  src/test/java/org/openstreetmap/atlas/geography/atlas/complete/CompleteLineTest.java
  src/test/java/org/openstreetmap/atlas/geography/atlas/complete/CompleteNodeTest.java
  src/test/java/org/openstreetmap/atlas/geography/atlas/complete/CompletePointTest.java
  src/test/java/org/openstreetmap/atlas/geography/atlas/complete/CompleteRelationTest.java
Labels: Enhancement

#397 Fixed Sonar issue with PackedAtlas synchronization
  src/main/java/org/openstreetmap/atlas/geography/atlas/packed/PackedAtlas.java
Labels: Enhancement
