Repository osmlab/atlas, pull requests merged in 2019-02, with the labels that each got.

#334 Refactor in MultiPolygon functionality
  src/main/java/org/openstreetmap/atlas/geography/MultiPolygon.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/AbstractAtlas.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/Atlas.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/BareAtlas.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/complete/EmptyAtlas.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/dynamic/DynamicAtlas.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/items/Relation.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/sub/SubAtlas.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/sub/SubAtlasCreator.java
  src/test/java/org/openstreetmap/atlas/geography/atlas/SubAtlasTest.java
Labels: Enhancement

#337 use UUID as Atlas identifier to fix related serialization issue
  src/main/java/org/openstreetmap/atlas/geography/atlas/Atlas.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/BareAtlas.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/complete/EmptyAtlas.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/multi/MultiAtlasBorderFixer.java
  src/test/java/org/openstreetmap/atlas/geography/atlas/AtlasResourceLoaderTest.java
Labels: Breaking Change, Enhancement

#338 MultiPolygon Inner Ring Mapping Bug
  src/main/java/org/openstreetmap/atlas/geography/atlas/items/complex/RelationOrAreaToMultiPolygonConverter.java
  src/test/java/org/openstreetmap/atlas/geography/atlas/items/complex/RelationOrAreaToMultiPolygonConverterTest.java
  src/test/java/org/openstreetmap/atlas/geography/atlas/items/complex/RelationOrAreaToMultiPolygonConverterTestRule.java
  src/test/resources/org/openstreetmap/atlas/geography/atlas/items/complex/InnerOuterMultiPolygon.osm
Labels: Bug, Data Change

#329 PyAtlas: Added a polyline length method
  pyatlas/pyatlas/atlas_entities.py
  pyatlas/pyatlas/geometry.py
  pyatlas/unit_tests/test_polyline_polygon.py
Labels: New Feature

#335 Located fully within
  src/main/java/org/openstreetmap/atlas/geography/Located.java
  src/main/java/org/openstreetmap/atlas/geography/Location.java
  src/main/java/org/openstreetmap/atlas/geography/PolyLine.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/items/Area.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/items/LineItem.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/items/LocationItem.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/items/Relation.java
  src/test/java/org/openstreetmap/atlas/geography/atlas/items/ContainableTestRule.java
  src/test/java/org/openstreetmap/atlas/geography/atlas/items/WithinTest.java
Labels: New Feature

#336 More IsoCountry functionality
  src/main/java/org/openstreetmap/atlas/locale/IsoCountry.java
  src/main/java/org/openstreetmap/atlas/locale/IsoCountryFuzzyMatcher.java
  src/main/java/org/openstreetmap/atlas/utilities/command/parsing/exceptions/UnknownOptionException.java
  src/test/java/org/openstreetmap/atlas/locale/IsoCountryFuzzyMatcherTest.java
  src/test/java/org/openstreetmap/atlas/locale/IsoCountryTest.java
Labels: Enhancement

#339 Deprecated a constructor in InputStreamResource
  src/main/java/org/openstreetmap/atlas/streaming/resource/InputStreamResource.java
Labels: Deprecation

#342 Add SyntheticDuplicateOsmNodeTag to AtlasTag
  src/main/java/org/openstreetmap/atlas/tags/AtlasTag.java
Labels: Bug

#340 Added some additional commands
  dependencies.gradle
  src/main/java/org/openstreetmap/atlas/streaming/resource/File.java
  src/main/java/org/openstreetmap/atlas/utilities/command/AtlasShellToolsException.java
  src/main/java/org/openstreetmap/atlas/utilities/command/abstractcommand/AbstractAtlasShellToolsCommand.java
  src/main/java/org/openstreetmap/atlas/utilities/command/subcommands/ConcatenateAtlasCommand.java
  src/main/java/org/openstreetmap/atlas/utilities/command/subcommands/IdentifierSearchCommand.java
  src/main/java/org/openstreetmap/atlas/utilities/command/subcommands/IsoCountryCodeCommand.java
  src/main/java/org/openstreetmap/atlas/utilities/command/subcommands/JavaToProtoSerializationCommand.java
  src/main/java/org/openstreetmap/atlas/utilities/command/subcommands/PackedToTextAtlasCommand.java
  src/main/java/org/openstreetmap/atlas/utilities/command/subcommands/ShardToBoundsCommand.java
  src/main/java/org/openstreetmap/atlas/utilities/command/subcommands/SubAtlasCommand.java
  src/main/java/org/openstreetmap/atlas/utilities/command/subcommands/templates/AtlasLoaderCommand.java
  src/main/java/org/openstreetmap/atlas/utilities/command/subcommands/templates/MultipleOutputCommand.java
  src/main/java/org/openstreetmap/atlas/utilities/command/subcommands/templates/VariadicAtlasLoaderCommand.java
  src/main/resources/org/openstreetmap/atlas/utilities/command/subcommands/ConcatenateAtlasCommandDescriptionSection.txt
  src/main/resources/org/openstreetmap/atlas/utilities/command/subcommands/ConcatenateAtlasCommandExamplesSection.txt
  src/main/resources/org/openstreetmap/atlas/utilities/command/subcommands/IdentifierSearchCommandDescriptionSection.txt
  src/main/resources/org/openstreetmap/atlas/utilities/command/subcommands/IdentifierSearchCommandExamplesSection.txt
  src/main/resources/org/openstreetmap/atlas/utilities/command/subcommands/IsoCountryCodeCommandDescriptionSection.txt
  src/main/resources/org/openstreetmap/atlas/utilities/command/subcommands/IsoCountryCodeCommandExamplesSection.txt
  src/main/resources/org/openstreetmap/atlas/utilities/command/subcommands/templates/AtlasLoaderCommandLoaderSection.txt
  src/main/resources/org/openstreetmap/atlas/utilities/command/subcommands/templates/AtlasLoaderCommandSection.txt
  src/main/resources/org/openstreetmap/atlas/utilities/command/subcommands/templates/MultipleOutputCommandSection.txt
Labels: New Feature

#345 Fixed some inconsistent error messages in toolset.
  atlas-shell-tools/scripts/atlas-config
Labels: Enhancement

#348 Improvements in ChangeBuilder and Change classes.
  src/main/java/org/openstreetmap/atlas/geography/atlas/change/Change.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/change/ChangeBuilder.java
  src/test/java/org/openstreetmap/atlas/geography/atlas/change/ChangeBuilderTest.java
  src/test/java/org/openstreetmap/atlas/geography/atlas/change/ChangeTest.java
Labels: Enhancement

#346 Support YAML formatted config files
  build.gradle
  dependencies.gradle
  src/main/java/org/openstreetmap/atlas/utilities/configuration/StandardConfiguration.java
  src/test/java/org/openstreetmap/atlas/utilities/configuration/MergedConfigurationTest.java
  src/test/java/org/openstreetmap/atlas/utilities/configuration/StandardConfigurationTest.java
  src/test/resources/org/openstreetmap/atlas/utilities/configuration/application.yml
  src/test/resources/org/openstreetmap/atlas/utilities/configuration/development.yml
  src/test/resources/org/openstreetmap/atlas/utilities/configuration/developmentOverriding.yml
  src/test/resources/org/openstreetmap/atlas/utilities/configuration/feature.yml
  src/test/resources/org/openstreetmap/atlas/utilities/configuration/keywordOverridingApplication.yml
  src/test/resources/org/openstreetmap/atlas/utilities/configuration/yaml_dot_compressed.yml
  src/test/resources/org/openstreetmap/atlas/utilities/configuration/yaml_dot_expanded.yml
Labels: Enhancement, New Feature

#341 Dynamic slicing for relations
  src/integrationTest/java/org/openstreetmap/atlas/geography/atlas/pbf/OsmPbfIngestIntegrationTest.java
  src/integrationTest/java/org/openstreetmap/atlas/geography/atlas/pbf/slicing/WaySectionProcessorIntegrationTest.java
  src/integrationTest/java/org/openstreetmap/atlas/geography/atlas/raw/RawAtlasIntegrationTest.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/BareAtlas.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/items/complex/waters/ComplexWaterEntityFinder.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/items/complex/waters/WaterType.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/items/complex/waters/handler/SeaHandler.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/pbf/slicing/identifier/PointIdentifierFactory.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/raw/slicing/RawAtlasCountrySlicer.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/raw/slicing/RawAtlasPointAndLineSlicer.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/raw/slicing/RawAtlasRelationSlicer.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/raw/slicing/RawAtlasSlicer.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/sub/AtlasCutType.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/sub/SubAtlas.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/sub/SubAtlasCreator.java
  src/main/java/org/openstreetmap/atlas/tags/WaterTag.java
  src/main/resources/org/openstreetmap/atlas/geography/atlas/pbf/osm-pbf-relation.json
  src/main/resources/org/openstreetmap/atlas/geography/atlas/pbf/osm-pbf-way.json
  src/main/resources/org/openstreetmap/atlas/geography/atlas/raw/slicing/dynamic-relation-tag-filter.json
  src/test/java/org/openstreetmap/atlas/geography/atlas/SubAtlasTest.java
  src/test/java/org/openstreetmap/atlas/geography/atlas/command/OsmPbfToAtlasSubCommandTest.java
  src/test/java/org/openstreetmap/atlas/geography/atlas/items/complex/water/AbstractWaterIslandTest.java
  src/test/java/org/openstreetmap/atlas/geography/atlas/items/complex/water/ComplexWaterEntityTest.java
  src/test/java/org/openstreetmap/atlas/geography/atlas/raw/RawAtlasTest.java
  src/test/java/org/openstreetmap/atlas/geography/atlas/raw/creation/RawAtlasGeneratorTest.java
  src/test/java/org/openstreetmap/atlas/geography/atlas/raw/slicing/LineAndPointSlicingTest.java
  src/test/java/org/openstreetmap/atlas/geography/atlas/raw/slicing/RelationSlicingTest.java
  src/test/java/org/openstreetmap/atlas/geography/atlas/raw/slicing/RelationSlicingTestRule.java
  src/test/java/org/openstreetmap/atlas/tags/filters/ConfiguredTaggableFilterTest.java
Labels: New Feature

#356 Travis: Ensure right commit is tagged
  .travis/tag-master.sh
Labels: Bug

#357 Fixed a class cast bug with Node merging
  src/main/java/org/openstreetmap/atlas/geography/atlas/change/FeatureChange.java
  src/main/java/org/openstreetmap/atlas/utilities/collections/Sets.java
  src/test/java/org/openstreetmap/atlas/geography/atlas/change/FeatureChangeTest.java
Labels: Bug

#355 TaggableFilter with double negative
  src/main/java/org/openstreetmap/atlas/tags/Taggable.java
  src/main/java/org/openstreetmap/atlas/tags/filters/README.md
  src/test/java/org/openstreetmap/atlas/tags/filters/TaggableFilterTest.java
Labels: Bug, Data Change

#358 TurnRestriction: catch errors in TurnRestriction route()
  src/main/java/org/openstreetmap/atlas/geography/atlas/items/TurnRestriction.java
  src/test/java/org/openstreetmap/atlas/geography/atlas/items/complex/restriction/ComplexTurnRestrictionTest.java
  src/test/java/org/openstreetmap/atlas/geography/atlas/items/complex/restriction/ComplexTurnRestrictionTestCaseRule.java
  src/test/resources/org/openstreetmap/atlas/geography/atlas/items/complex/restriction/atlasBrokenTurnRestrictionRoute.josm.osm
Labels: Bug

#360 MultiplePolyLineToPolygonsConverterCommand: MultiLineString
  src/main/java/org/openstreetmap/atlas/geography/converters/MultiplePolyLineToPolygonsConverterCommand.java
  src/test/java/org/openstreetmap/atlas/geography/converters/MultiplePolyLineToPolygonsConverterCommandTest.java
Labels: New Feature

#363 Remove bloated from non-test code
  src/main/java/org/openstreetmap/atlas/geography/atlas/change/FeatureChange.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/change/diff/AtlasDiff.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/change/diff/AtlasDiffHelper.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/complete/CompleteArea.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/complete/CompleteEdge.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/complete/CompleteLine.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/complete/CompleteNode.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/complete/CompletePoint.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/complete/CompleteRelation.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/complete/EmptyAtlas.java
Labels: Enhancement

#359 Add a new static method isOfSameType() to Validators
  src/main/java/org/openstreetmap/atlas/tags/annotations/validation/Validators.java
  src/test/java/org/openstreetmap/atlas/tags/annotations/validation/ValidatorsHasValuesForTestCase.java
Labels: Enhancement

#365 bug fix in Polygon isClockwise method
  src/main/java/org/openstreetmap/atlas/geography/Polygon.java
  src/main/java/org/openstreetmap/atlas/geography/converters/GeodeticEarthCenteredEarthFixedConverter.java
  src/test/java/org/openstreetmap/atlas/geography/PolygonTest.java
Labels: Bug

#367 added a new pbf2raw command
  src/main/java/org/openstreetmap/atlas/utilities/command/subcommands/PbfToRawAtlasCommand.java
  src/main/resources/org/openstreetmap/atlas/utilities/command/subcommands/PbfToRawAtlasCommandExamplesSection.txt
  src/main/resources/org/openstreetmap/atlas/utilities/command/subcommands/PbfToRawAtlasDescriptionSection.txt
Labels: New Feature

#366 Jdk11 compatibility
  dependencies.gradle
  gradle/quality.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  src/main/java/org/openstreetmap/atlas/geography/Polygon.java
  src/main/java/org/openstreetmap/atlas/geography/Rectangle.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/raw/slicing/CoordinateToNewPointMapping.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/raw/slicing/CountryCodeProperties.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/raw/slicing/RawAtlasPointAndLineSlicer.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/raw/slicing/RawAtlasRelationSlicer.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/raw/slicing/RawAtlasSlicer.java
  src/main/java/org/openstreetmap/atlas/geography/boundary/AbstractGridIndexBuilder.java
  src/main/java/org/openstreetmap/atlas/geography/boundary/CountryBoundaryMap.java
  src/main/java/org/openstreetmap/atlas/geography/boundary/CountryBoundaryMapCompareCommand.java
  src/main/java/org/openstreetmap/atlas/geography/boundary/DynamicGridIndexBuilder.java
  src/main/java/org/openstreetmap/atlas/geography/boundary/FixedGridIndexBuilder.java
  src/main/java/org/openstreetmap/atlas/geography/clipping/MultiPolygonClipper.java
  src/main/java/org/openstreetmap/atlas/geography/clipping/PolygonClipper.java
  src/main/java/org/openstreetmap/atlas/geography/converters/PolygonStringFormat.java
  src/main/java/org/openstreetmap/atlas/geography/converters/WkbLocationConverter.java
  src/main/java/org/openstreetmap/atlas/geography/converters/WkbMultiPolygonConverter.java
  src/main/java/org/openstreetmap/atlas/geography/converters/WkbPolyLineConverter.java
  src/main/java/org/openstreetmap/atlas/geography/converters/WkbPolygonConverter.java
  src/main/java/org/openstreetmap/atlas/geography/converters/WktLocationConverter.java
  src/main/java/org/openstreetmap/atlas/geography/converters/WktMultiPolyLineConverter.java
  src/main/java/org/openstreetmap/atlas/geography/converters/WktMultiPolygonConverter.java
  src/main/java/org/openstreetmap/atlas/geography/converters/WktPolyLineConverter.java
  src/main/java/org/openstreetmap/atlas/geography/converters/WktPolygonConverter.java
  src/main/java/org/openstreetmap/atlas/geography/converters/jts/GeometryStreamer.java
  src/main/java/org/openstreetmap/atlas/geography/converters/jts/JtsCoordinateArrayConverter.java
  src/main/java/org/openstreetmap/atlas/geography/converters/jts/JtsLinearRingConverter.java
  src/main/java/org/openstreetmap/atlas/geography/converters/jts/JtsLocationConverter.java
  src/main/java/org/openstreetmap/atlas/geography/converters/jts/JtsMultiPolyLineConverter.java
  src/main/java/org/openstreetmap/atlas/geography/converters/jts/JtsMultiPolygonConverter.java
  src/main/java/org/openstreetmap/atlas/geography/converters/jts/JtsMultiPolygonToMultiPolygonConverter.java
  src/main/java/org/openstreetmap/atlas/geography/converters/jts/JtsPointConverter.java
  src/main/java/org/openstreetmap/atlas/geography/converters/jts/JtsPolyLineConverter.java
  src/main/java/org/openstreetmap/atlas/geography/converters/jts/JtsPolygonConverter.java
  src/main/java/org/openstreetmap/atlas/geography/converters/jts/JtsPrecisionManager.java
  src/main/java/org/openstreetmap/atlas/geography/converters/jts/JtsUtility.java
  src/main/java/org/openstreetmap/atlas/geography/index/QuadTree.java
  src/main/java/org/openstreetmap/atlas/geography/index/RTree.java
  src/main/java/org/openstreetmap/atlas/utilities/command/subcommands/SubAtlasCommand.java
  src/main/java/org/openstreetmap/atlas/utilities/command/subcommands/WKTShardCommand.java
  src/test/java/org/openstreetmap/atlas/geography/MultiPolyLineTest.java
  src/test/java/org/openstreetmap/atlas/geography/boundary/CountryBoundaryMapTest.java
  src/test/java/org/openstreetmap/atlas/geography/boundary/DynamicGridIndexBuilderTest.java
  src/test/java/org/openstreetmap/atlas/geography/converters/WkBPolygonConverterTest.java
  src/test/java/org/openstreetmap/atlas/geography/converters/WkbPolyLineConverterTest.java
  src/test/java/org/openstreetmap/atlas/test/TestUtility.java
  src/test/java/org/openstreetmap/atlas/utilities/filters/AtlasEntityPolygonsFilterTest.java
  src/test/java/org/openstreetmap/atlas/utilities/runtime/RunScriptTest.java
Labels: Bug, Enhancement
