Repository osmlab/atlas, pull requests merged in 2019-07, with the labels that each got.

#477 ID generator no longer takes bounds into account for CompleteRelations
  src/main/java/org/openstreetmap/atlas/utilities/identifiers/EntityIdentifierGenerator.java
Labels: Bug, Fail

#479 ArrangementCheck Readme: Update supported checkstyle versions
  src/main/java/org/openstreetmap/atlas/utilities/checkstyle/README.md
Labels: Documentation

#480 Fix Sonar Warning about Jacoco
  .travis/sonar.sh
  build.gradle
  gradle/quality.gradle
Labels: Testing

#481 Jacoco report should take integration tests too
  gradle/quality.gradle
Labels: Testing

#482 Ignore slow integration tests while better solution thought out
  .travis/build.sh
  src/integrationTest/java/org/openstreetmap/atlas/geography/PolygonPerformanceTest.java
  src/integrationTest/java/org/openstreetmap/atlas/geography/atlas/raw/RawAtlasIntegrationTest.java
Labels: Fail, Performance, Testing

#483 CircleCI: Sonar and PyAtlas
  .circleci/config.yml
  .circleci/sonar.sh
Labels: Testing

#484 AtlasChangeGenerator to enforce Node location
  src/main/java/org/openstreetmap/atlas/geography/atlas/change/AtlasChangeGenerator.java
  src/test/java/org/openstreetmap/atlas/geography/atlas/change/AtlasChangeGeneratorTest.java
Labels: Enhancement

#485 Upgraded find-id command to support more search criteria
  src/main/java/org/openstreetmap/atlas/geography/atlas/complete/CompleteNode.java
  src/main/java/org/openstreetmap/atlas/utilities/command/subcommands/AtlasSearchCommand.java
  src/main/java/org/openstreetmap/atlas/utilities/command/subcommands/IdentifierSearchCommand.java
  src/main/resources/org/openstreetmap/atlas/utilities/command/subcommands/AtlasSearchCommandDescriptionSection.txt
  src/main/resources/org/openstreetmap/atlas/utilities/command/subcommands/AtlasSearchCommandExamplesSection.txt
  src/main/resources/org/openstreetmap/atlas/utilities/command/subcommands/IdentifierSearchCommandDescriptionSection.txt
  src/main/resources/org/openstreetmap/atlas/utilities/command/subcommands/IdentifierSearchCommandExamplesSection.txt
  src/test/java/org/openstreetmap/atlas/utilities/command/subcommands/AtlasSearchCommandTest.java
Labels: Enhancement, New Feature

#486 Added metadata to FeatureChange pretty string
  src/main/java/org/openstreetmap/atlas/geography/atlas/change/FeatureChange.java
Labels: Enhancement

#487 Added a special exception for FeatureChange merge failures
  src/main/java/org/openstreetmap/atlas/exception/change/FeatureChangeMergeException.java
  src/main/java/org/openstreetmap/atlas/exception/change/MergeFailureType.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/change/MemberMerger.java
  src/test/java/org/openstreetmap/atlas/geography/atlas/change/TagChangeTest.java
Labels: Enhancement

#488 Implemented more robust FeatureChangeMergeException mechanics
  src/main/java/org/openstreetmap/atlas/exception/change/FeatureChangeMergeException.java
  src/main/java/org/openstreetmap/atlas/exception/change/MergeFailureType.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/change/FeatureChange.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/change/FeatureChangeMergingHelpers.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/change/MemberMergeStrategies.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/change/MemberMerger.java
  src/test/java/org/openstreetmap/atlas/geography/atlas/change/FeatureChangeMergerTest.java
  src/test/java/org/openstreetmap/atlas/geography/atlas/change/MemberMergeStrategiesTest.java
Labels: Enhancement

#489 A few more FeatureChangeMergeException improvements
  src/main/java/org/openstreetmap/atlas/exception/change/FeatureChangeMergeException.java
  src/main/java/org/openstreetmap/atlas/exception/change/MergeFailureType.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/change/FeatureChangeMergingHelpers.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/change/MemberMergeStrategies.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/change/MemberMerger.java
  src/test/java/org/openstreetmap/atlas/geography/atlas/change/FeatureChangeMergerTest.java
Labels: Enhancement

#490 Added some newlines to stacktraces for readability
  src/main/java/org/openstreetmap/atlas/geography/atlas/change/MemberMergeStrategies.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/change/MemberMerger.java
Labels: Enhancement

#492 Made FeatureChange#withAtlasContext method public
  src/main/java/org/openstreetmap/atlas/geography/atlas/change/FeatureChange.java
Labels: Enhancement
