Repository osmlab/atlas, pull requests merged in 2019-01, with the labels that each got.

#317 DNM: Added some additional file suffixes
  src/main/java/org/openstreetmap/atlas/streaming/resource/FileSuffix.java
Labels: Enhancement

#318 Removing deprecated code and updating FastClasspathScanner to ClassGraph
  build.gradle
  dependencies.gradle
  src/integrationTest/java/org/openstreetmap/atlas/geography/atlas/SubAtlasIntegrationTest.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/Atlas.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/README.md
  src/main/java/org/openstreetmap/atlas/geography/atlas/bloated/BloatedAtlas.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/command/AbstractAtlasOutputTestSubCommand.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/command/AtlasReader.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/command/AtlasSplitterWithSlippyTileCommand.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/command/SubAtlasSubCommand.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/multi/MultiAtlas.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/raw/sectioning/WaySectionProcessor.java
  src/main/java/org/openstreetmap/atlas/proto/builder/ProtoAtlasBuilder.java
  src/main/java/org/openstreetmap/atlas/streaming/readers/CsvReader.java
  src/main/java/org/openstreetmap/atlas/streaming/resource/http/HttpResource.java
  src/main/java/org/openstreetmap/atlas/tags/annotations/validation/ExactMatchValidator.java
  src/main/java/org/openstreetmap/atlas/tags/annotations/validation/TagDocumenter.java
  src/main/java/org/openstreetmap/atlas/tags/annotations/validation/Validators.java
  src/main/java/org/openstreetmap/atlas/tags/filters/LineFilterConverter.java
  src/main/java/org/openstreetmap/atlas/utilities/runtime/FlexibleCommand.java
  src/test/java/org/openstreetmap/atlas/geography/atlas/dynamic/DynamicAtlasMovingTooFastTest.java
  src/test/java/org/openstreetmap/atlas/geography/atlas/dynamic/DynamicAtlasRestrainedExpansionWithPolygonTest.java
Labels: Breaking Change, Enhancement

#320 Update to latest released ClassGraph dependency
  dependencies.gradle
Labels: Enhancement

#319 Complex Entity for AOI
  src/main/java/org/openstreetmap/atlas/geography/atlas/items/complex/aoi/ComplexAreaOfInterest.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/items/complex/aoi/ComplexAreaOfInterestFinder.java
  src/main/resources/org/openstreetmap/atlas/geography/atlas/items/complex/aoi/aoi-tag-filter.json
  src/test/java/org/openstreetmap/atlas/geography/atlas/items/complex/aoi/ComplexAreaOfInterestFinderTest.java
  src/test/java/org/openstreetmap/atlas/geography/atlas/items/complex/aoi/ComplexAreaOfInterestFinderTestRule.java
Labels: New Feature

#322 Added a necessary patch to get fat jars to work
  atlas-shell-tools/scripts/common/ast_repo_subsystem.pm
Labels: Bug

#323 Relation geojson geometry actually represents
  src/main/java/org/openstreetmap/atlas/geography/atlas/items/Relation.java
Labels: Enhancement

#327 Fixed a bug in RawAtlasPointAndLineSlicer that prevented ferry slicing
  src/main/java/org/openstreetmap/atlas/geography/atlas/raw/slicing/RawAtlasPointAndLineSlicer.java
Labels: Bug

#324 Move Event Service to Atlas
  src/main/java/org/openstreetmap/atlas/event/Event.java
  src/main/java/org/openstreetmap/atlas/event/EventService.java
  src/main/java/org/openstreetmap/atlas/event/Processor.java
  src/main/java/org/openstreetmap/atlas/event/README.md
  src/main/java/org/openstreetmap/atlas/event/ShutdownEvent.java
  src/test/java/org/openstreetmap/atlas/event/EventBusTest.java
  src/test/java/org/openstreetmap/atlas/event/EventServiceTest.java
  src/test/java/org/openstreetmap/atlas/event/TestEvent.java
  src/test/java/org/openstreetmap/atlas/event/TestProcessor.java
Labels: New Feature

#325 Add Construction Tag
  src/main/java/org/openstreetmap/atlas/tags/ConstructionTag.java
Labels: Enhancement

#326 SnappedLocation: Equals method backwards compatability
  src/main/java/org/openstreetmap/atlas/geography/Snapper.java
  src/test/java/org/openstreetmap/atlas/geography/SnapperTest.java
Labels: Bug

#328 Added a command line tool for atlas diffing
  src/main/java/org/openstreetmap/atlas/utilities/command/subcommands/AtlasDiffCommand.java
  src/main/resources/org/openstreetmap/atlas/utilities/command/subcommands/AtlasDiffCommandDescriptionSection.txt
  src/main/resources/org/openstreetmap/atlas/utilities/command/subcommands/AtlasDiffCommandExamplesSection.txt
Labels: New Feature

#330 Added a protobuf conversion command, and tweaked atlas saving behaviour
  atlas-shell-tools/man/man1/atlas-config-repo.1
  src/main/java/org/openstreetmap/atlas/geography/atlas/packed/PackedAtlas.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/packed/PackedAtlasSerializer.java
  src/main/java/org/openstreetmap/atlas/utilities/command/abstractcommand/AbstractAtlasShellToolsCommand.java
  src/main/java/org/openstreetmap/atlas/utilities/command/subcommands/ConcatenateAtlasCommand.java
  src/main/java/org/openstreetmap/atlas/utilities/command/subcommands/JavaToProtoSerializationCommand.java
  src/main/java/org/openstreetmap/atlas/utilities/command/subcommands/PackedToTextAtlasCommand.java
  src/main/java/org/openstreetmap/atlas/utilities/command/subcommands/SubAtlasCommand.java
  src/main/java/org/openstreetmap/atlas/utilities/command/subcommands/templates/VariadicAtlasLoaderCommand.java
  src/main/resources/org/openstreetmap/atlas/utilities/command/subcommands/AtlasDiffCommandExamplesSection.txt
  src/main/resources/org/openstreetmap/atlas/utilities/command/subcommands/ConcatenateAtlasCommandDescriptionSection.txt
  src/main/resources/org/openstreetmap/atlas/utilities/command/subcommands/JavaToProtoSerializationCommandDescriptionSection.txt
  src/main/resources/org/openstreetmap/atlas/utilities/command/subcommands/JavaToProtoSerializationCommandExamplesSection.txt
  src/main/resources/org/openstreetmap/atlas/utilities/command/subcommands/PackedToTextAtlasCommandDescriptionSection.txt
  src/main/resources/org/openstreetmap/atlas/utilities/command/subcommands/PackedToTextAtlasCommandExamplesSection.txt
Labels: Enhancement, New Feature

#331 Tame too zealous validation on reverse edge
  src/main/java/org/openstreetmap/atlas/geography/atlas/change/validators/ChangeValidator.java
  src/test/java/org/openstreetmap/atlas/geography/atlas/change/validators/ChangeValidatorTest.java
Labels: Bug

#332 Tame too zealous validation on reverse edge v.2
  src/main/java/org/openstreetmap/atlas/geography/atlas/change/validators/ChangeValidator.java
  src/test/java/org/openstreetmap/atlas/geography/atlas/change/validators/ChangeValidatorTest.java
Labels: Bug

#333 Added a shard to bounds command
  src/main/java/org/openstreetmap/atlas/utilities/command/subcommands/AtlasDiffCommand.java
  src/main/java/org/openstreetmap/atlas/utilities/command/subcommands/AtlasShellToolsDemoCommand.java
  src/main/java/org/openstreetmap/atlas/utilities/command/subcommands/ConcatenateAtlasCommand.java
  src/main/java/org/openstreetmap/atlas/utilities/command/subcommands/HelloWorldCommand.java
  src/main/java/org/openstreetmap/atlas/utilities/command/subcommands/JavaToProtoSerializationCommand.java
  src/main/java/org/openstreetmap/atlas/utilities/command/subcommands/PackedToTextAtlasCommand.java
  src/main/java/org/openstreetmap/atlas/utilities/command/subcommands/ShardToBoundsCommand.java
  src/main/java/org/openstreetmap/atlas/utilities/command/subcommands/SubAtlasCommand.java
  src/main/java/org/openstreetmap/atlas/utilities/command/subcommands/WKTShardCommand.java
  src/main/java/org/openstreetmap/atlas/utilities/command/subcommands/templates/VariadicAtlasLoaderCommand.java
  src/main/resources/org/openstreetmap/atlas/utilities/command/subcommands/ShardToBoundsCommandDescriptionSection.txt
  src/main/resources/org/openstreetmap/atlas/utilities/command/subcommands/ShardToBoundsCommandExamplesSection.txt
Labels: New Feature
