Repository osmlab/atlas, pull requests merged in 2020-02, with the labels that each got.

#597 Fixed a bug where TestAtlas would choke on text atlases
  src/main/java/org/openstreetmap/atlas/geography/atlas/AtlasResourceLoader.java
  src/main/java/org/openstreetmap/atlas/streaming/resource/FileSuffix.java
  src/main/java/org/openstreetmap/atlas/utilities/command/subcommands/PackedToTextAtlasCommand.java
  src/test/java/org/openstreetmap/atlas/geography/atlas/AtlasResourceLoaderTest.java
Labels: Bug

#599 Fixed an NPE that occurred on loading empty atlases
  src/main/java/org/openstreetmap/atlas/geography/atlas/AtlasResourceLoader.java
  src/test/java/org/openstreetmap/atlas/geography/atlas/AtlasResourceLoaderTest.java
Labels: Bug

#604 Enforce stricter name checks for residential roads
  src/main/java/org/openstreetmap/atlas/geography/atlas/items/complex/bignode/BigNodeFinder.java
  src/test/java/org/openstreetmap/atlas/geography/atlas/items/complex/bignode/BigNodeFinderTest.java
  src/test/java/org/openstreetmap/atlas/geography/atlas/items/complex/bignode/BigNodeFinderTestCaseRule.java
  src/test/resources/org/openstreetmap/atlas/geography/atlas/items/complex/bignode/overmerge.atlas.txt.gz
Labels: Enhancement

#601 Improved slicing logic
  src/main/java/org/openstreetmap/atlas/geography/atlas/raw/slicing/RawAtlasPointAndLineSlicer.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/raw/slicing/RawAtlasRelationSlicer.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/raw/slicing/RawAtlasSlicer.java
  src/main/java/org/openstreetmap/atlas/geography/boundary/CountryBoundaryMap.java
  src/test/java/org/openstreetmap/atlas/geography/atlas/raw/slicing/InvalidMultipolygonSlicingTest.java
  src/test/java/org/openstreetmap/atlas/geography/atlas/raw/slicing/RelationSlicingTest.java
Labels: Data Change, Enhancement

#605 Option for quadratic wait in Retry
  src/main/java/org/openstreetmap/atlas/utilities/runtime/Retry.java
  src/main/java/org/openstreetmap/atlas/utilities/scalars/Duration.java
  src/test/java/org/openstreetmap/atlas/utilities/runtime/RetryTest.java
  src/test/java/org/openstreetmap/atlas/utilities/scalars/DurationTest.java
Labels: New Feature

#608 Quadratic retries with the NamespaceCachingStrategy
  src/main/java/org/openstreetmap/atlas/utilities/caching/strategies/NamespaceCachingStrategy.java
Labels: Enhancement

#609 WktPolygonConverter to read single outer MultiPolygons
  src/main/java/org/openstreetmap/atlas/geography/converters/WktPolygonConverter.java
  src/test/java/org/openstreetmap/atlas/geography/converters/WktPolygonConverterTest.java
Labels: New Feature

#610 [AQL] Documentation improvements
  src/main/groovy/org/openstreetmap/atlas/geography/atlas/dsl/AQLExplainPlan.md
  src/main/groovy/org/openstreetmap/atlas/geography/atlas/dsl/AQLIndexingAndScanStrategy.md
  src/main/groovy/org/openstreetmap/atlas/geography/atlas/dsl/AQLInternals.md
  src/main/groovy/org/openstreetmap/atlas/geography/atlas/dsl/AQLOptimization.md
  src/main/groovy/org/openstreetmap/atlas/geography/atlas/dsl/README.md
  src/main/groovy/org/openstreetmap/atlas/geography/atlas/dsl/query/optimizer/optimization/impl/IdsInOptimization.groovy
  src/test/groovy/org/openstreetmap/atlas/geography/atlas/dsl/query/DeleteQueryTest.groovy
  src/test/groovy/org/openstreetmap/atlas/geography/atlas/dsl/query/SelectQueryTest.groovy
  src/test/groovy/org/openstreetmap/atlas/geography/atlas/dsl/query/UpdateQueryTest.groovy
  src/test/groovy/org/openstreetmap/atlas/geography/atlas/dsl/query/optimizer/optimization/impl/IdsInOptimizationTest.groovy
Labels: Documentation, Testing
