Repository osmlab/atlas, pull requests merged in 2020-06, with the labels that each got.

#636 Refactored File to be file system agnostic
  build.gradle
  dependencies.gradle
  src/integrationTest/java/org/openstreetmap/atlas/geography/boundary/CountryBoundaryMapArchiverIntegrationTest.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/Crawler.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/command/AtlasFeatureCountsSubCommand.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/items/complex/islands/ComplexIslandFinder.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/items/complex/water/finder/WaterConfigurationReader.java
  src/main/java/org/openstreetmap/atlas/geography/sharding/Sharding.java
  src/main/java/org/openstreetmap/atlas/streaming/resource/File.java
  src/main/java/org/openstreetmap/atlas/streaming/resource/README.md
  src/main/java/org/openstreetmap/atlas/streaming/resource/TemporaryFile.java
  src/main/java/org/openstreetmap/atlas/utilities/caching/strategies/NamespaceCachingStrategy.java
  src/main/java/org/openstreetmap/atlas/utilities/command/documentation/PagerHelper.java
  src/main/java/org/openstreetmap/atlas/utilities/command/subcommands/AnyToGeoJsonCommand.java
  src/main/java/org/openstreetmap/atlas/utilities/command/subcommands/AtlasSearchCommand.java
  src/main/java/org/openstreetmap/atlas/utilities/command/subcommands/CountryShardToBoundsCommand.java
  src/main/java/org/openstreetmap/atlas/utilities/command/subcommands/JavaToProtoSerializationCommand.java
  src/main/java/org/openstreetmap/atlas/utilities/command/subcommands/PackedToTextAtlasCommand.java
  src/main/java/org/openstreetmap/atlas/utilities/command/subcommands/PbfToAtlasCommand.java
  src/main/java/org/openstreetmap/atlas/utilities/command/subcommands/SubAtlasCommand.java
  src/main/java/org/openstreetmap/atlas/utilities/command/subcommands/WKTShardCommand.java
  src/test/java/org/openstreetmap/atlas/geography/atlas/ShardFileOverlapsPolygonTest.java
  src/test/java/org/openstreetmap/atlas/geography/atlas/command/AtlasFindByAtlasIdentifierSubCommandTest.java
  src/test/java/org/openstreetmap/atlas/geography/atlas/command/AtlasJoinerSubCommandTest.java
  src/test/java/org/openstreetmap/atlas/streaming/resource/FileTest.java
  src/test/java/org/openstreetmap/atlas/streaming/resource/RecursiveListWithMissingFileTestCase.java
  src/test/java/org/openstreetmap/atlas/utilities/command/subcommands/AtlasSearchCommandTest.java
  src/test/java/org/openstreetmap/atlas/utilities/command/subcommands/CountryShardToBoundsCommandTest.java
  src/test/java/org/openstreetmap/atlas/utilities/command/subcommands/PbfToAtlasCommandTest.java
  src/test/java/org/openstreetmap/atlas/utilities/command/subcommands/ShardingConverterCommandTest.java
  src/test/java/org/openstreetmap/atlas/utilities/command/subcommands/WKTShardCommandTest.java
Labels: Breaking Change, Enhancement

#637 Bumped down level of ComplexWaterEntityFinder logs
  src/main/java/org/openstreetmap/atlas/geography/atlas/items/complex/water/finder/ComplexWaterEntityFinder.java
Labels: Logging

#638 AbstractAtlasShellToolsCommand now provides API for environment and InputStream
  src/main/java/org/openstreetmap/atlas/utilities/command/abstractcommand/AbstractAtlasShellToolsCommand.java
  src/main/java/org/openstreetmap/atlas/utilities/command/subcommands/AtlasShellToolsDemoCommand.java
  src/test/java/org/openstreetmap/atlas/utilities/command/subcommands/AtlasShellToolsDemoCommandTest.java
Labels: Enhancement

#641 Removed connectivity from EntityIdentifierGenerator
  src/main/java/org/openstreetmap/atlas/utilities/identifiers/EntityIdentifierGenerator.java
  src/test/java/org/openstreetmap/atlas/utilities/identifiers/EntityIdentifierGeneratorTest.java
Labels: Enhancement

#642 Bumped log in CountryBoundaryMap down to debug
  src/main/java/org/openstreetmap/atlas/geography/boundary/CountryBoundaryMap.java
Labels: Logging

#644 Fixes for slicing certain OSM valid polygons that are OGC invalid
  src/main/java/org/openstreetmap/atlas/geography/atlas/raw/slicing/README.md
  src/main/java/org/openstreetmap/atlas/geography/atlas/raw/slicing/RawAtlasSlicer.java
  src/main/java/org/openstreetmap/atlas/tags/AtlasTag.java
  src/main/java/org/openstreetmap/atlas/tags/SyntheticInvalidGeometryTag.java
  src/test/java/org/openstreetmap/atlas/geography/atlas/raw/slicing/RawAtlasSlicerTestRule.java
  src/test/java/org/openstreetmap/atlas/geography/atlas/raw/slicing/RawAtlasSlicingTest.java
Labels: New Feature

#646 Added reverse functionality to Angle
  src/main/java/org/openstreetmap/atlas/utilities/scalars/Angle.java
  src/test/java/org/openstreetmap/atlas/utilities/scalars/AngleTest.java
Labels: New Feature
