Repository osmlab/atlas, pull requests merged in 2020-10, with the labels that each got.

#689 Make Relation ID generator deterministic
  src/main/java/org/openstreetmap/atlas/geography/atlas/builder/RelationBean.java
  src/main/java/org/openstreetmap/atlas/utilities/identifiers/EntityIdentifierGenerator.java
  src/test/java/org/openstreetmap/atlas/utilities/identifiers/EntityIdentifierGeneratorTest.java
Labels: Breaking Change, Bug

#686 MultiPolygon GeoJson Parser Fix
  src/main/java/org/openstreetmap/atlas/geography/geojson/parser/domain/geometry/MultiLineString.java
  src/main/java/org/openstreetmap/atlas/geography/geojson/parser/domain/geometry/MultiPoint.java
  src/main/java/org/openstreetmap/atlas/geography/geojson/parser/domain/geometry/MultiPolygon.java
  src/main/java/org/openstreetmap/atlas/geography/geojson/parser/domain/geometry/Point.java
  src/main/java/org/openstreetmap/atlas/geography/geojson/parser/domain/geometry/coordinate/Coordinates.java
  src/test/java/org/openstreetmap/atlas/geography/geojson/parser/domain/geometry/coordinate/CoordinatesTest.java
  src/test/java/org/openstreetmap/atlas/geography/geojson/parser/impl/gson/GeoJsonParserGsonImplTest.java
  src/test/resources/org/openstreetmap/atlas/geography/geojson/parser/multiPolygon.json
  src/test/resources/org/openstreetmap/atlas/geography/geojson/parser/multiPolygonConversion.json
  src/test/resources/org/openstreetmap/atlas/geography/geojson/parser/multiPolygonDonut.json
Labels: Breaking Change, Bug

#691 Add a sample demo class which uses Atlas
  .gitignore
  README.md
  sample/Readme.md
  sample/build.gradle
  sample/settings.gradle
  sample/src/main/java/org/openstreetmap/atlas/sample/Sample.java
  sample/src/main/resources/log4j.properties
Labels: Documentation

#690 Use JTS Polygonizer to re-construct Polygons
  src/main/java/org/openstreetmap/atlas/geography/GeometricObject.java
  src/main/java/org/openstreetmap/atlas/geography/MultiPolygon.java
  src/main/java/org/openstreetmap/atlas/geography/Polygon.java
  src/main/java/org/openstreetmap/atlas/geography/converters/MultiplePolyLineToPolygonsConverter.java
  src/test/java/org/openstreetmap/atlas/geography/atlas/items/complex/RelationToMultiPolygonMemberConverterTest.java
  src/test/java/org/openstreetmap/atlas/geography/atlas/raw/slicing/RawAtlasSlicingTest.java
  src/test/java/org/openstreetmap/atlas/geography/boundary/CountryBoundaryMapTest.java
  src/test/java/org/openstreetmap/atlas/geography/converters/MultiplePolyLineToPolygonsConverterCommandTest.java
  src/test/java/org/openstreetmap/atlas/geography/converters/MultiplePolyLineToPolygonsConverterTest.java
  src/test/java/org/openstreetmap/atlas/utilities/command/subcommands/RelationToMultiPolygonCommandTest.java
  src/test/resources/org/openstreetmap/atlas/geography/converters/MultiplePolyLineToPolygonsConverterTest_crossingPolyLines.txt
  src/test/resources/org/openstreetmap/atlas/geography/converters/MultiplePolyLineToPolygonsConverterTest_expectedPolygons.txt
  src/test/resources/org/openstreetmap/atlas/geography/converters/MultiplePolyLineToPolygonsConverterTest_multiplePolyLines.txt
Labels: Enhancement

#692 Big node improvement: Service and Link roads
  src/main/java/org/openstreetmap/atlas/geography/atlas/items/complex/bignode/BigNodeFinder.java
  src/test/java/org/openstreetmap/atlas/geography/atlas/items/complex/bignode/BigNodeFinderTest.java
  src/test/java/org/openstreetmap/atlas/geography/atlas/items/complex/bignode/BigNodeFinderTestCaseRule.java
  src/test/resources/org/openstreetmap/atlas/geography/atlas/items/complex/bignode/dnk-link-road-test.osm
  src/test/resources/org/openstreetmap/atlas/geography/atlas/items/complex/bignode/ukr-link-road-test.osm
Labels: Enhancement

#694 CountryBoundaryMap: Do not override polygon ID key
  src/main/java/org/openstreetmap/atlas/geography/boundary/CountryBoundaryMap.java
Labels: Bug

#693 CompleteRelation.changeMemberRole should list old role as explicitly excluded
  src/main/java/org/openstreetmap/atlas/geography/atlas/complete/CompleteRelation.java
  src/test/java/org/openstreetmap/atlas/geography/atlas/complete/CompleteRelationTest.java
Labels: Bug

#695 Atlas command to itemize country boundary map
  src/main/java/org/openstreetmap/atlas/geography/boundary/CountryBoundaryMapPrinter.java
  src/main/java/org/openstreetmap/atlas/utilities/command/subcommands/CountryBoundaryMapPrinterCommand.java
  src/main/resources/org/openstreetmap/atlas/utilities/command/subcommands/CountryBoundaryMapPrinterCommandDescriptionSection.txt
  src/main/resources/org/openstreetmap/atlas/utilities/command/subcommands/CountryBoundaryMapPrinterCommandExamplesSection.txt
  src/test/java/org/openstreetmap/atlas/utilities/command/subcommands/CountryBoundaryMapPrinterCommandTest.java
  src/test/resources/org/openstreetmap/atlas/utilities/command/subcommands/CountryBoundaryMapPrinterCommandTestBoundaries.txt
Labels: New Feature

#697 Fall back to legacy code with any Polygonizer exception
  src/main/java/org/openstreetmap/atlas/geography/converters/MultiplePolyLineToPolygonsConverter.java
  src/test/java/org/openstreetmap/atlas/geography/converters/MultiplePolyLineToPolygonsConverterTest.java
  src/test/resources/org/openstreetmap/atlas/geography/converters/MultiplePolyLineToPolygonsConverterTest_jtsErrorInner1.wkt
  src/test/resources/org/openstreetmap/atlas/geography/converters/MultiplePolyLineToPolygonsConverterTest_jtsErrorInner2.wkt
  src/test/resources/org/openstreetmap/atlas/geography/converters/MultiplePolyLineToPolygonsConverterTest_jtsErrorOuter.wkt
Labels: Bug, Enhancement

#700 Improved unit tests in caching package
  gradle.properties
  src/main/java/org/openstreetmap/atlas/utilities/caching/ConcurrentResourceCache.java
  src/main/java/org/openstreetmap/atlas/utilities/caching/LocalFileInMemoryCache.java
  src/main/java/org/openstreetmap/atlas/utilities/caching/strategies/ByteArrayCachingStrategy.java
  src/main/java/org/openstreetmap/atlas/utilities/caching/strategies/CachingStrategy.java
  src/main/java/org/openstreetmap/atlas/utilities/caching/strategies/GlobalNamespaceCachingStrategy.java
  src/main/java/org/openstreetmap/atlas/utilities/caching/strategies/NamespaceCachingStrategy.java
  src/main/java/org/openstreetmap/atlas/utilities/caching/strategies/NoCachingStrategy.java
  src/test/java/org/openstreetmap/atlas/utilities/caching/CachingTests.java
  src/test/java/org/openstreetmap/atlas/utilities/caching/ConcurrentResourceCacheTest.java
  src/test/java/org/openstreetmap/atlas/utilities/caching/LocalFileInMemoryCacheTest.java
  src/test/java/org/openstreetmap/atlas/utilities/caching/ResourceCacheTest.java
  src/test/java/org/openstreetmap/atlas/utilities/caching/strategies/ByteArrayCachingStrategyTest.java
  src/test/java/org/openstreetmap/atlas/utilities/caching/strategies/NamespaceCachingStrategiesTest.java
  src/test/java/org/openstreetmap/atlas/utilities/caching/strategies/NoCachingStrategyTest.java
  src/test/resources/org/openstreetmap/atlas/utilities/caching/feature.json
  src/test/resources/org/openstreetmap/atlas/utilities/caching/fileNoExt
  src/test/resources/org/openstreetmap/atlas/utilities/caching/strategies/hello.txt.gz
Labels: Testing

#703 File parent method no longer throws NullPointerException
  src/main/java/org/openstreetmap/atlas/streaming/resource/File.java
Labels: Bug

#699 Remove outdated scripts to avoid confusion with atlas-shell-tools
  scripts/README.md
  scripts/atlas
  scripts/shards
Labels: Duplicate

#704 ZipFileWritableResource no longer leaves open file descriptors
  src/main/java/org/openstreetmap/atlas/streaming/resource/zip/ZipFileWritableResource.java
  src/main/java/org/openstreetmap/atlas/streaming/resource/zip/ZipWritableResource.java
  src/test/java/org/openstreetmap/atlas/streaming/resource/zip/ZipResourceTest.java
Labels: Enhancement

#705 Make Polygonizer optional to re-construct multipolygons
  src/main/java/org/openstreetmap/atlas/geography/atlas/items/complex/RelationOrAreaToMultiPolygonConverter.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/items/complex/RelationToMultiPolygonMemberConverter.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/raw/slicing/RawAtlasSlicer.java
  src/main/java/org/openstreetmap/atlas/geography/converters/MultiplePolyLineToPolygonsConverter.java
Labels: Bug, Data Change

#706 Catch way-sectioning errors
  src/main/java/org/openstreetmap/atlas/geography/atlas/raw/sectioning/WaySectionProcessor.java
  src/test/java/org/openstreetmap/atlas/geography/atlas/raw/sectioning/WaySectionProcessorTest.java
  src/test/java/org/openstreetmap/atlas/geography/atlas/raw/sectioning/WaySectionProcessorTestRule.java
  src/test/resources/org/openstreetmap/atlas/geography/atlas/raw/sectioning/lineWithInvalidOverlappingGeometry.atlas.txt
Labels: Bug
