Repository osmlab/atlas, pull requests merged in 2020-05, with the labels that each got.

#628 Added reverse functionality to packed2text command
  src/main/java/org/openstreetmap/atlas/utilities/command/subcommands/PackedToTextAtlasCommand.java
  src/main/resources/org/openstreetmap/atlas/utilities/command/subcommands/PackedToTextAtlasCommandDescriptionSection.txt
  src/main/resources/org/openstreetmap/atlas/utilities/command/subcommands/PackedToTextAtlasCommandExamplesSection.txt
Labels: Enhancement, New Feature

#627 Refactored slicing
  src/integrationTest/java/org/openstreetmap/atlas/geography/atlas/AtlasIntegrationTest.java
  src/integrationTest/java/org/openstreetmap/atlas/geography/atlas/pbf/OsmPbfIngestIntegrationTest.java
  src/integrationTest/java/org/openstreetmap/atlas/geography/atlas/raw/RawAtlasIntegrationTest.java
  src/integrationTest/resources/org/openstreetmap/atlas/geography/atlas/raw/layerIntersectionAtStartBoundaryMap.txt
  src/main/java/org/openstreetmap/atlas/geography/atlas/AbstractAtlas.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/command/OsmPbfToAtlasSubCommand.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/complete/CompleteRelation.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/converters/AtlasDebugTool.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/items/Relation.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/pbf/AtlasLoadingOption.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/raw/sectioning/WaySectionProcessor.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/raw/slicing/CoordinateToNewPointMapping.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/raw/slicing/README.md
  src/main/java/org/openstreetmap/atlas/geography/atlas/raw/slicing/RawAtlasCountrySlicer.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/raw/slicing/RawAtlasPointAndLineSlicer.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/raw/slicing/RawAtlasRelationSlicer.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/raw/slicing/RawAtlasSlicer.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/raw/slicing/RawAtlasSlicingStatistic.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/raw/slicing/RuntimeCounter.java
  src/main/java/org/openstreetmap/atlas/geography/boundary/CountryBoundaryMap.java
  src/main/java/org/openstreetmap/atlas/geography/clipping/GeometryOperation.java
  src/main/java/org/openstreetmap/atlas/geography/converters/jts/JtsPrecisionManager.java
  src/main/java/org/openstreetmap/atlas/utilities/testing/TestAtlasHandler.java
  src/test/java/org/openstreetmap/atlas/geography/atlas/command/OsmPbfToAtlasSubCommandTest.java
  src/test/java/org/openstreetmap/atlas/geography/atlas/pbf/OsmPbfIngestTest.java
  src/test/java/org/openstreetmap/atlas/geography/atlas/raw/RawAtlasTest.java
  src/test/java/org/openstreetmap/atlas/geography/atlas/raw/slicing/InvalidMultipolygonSlicingTest.java
  src/test/java/org/openstreetmap/atlas/geography/atlas/raw/slicing/InvalidRelationSlicingTestRule.java
  src/test/java/org/openstreetmap/atlas/geography/atlas/raw/slicing/LineAndPointSlicingTest.java
  src/test/java/org/openstreetmap/atlas/geography/atlas/raw/slicing/LineAndPointSlicingTestRule.java
  src/test/java/org/openstreetmap/atlas/geography/atlas/raw/slicing/RelationSlicingTest.java
  src/test/java/org/openstreetmap/atlas/geography/boundary/CountryBoundaryMapTest.java
Labels: Breaking Change, Data Change, Enhancement, New Feature

#629 Do not use extend indefinitely to decide geometry operations in DynamicAtlasExpander
  src/main/java/org/openstreetmap/atlas/geography/atlas/dynamic/DynamicAtlasExpander.java
  src/test/java/org/openstreetmap/atlas/geography/atlas/dynamic/DynamicAtlasPreemptiveLoadTest.java
Labels: Bug

#630 Fix slicing bugs, add new synthetic tests, and overhaul slicing tests
  src/integrationTest/java/org/openstreetmap/atlas/geography/atlas/pbf/OsmPbfIngestIntegrationTest.java
  src/integrationTest/java/org/openstreetmap/atlas/geography/atlas/raw/RawAtlasIntegrationTest.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/AbstractAtlas.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/command/OsmPbfToAtlasSubCommand.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/converters/AtlasDebugTool.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/pbf/AtlasLoadingOption.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/raw/slicing/RawAtlasSlicer.java
  src/main/java/org/openstreetmap/atlas/tags/AtlasTag.java
  src/main/java/org/openstreetmap/atlas/tags/SyntheticGeometrySlicedTag.java
  src/main/java/org/openstreetmap/atlas/tags/SyntheticInvalidMultiPolygonRelationMembersRemovedTag.java
  src/main/java/org/openstreetmap/atlas/tags/SyntheticNearestNeighborCountryCodeTag.java
  src/main/java/org/openstreetmap/atlas/tags/SyntheticSyntheticRelationMemberTag.java
  src/test/java/org/openstreetmap/atlas/geography/atlas/pbf/OsmPbfIngestTest.java
  src/test/java/org/openstreetmap/atlas/geography/atlas/raw/RawAtlasTest.java
  src/test/java/org/openstreetmap/atlas/geography/atlas/raw/sectioning/WaySectionProcessorTest.java
  src/test/java/org/openstreetmap/atlas/geography/atlas/raw/slicing/InvalidMultipolygonSlicingTest.java
  src/test/java/org/openstreetmap/atlas/geography/atlas/raw/slicing/InvalidRelationSlicingTestRule.java
  src/test/java/org/openstreetmap/atlas/geography/atlas/raw/slicing/LineAndPointSlicingTest.java
  src/test/java/org/openstreetmap/atlas/geography/atlas/raw/slicing/LineAndPointSlicingTestRule.java
  src/test/java/org/openstreetmap/atlas/geography/atlas/raw/slicing/RawAtlasSlicerTestRule.java
  src/test/java/org/openstreetmap/atlas/geography/atlas/raw/slicing/RawAtlasSlicingTest.java
  src/test/java/org/openstreetmap/atlas/geography/atlas/raw/slicing/RelationSlicingTest.java
  src/test/java/org/openstreetmap/atlas/geography/atlas/raw/slicing/RelationSlicingTestRule.java
  src/test/java/org/openstreetmap/atlas/geography/atlas/raw/slicing/TemporaryEntityTest.java
  src/test/resources/org/openstreetmap/atlas/geography/atlas/pbf/slicing/CIV_GIN_LBR_osm_boundaries.txt.gz
  src/test/resources/org/openstreetmap/atlas/geography/atlas/pbf/slicing/relation_multipolygon.xml
  src/test/resources/org/openstreetmap/atlas/geography/atlas/pbf/slicing/relation_multipolygon_complex.xml
  src/test/resources/org/openstreetmap/atlas/geography/atlas/pbf/slicing/relation_multipolygon_complex_hole.xml
  src/test/resources/org/openstreetmap/atlas/geography/atlas/pbf/slicing/relation_multipolygon_hole.xml
  src/test/resources/org/openstreetmap/atlas/geography/atlas/pbf/slicing/testForceSlicingBoundaryMap.txt
  src/test/resources/org/openstreetmap/atlas/geography/atlas/pbf/slicing/way_inside.osm
Labels: Breaking Change, Data Change, Enhancement

#631 Attach cause to final thread pool error message
  src/main/java/org/openstreetmap/atlas/utilities/threads/Pool.java
Labels: Enhancement

#633 Fixed class name in unit test for CountryShardToBoundsCommand
  src/test/java/org/openstreetmap/atlas/utilities/command/subcommands/CountryShardToBoundsCommandTest.java
Labels: Bug

#634 Fixed an overflow bug in RelationMember#compareTo
  src/main/java/org/openstreetmap/atlas/geography/atlas/items/RelationMember.java
  src/test/java/org/openstreetmap/atlas/geography/atlas/items/RelationMemberComparisonTestCase.java
  src/test/java/org/openstreetmap/atlas/geography/atlas/items/RelationMemberComparisonTestCaseRule.java
Labels: Bug

#635 Added some comments and FileSystem methods
  src/main/java/org/openstreetmap/atlas/geography/sharding/DynamicTileSharding.java
  src/main/java/org/openstreetmap/atlas/geography/sharding/GeoHashSharding.java
  src/main/java/org/openstreetmap/atlas/geography/sharding/Sharding.java
  src/main/java/org/openstreetmap/atlas/geography/sharding/SlippyTileSharding.java
  src/main/java/org/openstreetmap/atlas/utilities/command/abstractcommand/AbstractAtlasShellToolsCommand.java
  src/main/java/org/openstreetmap/atlas/utilities/command/parsing/SimpleOptionAndArgumentParser.java
  src/main/java/org/openstreetmap/atlas/utilities/command/subcommands/OsmToAtlasCommand.java
  src/test/java/org/openstreetmap/atlas/geography/sharding/DynamicTileShardingTest.java
  src/test/java/org/openstreetmap/atlas/geography/sharding/GeoHashShardingTest.java
  src/test/java/org/openstreetmap/atlas/geography/sharding/SlippyTileShardingTest.java
Labels: Enhancement
