Repository osmlab/atlas, pull requests merged in 2020-01, with the labels that each got.

#584 Migration to gradle 6
  build.gradle
  gradle/deployment.gradle
  gradle/quality.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
Labels: Enhancement

#588 Shard bounds command now supports a reverse match
  src/main/java/org/openstreetmap/atlas/utilities/command/subcommands/ShardToBoundsCommand.java
  src/main/resources/org/openstreetmap/atlas/utilities/command/subcommands/ShardToBoundsCommandDescriptionSection.txt
  src/main/resources/org/openstreetmap/atlas/utilities/command/subcommands/ShardToBoundsCommandExamplesSection.txt
Labels: Enhancement

#585 Better error message for null boundary
  src/main/java/org/openstreetmap/atlas/geography/boundary/CountryBoundaryMap.java
Labels: Bug

#586 Major refactor of AtlasResourceLoader
  src/main/java/org/openstreetmap/atlas/geography/atlas/AtlasLoadingCommand.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/AtlasResourceLoader.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/builder/AtlasSize.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/builder/text/TextAtlasBuilder.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/command/AbstractAtlasSubCommand.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/delta/AtlasDeltaGenerator.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/geojson/LineDelimitedGeoJsonConverter.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/multi/MultiAtlas.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/packed/PackedAtlasBuilder.java
  src/main/java/org/openstreetmap/atlas/streaming/resource/AbstractResource.java
  src/main/java/org/openstreetmap/atlas/streaming/resource/FileSuffix.java
  src/main/java/org/openstreetmap/atlas/streaming/resource/Resource.java
  src/test/java/org/openstreetmap/atlas/geography/atlas/AtlasResourceLoaderTest.java
  src/test/java/org/openstreetmap/atlas/geography/atlas/IsAtlasTestCase.java
  src/test/java/org/openstreetmap/atlas/geography/atlas/multi/MultiAtlasOverlappingNodesFixerTest.java
  src/test/java/org/openstreetmap/atlas/geography/atlas/packed/PackedAtlasSerializerTest.java
Labels: Breaking Change, Enhancement

#587 Removed deprecated constructor from InputStreamResource
  src/main/java/org/openstreetmap/atlas/streaming/resource/InputStreamResource.java
  src/main/java/org/openstreetmap/atlas/streaming/resource/StringResource.java
  src/main/java/org/openstreetmap/atlas/utilities/runtime/RunScriptMonitor.java
  src/test/java/org/openstreetmap/atlas/geography/atlas/ShardFileOverlapsPolygonTest.java
  src/test/java/org/openstreetmap/atlas/geography/atlas/builder/GeoJsonAtlasBuilderTest.java
  src/test/java/org/openstreetmap/atlas/geography/boundary/CountryBoundaryMapTest.java
  src/test/java/org/openstreetmap/atlas/geography/boundary/CountryShardListingTest.java
  src/test/java/org/openstreetmap/atlas/geography/boundary/DynamicGridIndexBuilderTest.java
  src/test/java/org/openstreetmap/atlas/geography/boundary/converters/CountryBoundaryMapGeoJsonConverterTest.java
  src/test/java/org/openstreetmap/atlas/streaming/SplittableInputStreamTest.java
  src/test/java/org/openstreetmap/atlas/streaming/readers/CsvReaderTest.java
  src/test/java/org/openstreetmap/atlas/streaming/readers/GeoJsonReaderTest.java
  src/test/java/org/openstreetmap/atlas/streaming/resource/zip/ZipResourceTest.java
  src/test/java/org/openstreetmap/atlas/tags/filters/ConfiguredTaggableFilterTest.java
Labels: Breaking Change

#591 Separate out JTS-based enclosing method
  src/main/java/org/openstreetmap/atlas/geography/Polygon.java
Labels: Enhancement

#593 Fixed a file extension in packed2text
  src/main/java/org/openstreetmap/atlas/utilities/command/subcommands/PackedToTextAtlasCommand.java
Labels: Bug

#594 Modernize Clip with GeometryOperation and MultiPolygon union
  src/main/java/org/openstreetmap/atlas/geography/clipping/Clip.java
  src/main/java/org/openstreetmap/atlas/geography/clipping/GeometryOperation.java
  src/main/java/org/openstreetmap/atlas/geography/clipping/MultiPolygonClipper.java
  src/main/java/org/openstreetmap/atlas/geography/clipping/PolygonClipper.java
  src/main/java/org/openstreetmap/atlas/geography/clipping/README.md
  src/test/java/org/openstreetmap/atlas/geography/clipping/GeometryOperationTest.java
Labels: Bug, New Feature

#592 Changed JDK source and target version to JDK 11
  CONTRIBUTING.md
  build.gradle
Labels: Enhancement, Huzzah!
