Repository osmlab/atlas, pull requests merged in 2020-12, with the labels that each got.

#711 TaggableFilters overhauled with new TaggableMatcher class
  config/checkstyle/suppressions.xml
  src/main/java/org/openstreetmap/atlas/tags/Taggable.java
  src/main/java/org/openstreetmap/atlas/tags/filters/TaggableFilter.java
  src/main/java/org/openstreetmap/atlas/tags/filters/TaggableFilterToMatcherConverter.java
  src/main/java/org/openstreetmap/atlas/tags/filters/matcher/ConfiguredTaggableMatcher.java
  src/main/java/org/openstreetmap/atlas/tags/filters/matcher/README.md
  src/main/java/org/openstreetmap/atlas/tags/filters/matcher/TaggableMatcher.java
  src/main/java/org/openstreetmap/atlas/tags/filters/matcher/parsing/Lexer.java
  src/main/java/org/openstreetmap/atlas/tags/filters/matcher/parsing/Parser.java
  src/main/java/org/openstreetmap/atlas/tags/filters/matcher/parsing/SemanticChecker.java
  src/main/java/org/openstreetmap/atlas/tags/filters/matcher/parsing/Token.java
  src/main/java/org/openstreetmap/atlas/tags/filters/matcher/parsing/tree/ASTNode.java
  src/main/java/org/openstreetmap/atlas/tags/filters/matcher/parsing/tree/AndOperator.java
  src/main/java/org/openstreetmap/atlas/tags/filters/matcher/parsing/tree/BangOperator.java
  src/main/java/org/openstreetmap/atlas/tags/filters/matcher/parsing/tree/BinaryOperator.java
  src/main/java/org/openstreetmap/atlas/tags/filters/matcher/parsing/tree/EqualsOperator.java
  src/main/java/org/openstreetmap/atlas/tags/filters/matcher/parsing/tree/LiteralOperand.java
  src/main/java/org/openstreetmap/atlas/tags/filters/matcher/parsing/tree/Operand.java
  src/main/java/org/openstreetmap/atlas/tags/filters/matcher/parsing/tree/OrOperator.java
  src/main/java/org/openstreetmap/atlas/tags/filters/matcher/parsing/tree/RegexOperand.java
  src/main/java/org/openstreetmap/atlas/tags/filters/matcher/parsing/tree/TreePrinter.java
  src/main/java/org/openstreetmap/atlas/tags/filters/matcher/parsing/tree/UnaryOperator.java
  src/main/java/org/openstreetmap/atlas/tags/filters/matcher/parsing/tree/XorOperator.java
  src/main/java/org/openstreetmap/atlas/utilities/command/abstractcommand/AbstractAtlasShellToolsCommand.java
  src/main/java/org/openstreetmap/atlas/utilities/command/subcommands/AtlasSearchCommand.java
  src/main/java/org/openstreetmap/atlas/utilities/command/subcommands/TaggableMatcherPrinterCommand.java
  src/main/java/org/openstreetmap/atlas/utilities/configuration/ConfiguredFilter.java
  src/main/resources/org/openstreetmap/atlas/utilities/command/subcommands/TaggableMatcherPrinterCommandDescriptionSection.txt
  src/main/resources/org/openstreetmap/atlas/utilities/command/subcommands/TaggableMatcherPrinterCommandExamplesSection.txt
  src/test/java/org/openstreetmap/atlas/tags/filters/TaggableFilterToMatcherConverterTest.java
  src/test/java/org/openstreetmap/atlas/tags/filters/matcher/ConfiguredTaggableMatcherTest.java
  src/test/java/org/openstreetmap/atlas/tags/filters/matcher/TaggableMatcherTest.java
  src/test/java/org/openstreetmap/atlas/tags/filters/matcher/parsing/LexerTest.java
  src/test/java/org/openstreetmap/atlas/tags/filters/matcher/parsing/ParserTest.java
  src/test/java/org/openstreetmap/atlas/tags/filters/matcher/parsing/SemanticCheckerTest.java
  src/test/java/org/openstreetmap/atlas/tags/filters/matcher/parsing/tree/ASTNodeTest.java
  src/test/java/org/openstreetmap/atlas/tags/filters/matcher/parsing/tree/TreePrinterTest.java
  src/test/java/org/openstreetmap/atlas/utilities/command/subcommands/AtlasSearchCommandTest.java
  src/test/java/org/openstreetmap/atlas/utilities/command/subcommands/TaggableMatcherPrinterCommandTest.java
  src/test/java/org/openstreetmap/atlas/utilities/configuration/ConfiguredFilterTest.java
  src/test/resources/org/openstreetmap/atlas/tags/filters/matcher/test-matching.json
  src/test/resources/org/openstreetmap/atlas/utilities/configuration/ConfiguredFilterTest.json
Labels: Enhancement, New Feature

#714 Improved TaggableMatcherPrinterCommand outputs
  src/main/java/org/openstreetmap/atlas/tags/filters/matcher/README.md
  src/main/java/org/openstreetmap/atlas/utilities/command/subcommands/TaggableMatcherPrinterCommand.java
  src/test/java/org/openstreetmap/atlas/utilities/command/subcommands/TaggableMatcherPrinterCommandTest.java
Labels: Enhancement

#719 Upgrade to JTS 1.18.0
  dependencies.gradle
Labels: Performance
