Repository osmlab/atlas, pull requests merged in 2020-09, with the labels that each got.

#672 Replace some non-inclusive language
  src/main/java/org/openstreetmap/atlas/geography/atlas/change/testing/AtlasChangeGeneratorRemoveReverseEdges.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/change/validators/ChangeValidator.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/geojson/LineDelimitedGeoJsonConverter.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/items/DirectionalizedEdge.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/items/Edge.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/items/Node.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/items/Route.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/items/complex/RelationToMultiPolygonMemberConverter.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/items/complex/bignode/BigNodeFinder.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/items/complex/highwayarea/ComplexHighwayAreaFinder.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/items/complex/roundabout/ComplexRoundabout.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/multi/MultiAtlas.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/multi/MultiAtlasOverlappingNodesFixer.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/multi/MultiEdge.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/multi/MultiNode.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/packed/PackedAtlasBuilder.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/statistics/coverage/linear/edge/EdgeCoverage.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/validators/AtlasEdgeValidator.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/walker/OsmWayWalker.java
  src/main/java/org/openstreetmap/atlas/geography/boundary/converters/CountryBoundaryMapGeoJsonConverter.java
  src/main/java/org/openstreetmap/atlas/utilities/command/subcommands/AnyToGeoJsonCommand.java
  src/main/java/org/openstreetmap/atlas/utilities/command/subcommands/AtlasSearchCommand.java
  src/main/java/org/openstreetmap/atlas/utilities/command/subcommands/SubAtlasCommand.java
  src/main/java/org/openstreetmap/atlas/utilities/conversion/StringToPredicateConverter.java
  src/test/java/org/openstreetmap/atlas/geography/atlas/change/MultipleChangeAtlasTest.java
  src/test/java/org/openstreetmap/atlas/geography/atlas/items/EdgeTest.java
  src/test/java/org/openstreetmap/atlas/geography/atlas/items/complex/roundabout/ComplexRoundaboutTest.java
  src/test/java/org/openstreetmap/atlas/geography/atlas/routing/AllPathsRouterTest.java
Labels: Deprecation, Enhancement

#674 Replace some non-inclusive language
  .circleci/config.yml
  .travis.yml
  .travis/deploy.sh
  .travis/install.sh
  .travis/merge-dev-to-main-gate.sh
  .travis/merge-dev-to-main.sh
  .travis/tag-main-gate.sh
  .travis/tag-main.sh
  .travis/trigger-release.sh
Labels: Enhancement

#675 Replace some non-inclusive language
  README.md
  gradle.properties
Labels: Enhancement

#667 AtlasDiffCommand to support comparing folders
  src/main/java/org/openstreetmap/atlas/geography/atlas/change/Change.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/change/FeatureChange.java
  src/main/java/org/openstreetmap/atlas/utilities/command/subcommands/AtlasDiffCommand.java
  src/main/resources/org/openstreetmap/atlas/utilities/command/subcommands/AtlasDiffCommandDescriptionSection.txt
  src/main/resources/org/openstreetmap/atlas/utilities/command/subcommands/AtlasDiffCommandExamplesSection.txt
  src/test/java/org/openstreetmap/atlas/utilities/command/subcommands/AtlasDiffCommandTest.java
  src/test/java/org/openstreetmap/atlas/utilities/command/subcommands/AtlasDiffCommandTestRule.java
  src/test/resources/org/openstreetmap/atlas/utilities/command/subcommands/AtlasDiffCommandAtlas1.josm.osm
  src/test/resources/org/openstreetmap/atlas/utilities/command/subcommands/AtlasDiffCommandAtlas2.josm.osm
  src/test/resources/org/openstreetmap/atlas/utilities/command/subcommands/AtlasDiffCommandAtlas3.josm.osm
  src/test/resources/org/openstreetmap/atlas/utilities/command/subcommands/AtlasDiffCommandAtlas4.josm.osm
Labels: New Feature

#676 Replace some non-inclusive language in atlas-shell-tools
  atlas-shell-tools/README.md
  atlas-shell-tools/man/man1/atlas-config-repo.1
  atlas-shell-tools/quick_install_bash.sh
  atlas-shell-tools/quick_install_zsh.sh
  atlas-shell-tools/scripts/atlas-config
Labels: Enhancement

#673 MultiAtlas now can optionally disable overlapping node fixes on antimeridian
  src/main/java/org/openstreetmap/atlas/geography/atlas/multi/MultiAtlas.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/multi/MultiAtlasOverlappingNodesFixer.java
  src/test/java/org/openstreetmap/atlas/geography/atlas/multi/MultiAtlasTest.java
Labels: Enhancement

#671 Capped Rectangle expansion at geographic poles
  src/main/java/org/openstreetmap/atlas/geography/Rectangle.java
  src/main/java/org/openstreetmap/atlas/utilities/scalars/Distance.java
  src/test/java/org/openstreetmap/atlas/geography/RectangleTest.java
  src/test/java/org/openstreetmap/atlas/utilities/scalars/DistanceTest.java
Labels: Bug, Enhancement

#680 Increment JTS and GeoTools
  dependencies.gradle
Labels: Bug

#681 Increment Jackson version and revert GeoTools
  dependencies.gradle
Labels: Bug

#677 Added regex taggable filter
  src/main/java/org/openstreetmap/atlas/tags/filters/README.md
  src/main/java/org/openstreetmap/atlas/tags/filters/RegexTaggableFilter.java
  src/test/java/org/openstreetmap/atlas/tags/filters/RegexTaggableFilterTest.java
Labels: New Feature

#683 Make FeatureChange Constructor Public
  src/main/java/org/openstreetmap/atlas/geography/atlas/change/FeatureChange.java
  src/test/java/org/openstreetmap/atlas/geography/atlas/change/FeatureChangeTest.java
Labels: Enhancement

#685 More documentation updates for Atlas Shell Tools and 1.0.0 release
  atlas-shell-tools/README.md
  atlas-shell-tools/man/man1/atlas-config-activate.1
  atlas-shell-tools/man/man1/atlas-config-deactivate.1
  atlas-shell-tools/man/man1/atlas-config-install.1
  atlas-shell-tools/man/man1/atlas-config-list.1
  atlas-shell-tools/man/man1/atlas-config-log.1
  atlas-shell-tools/man/man1/atlas-config-preset.1
  atlas-shell-tools/man/man1/atlas-config-repo.1
  atlas-shell-tools/man/man1/atlas-config-reset.1
  atlas-shell-tools/man/man1/atlas-config-sync.1
  atlas-shell-tools/man/man1/atlas-config-uninstall.1
  atlas-shell-tools/man/man1/atlas-config-update.1
  atlas-shell-tools/man/man1/atlas-config.1
  atlas-shell-tools/man/man1/atlas.1
  atlas-shell-tools/man/man5/atlas-plumbing.5
  atlas-shell-tools/man/man7/atlas-cli.7
  atlas-shell-tools/man/man7/atlas-cookbook.7
  atlas-shell-tools/man/man7/atlas-environment.7
  atlas-shell-tools/man/man7/atlas-glossary.7
  atlas-shell-tools/man/man7/atlas-presets.7
  atlas-shell-tools/man/man7/atlas-shell-tools.7
  atlas-shell-tools/scripts/common/ast_utilities.pm
Labels: Documentation

#687 Fixed broken anchors in Atlas Shell Tools readme
  atlas-shell-tools/README.md
Labels: Documentation
