Repository osmlab/atlas, pull requests merged in 2020-08, with the labels that each got.

#660 Allow ConfiguredFilter to filter on geometry
  src/main/java/org/openstreetmap/atlas/geography/converters/WkbLocationConverter.java
  src/main/java/org/openstreetmap/atlas/geography/converters/WkbMultiPolyLineConverter.java
  src/main/java/org/openstreetmap/atlas/geography/converters/WkbMultiPolygonConverter.java
  src/main/java/org/openstreetmap/atlas/geography/converters/WkbPolyLineConverter.java
  src/main/java/org/openstreetmap/atlas/geography/converters/WkbPolygonConverter.java
  src/main/java/org/openstreetmap/atlas/utilities/configuration/ConfigurationReader.java
  src/main/java/org/openstreetmap/atlas/utilities/configuration/ConfiguredFilter.java
  src/main/java/org/openstreetmap/atlas/utilities/conversion/HexStringByteArrayConverter.java
  src/test/java/org/openstreetmap/atlas/utilities/configuration/ConfiguredFilterTest.java
  src/test/java/org/openstreetmap/atlas/utilities/conversion/HexStringByteArrayConverterTest.java
  src/test/resources/org/openstreetmap/atlas/utilities/configuration/ConfiguredFilterTest.json
  src/test/resources/org/openstreetmap/atlas/utilities/configuration/geometryFilter.josm.osm
Labels: New Feature

#662 Use ConfiguredFilter in AtlasLoadingOption
  src/main/java/org/openstreetmap/atlas/geography/atlas/command/OsmPbfToAtlasSubCommand.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/pbf/AtlasLoadingOption.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/pbf/BridgeConfiguredFilter.java
  src/main/java/org/openstreetmap/atlas/utilities/configuration/ConfiguredFilter.java
  src/main/resources/org/openstreetmap/atlas/geography/atlas/pbf/atlas-area.json
  src/main/resources/org/openstreetmap/atlas/geography/atlas/pbf/atlas-edge.json
  src/main/resources/org/openstreetmap/atlas/geography/atlas/pbf/atlas-relation-slicing.json
  src/main/resources/org/openstreetmap/atlas/geography/atlas/pbf/atlas-way-section.json
  src/main/resources/org/openstreetmap/atlas/geography/atlas/pbf/osm-pbf-node.json
  src/main/resources/org/openstreetmap/atlas/geography/atlas/pbf/osm-pbf-relation.json
  src/main/resources/org/openstreetmap/atlas/geography/atlas/pbf/osm-pbf-way.json
  src/test/java/org/openstreetmap/atlas/geography/atlas/pbf/BridgeConfiguredFilterTest.java
  src/test/java/org/openstreetmap/atlas/geography/atlas/pbf/OsmPbfIngestTest.java
  src/test/java/org/openstreetmap/atlas/utilities/configuration/ConfiguredFilterTest.java
  src/test/resources/org/openstreetmap/atlas/geography/atlas/pbf/bridgeConfiguredFilter1.json
  src/test/resources/org/openstreetmap/atlas/geography/atlas/pbf/bridgeConfiguredFilter2.json
  src/test/resources/org/openstreetmap/atlas/geography/atlas/pbf/edge-filter.json
  src/test/resources/org/openstreetmap/atlas/utilities/configuration/ConfiguredFilterTest.json
  src/test/resources/org/openstreetmap/atlas/utilities/configuration/ConfiguredFilterTestOtherRoot.json
Labels: New Feature

#659 Made getTTYStringBuilder public and added toJson to ConfiguredFilter
  src/main/java/org/openstreetmap/atlas/utilities/command/abstractcommand/AbstractAtlasShellToolsCommand.java
  src/main/java/org/openstreetmap/atlas/utilities/configuration/ConfiguredFilter.java
  src/test/java/org/openstreetmap/atlas/utilities/configuration/ConfiguredFilterTest.java
Labels: Enhancement

#666 Improvements to IsoCountryCodeCommand, WKTShardCommand, and AtlasSearchCommand
  build.gradle
  dependencies.gradle
  src/main/java/org/openstreetmap/atlas/geography/atlas/Atlas.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/BareAtlas.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/complete/CompleteArea.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/complete/CompleteEdge.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/complete/CompleteLine.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/complete/CompleteNode.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/complete/CompletePoint.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/complete/CompleteRelation.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/complete/EmptyAtlas.java
  src/main/java/org/openstreetmap/atlas/locale/IsoCountryFuzzyMatcher.java
  src/main/java/org/openstreetmap/atlas/utilities/command/subcommands/AtlasSearchCommand.java
  src/main/java/org/openstreetmap/atlas/utilities/command/subcommands/IsoCountryCodeCommand.java
  src/main/java/org/openstreetmap/atlas/utilities/command/subcommands/WKTShardCommand.java
  src/main/java/org/openstreetmap/atlas/utilities/command/subcommands/templates/AtlasLoaderCommand.java
  src/main/resources/org/openstreetmap/atlas/utilities/command/subcommands/AtlasSearchCommandExamplesSection.txt
  src/main/resources/org/openstreetmap/atlas/utilities/command/subcommands/AtlasSearchCommandPredicateSection.txt
  src/main/resources/org/openstreetmap/atlas/utilities/command/subcommands/WKTShardCommandDescriptionSection.txt
  src/main/resources/org/openstreetmap/atlas/utilities/command/subcommands/WKTShardCommandExamplesSection.txt
  src/test/java/org/openstreetmap/atlas/locale/IsoCountryFuzzyMatcherTest.java
  src/test/java/org/openstreetmap/atlas/utilities/command/subcommands/AtlasSearchCommandTest.java
  src/test/java/org/openstreetmap/atlas/utilities/command/subcommands/IsoCountryCodeCommandTest.java
  src/test/java/org/openstreetmap/atlas/utilities/command/subcommands/WKTShardCommandTest.java
Labels: Enhancement

#668 Commands with predicate option can now control imports.
  src/main/java/org/openstreetmap/atlas/utilities/command/subcommands/AtlasSearchCommand.java
  src/main/java/org/openstreetmap/atlas/utilities/command/subcommands/SubAtlasCommand.java
  src/main/java/org/openstreetmap/atlas/utilities/command/subcommands/templates/AtlasLoaderCommand.java
  src/main/resources/org/openstreetmap/atlas/utilities/command/subcommands/AtlasSearchCommandPredicateSection.txt
  src/main/resources/org/openstreetmap/atlas/utilities/command/subcommands/SubAtlasCommandPredicateSection.txt
  src/test/java/org/openstreetmap/atlas/utilities/command/subcommands/AtlasSearchCommandTest.java
  src/test/java/org/openstreetmap/atlas/utilities/command/subcommands/SubAtlasCommandTest.java
  src/test/java/org/openstreetmap/atlas/utilities/command/subcommands/templates/AtlasLoaderCommandTest.java
Labels: Enhancement

#665 Fix sonar vulnerability in Extractor
  src/main/java/org/openstreetmap/atlas/utilities/archive/Extractor.java
  src/main/java/org/openstreetmap/atlas/utilities/archive/UnzipperCommand.java
Labels: Bug

#670 Avoid long overflow while comparing Edges
  src/main/java/org/openstreetmap/atlas/geography/atlas/items/Edge.java
  src/test/java/org/openstreetmap/atlas/geography/atlas/items/EdgeTest.java
Labels: Bug
