Repository osmlab/atlas, pull requests merged in 2021-02, with the labels that each got.

#731 Some updates to AtlasSearchCommand and brand new AtlasMetadataReaderCommand
  src/main/java/org/openstreetmap/atlas/geography/atlas/AtlasMetaData.java
  src/main/java/org/openstreetmap/atlas/utilities/command/abstractcommand/AbstractAtlasShellToolsCommand.java
  src/main/java/org/openstreetmap/atlas/utilities/command/subcommands/AtlasDiffCommand.java
  src/main/java/org/openstreetmap/atlas/utilities/command/subcommands/AtlasMetadataReaderCommand.java
  src/main/java/org/openstreetmap/atlas/utilities/command/subcommands/AtlasSearchCommand.java
  src/main/resources/org/openstreetmap/atlas/utilities/command/subcommands/AtlasMetadataReaderCommandDescriptionSection.txt
  src/main/resources/org/openstreetmap/atlas/utilities/command/subcommands/AtlasMetadataReaderCommandExamplesSection.txt
  src/main/resources/org/openstreetmap/atlas/utilities/command/subcommands/AtlasSearchCommandDescriptionSection.txt
  src/main/resources/org/openstreetmap/atlas/utilities/command/subcommands/AtlasSearchCommandExamplesSection.txt
  src/test/java/org/openstreetmap/atlas/utilities/command/subcommands/AtlasDiffCommandTest.java
  src/test/java/org/openstreetmap/atlas/utilities/command/subcommands/AtlasMetadataReaderCommandTest.java
  src/test/java/org/openstreetmap/atlas/utilities/command/subcommands/AtlasSearchCommandTest.java
Labels: Enhancement, New Feature

#732 Additional cycling tag values
  src/main/java/org/openstreetmap/atlas/tags/CyclewayLaneTag.java
  src/main/java/org/openstreetmap/atlas/tags/CyclewayLeftTag.java
  src/main/java/org/openstreetmap/atlas/tags/CyclewayRightTag.java
  src/main/java/org/openstreetmap/atlas/tags/CyclewayTag.java
Labels: Enhancement

#736 Fix for certain tags being dropped during sectioning
  src/main/java/org/openstreetmap/atlas/geography/atlas/raw/sectioning/AtlasSectionProcessor.java
  src/test/java/org/openstreetmap/atlas/geography/atlas/raw/sectioning/AtlasSectionProcessorTest.java
  src/test/java/org/openstreetmap/atlas/geography/atlas/raw/sectioning/WaySectionProcessorTestRule.java
  src/test/resources/org/openstreetmap/atlas/geography/atlas/raw/sectioning/lineWithLessThanTwoNodesDueToRepeatedLocationAtEndOfLine.atlas.txt
Labels: Bug

#738 Allow expand indefinitely for relation exploration
  src/main/java/org/openstreetmap/atlas/geography/atlas/dynamic/DynamicAtlasExpander.java
  src/test/java/org/openstreetmap/atlas/geography/atlas/dynamic/DynamicAtlasAggressiveRelationsTest.java
  src/test/java/org/openstreetmap/atlas/geography/atlas/dynamic/rules/DynamicAtlasAggressiveRelationsTestRule.java
  src/test/resources/org/openstreetmap/atlas/geography/atlas/dynamic/rules/DynamicAtlasAgressiveRelationsTest_11-998-708.josm.osm
  src/test/resources/org/openstreetmap/atlas/geography/atlas/dynamic/rules/DynamicAtlasAgressiveRelationsTest_11-999-708.josm.osm
Labels: Bug

#744 Added JSON output format for AtlasSearchCommand results
  src/main/java/org/openstreetmap/atlas/geography/atlas/complete/CompleteArea.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/complete/CompleteEdge.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/complete/CompleteEntity.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/complete/CompleteNode.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/complete/CompletePoint.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/complete/CompleteRelation.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/items/AtlasEntity.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/items/AtlasItem.java
  src/main/java/org/openstreetmap/atlas/utilities/command/subcommands/AtlasSearchCommand.java
  src/main/resources/org/openstreetmap/atlas/utilities/command/subcommands/AtlasSearchCommandDescriptionSection.txt
  src/test/java/org/openstreetmap/atlas/utilities/command/subcommands/AtlasSearchCommandTest.java
  src/test/resources/org/openstreetmap/atlas/utilities/command/subcommands/expected-json-features.txt
Labels: Enhancement
