Repository osmlab/atlas, pull requests merged in 2021-01, with the labels that each got.

#710 Refactored way-sectioning
  src/integrationTest/java/org/openstreetmap/atlas/geography/atlas/AtlasIntegrationTest.java
  src/integrationTest/java/org/openstreetmap/atlas/geography/atlas/pbf/OsmPbfIngestIntegrationTest.java
  src/integrationTest/java/org/openstreetmap/atlas/geography/atlas/pbf/slicing/AtlasSectionProcessorIntegrationTest.java
  src/integrationTest/java/org/openstreetmap/atlas/geography/atlas/raw/RawAtlasIntegrationTest.java
  src/main/groovy/org/openstreetmap/atlas/geography/atlas/dsl/schema/uri/impl/AbstractScheme.groovy
  src/main/java/org/openstreetmap/atlas/geography/PolyLine.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/AbstractAtlas.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/command/OsmPbfToAtlasSubCommand.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/converters/AtlasDebugTool.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/pbf/BridgeConfiguredFilter.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/raw/creation/OsmPbfReader.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/raw/creation/README.md
  src/main/java/org/openstreetmap/atlas/geography/atlas/raw/creation/RawAtlasGenerator.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/raw/sectioning/AtlasSectionProcessor.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/raw/sectioning/NodeOccurrenceCounter.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/raw/sectioning/README.md
  src/main/java/org/openstreetmap/atlas/geography/atlas/raw/sectioning/WaySectionChangeSet.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/raw/sectioning/WaySectionProcessor.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/raw/slicing/RawAtlasSlicer.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/raw/temporary/TemporaryEdge.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/raw/temporary/TemporaryEntity.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/raw/temporary/TemporaryLine.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/raw/temporary/TemporaryNode.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/raw/temporary/TemporaryPoint.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/raw/temporary/TemporaryRelation.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/raw/temporary/TemporaryRelationMember.java
  src/main/java/org/openstreetmap/atlas/utilities/command/subcommands/PbfToAtlasCommand.java
  src/main/java/org/openstreetmap/atlas/utilities/configuration/ConfiguredFilter.java
  src/main/java/org/openstreetmap/atlas/utilities/testing/TestAtlasHandler.java
  src/test/java/org/openstreetmap/atlas/geography/atlas/change/diff/AtlasDiffTest.java
  src/test/java/org/openstreetmap/atlas/geography/atlas/pbf/OsmPbfIngestTest.java
  src/test/java/org/openstreetmap/atlas/geography/atlas/raw/creation/RawAtlasGeneratorTest.java
  src/test/java/org/openstreetmap/atlas/geography/atlas/raw/sectioning/AtlasSectionProcessorTest.java
  src/test/java/org/openstreetmap/atlas/geography/atlas/raw/sectioning/WaySectionProcessorTestRule.java
  src/test/java/org/openstreetmap/atlas/geography/atlas/raw/slicing/RawAtlasSlicerTest.java
  src/test/java/org/openstreetmap/atlas/geography/atlas/raw/slicing/RawAtlasSlicerTestRule.java
  src/test/java/org/openstreetmap/atlas/geography/boundary/CountryBoundaryMapTest.java
Labels: Data Change, Enhancement, Huzzah!

#712 Use Jackson instead of Gson for geojson parser
  src/main/java/org/openstreetmap/atlas/geography/geojson/parser/README.md
  src/main/java/org/openstreetmap/atlas/geography/geojson/parser/domain/geometry/MultiLineString.java
  src/main/java/org/openstreetmap/atlas/geography/geojson/parser/domain/geometry/MultiPoint.java
  src/main/java/org/openstreetmap/atlas/geography/geojson/parser/domain/geometry/MultiPolygon.java
  src/main/java/org/openstreetmap/atlas/geography/geojson/parser/domain/geometry/Point.java
  src/main/java/org/openstreetmap/atlas/geography/geojson/parser/domain/geometry/coordinate/Coordinates.java
  src/main/java/org/openstreetmap/atlas/geography/geojson/parser/impl/jackson/GeoJsonParserJacksonImpl.java
  src/test/java/org/openstreetmap/atlas/geography/geojson/parser/impl/jackson/AbstractGeoJsonParserJacksonImplTestBase.java
  src/test/java/org/openstreetmap/atlas/geography/geojson/parser/impl/jackson/GeoJsonParserJacksonImplExtensionsTest.java
  src/test/java/org/openstreetmap/atlas/geography/geojson/parser/impl/jackson/GeoJsonParserJacksonImplTest.java
  src/test/resources/org/openstreetmap/atlas/geography/geojson/parser/featureChangePropertiesExample2.json
  src/test/resources/org/openstreetmap/atlas/geography/geojson/parser/propertiesNested.json
Labels: Bug

#718 Allow configurations to provide subConfigurations for a key
  src/main/java/org/openstreetmap/atlas/utilities/configuration/Configuration.java
  src/main/java/org/openstreetmap/atlas/utilities/configuration/MergedConfiguration.java
  src/main/java/org/openstreetmap/atlas/utilities/configuration/StandardConfiguration.java
  src/test/java/org/openstreetmap/atlas/utilities/configuration/MergedConfigurationTest.java
  src/test/java/org/openstreetmap/atlas/utilities/configuration/StandardConfigurationTest.java
Labels: New Feature

#725 Add CI support for Github Actions
  .github/workflow_data/secret.gpg.aes256
  .github/workflow_scripts/decrypt_gpg_key.sh
  .github/workflow_scripts/deploy.sh
  .github/workflow_scripts/merge-dev-to-main.sh
  .github/workflow_scripts/sonar.sh
  .github/workflow_scripts/tag-main.sh
  .github/workflows/ci.yml
  .travis.yml
  README.md
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
Labels: New Feature, Testing

#726 Expand OneWay tag coverage: Motor and Bicycle
  gradle.properties
  src/main/java/org/openstreetmap/atlas/geography/atlas/builder/GeoJsonAtlasBuilder.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/raw/sectioning/PbfOneWay.java
  src/main/java/org/openstreetmap/atlas/tags/OneWayTag.java
  src/main/java/org/openstreetmap/atlas/tags/oneway/OneWayTag.java
  src/main/java/org/openstreetmap/atlas/tags/oneway/bicycle/BicycleOneWayTag.java
  src/main/java/org/openstreetmap/atlas/tags/oneway/bicycle/CyclewayLeftOneWayTag.java
  src/main/java/org/openstreetmap/atlas/tags/oneway/bicycle/CyclewayOneWayTag.java
  src/main/java/org/openstreetmap/atlas/tags/oneway/bicycle/CyclewayRightOneWayTag.java
  src/main/java/org/openstreetmap/atlas/tags/oneway/bicycle/OneWayBicycleTag.java
  src/main/java/org/openstreetmap/atlas/tags/oneway/motor/OneWayMotorVehicleTag.java
  src/main/java/org/openstreetmap/atlas/tags/oneway/motor/OneWayMotorcarTag.java
  src/main/java/org/openstreetmap/atlas/tags/oneway/motor/OneWayVehicleTag.java
  src/test/java/org/openstreetmap/atlas/geography/atlas/pbf/store/PbfOneWayTest.java
  src/test/java/org/openstreetmap/atlas/tags/cache/TaggerTestCase.java
  src/test/java/org/openstreetmap/atlas/tags/oneway/OneWayTagTest.java
Labels: Breaking Change, New Feature

#728 EntityIdentifierGenerator now has some config options
  src/main/java/org/openstreetmap/atlas/utilities/identifiers/EntityIdentifierGenerator.java
  src/test/java/org/openstreetmap/atlas/utilities/identifiers/EntityIdentifierGeneratorTest.java
Labels: Enhancement
