Repository osmlab/atlas, pull requests merged in 2021-04, with the labels that each got.

#753 Fix issue with snaps
  src/main/java/org/openstreetmap/atlas/geography/atlas/Atlas.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/BareAtlas.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/complete/EmptyAtlas.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/routing/AbstractRouter.java
  src/test/java/org/openstreetmap/atlas/geography/atlas/packed/PackedAtlasTest.java
Labels: Breaking Change, Bug

#752 Allocation Perf fixes
  src/main/java/org/openstreetmap/atlas/geography/PolyLine.java
  src/main/java/org/openstreetmap/atlas/geography/Polygon.java
  src/main/java/org/openstreetmap/atlas/geography/StringCompressedPolyLine.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/packed/PackedTagStore.java
  src/main/java/org/openstreetmap/atlas/utilities/collections/Iterables.java
  src/main/java/org/openstreetmap/atlas/utilities/collections/StringList.java
  src/main/java/org/openstreetmap/atlas/utilities/regex/RegexUtils.java
  src/test/resources/org/openstreetmap/atlas/geography/atlas/line-delimited-geojson.txt
Labels: Performance

#754 Add consolidate logic
  src/main/java/org/openstreetmap/atlas/geography/atlas/items/Relation.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/items/complex/MultiPolygonRelationToMemberConverter.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/items/complex/RelationOrAreaToMultiPolygonConverter.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/items/complex/RelationToMultiPolygonMemberConverter.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/pbf/AtlasLoadingOption.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/raw/slicing/RawAtlasSlicer.java
  src/main/java/org/openstreetmap/atlas/geography/atlas/statistics/coverage/poi/SimpleCoverage.java
  src/main/java/org/openstreetmap/atlas/tags/RelationTypeTag.java
  src/main/resources/org/openstreetmap/atlas/geography/atlas/pbf/atlas-relation-slicing.json
  src/test/java/org/openstreetmap/atlas/geography/atlas/raw/slicing/RawAtlasSlicerTest.java
  src/test/java/org/openstreetmap/atlas/geography/atlas/raw/slicing/RawAtlasSlicerTestRule.java
Labels: Data Change, Enhancement
